//! FCX-PACK — emit a complete, buildable native-app project from FCX.
//!
//! v0.1 of flux-fcx was a *string* transpiler (FCX → `.slint`). v0.2 makes it
//! an **app emitter**: given FCX source + an app name it produces every file
//! `fluxc build` (or `cargo build`) needs to cross-compile a native Slint
//! desktop binary — no Chromium, no bundled JS runtime, ~5–12 MB:
//!
//! ```text
//! <out>/Cargo.toml     — slint dep + bin target
//! <out>/build.rs       — slint-build compiles ui.slint at build time
//! <out>/ui.slint       — the transpiled UI (from slintgen)
//! <out>/src/main.rs    — slint::include_modules! → <Component>::new()?.run()
//! ```
//!
//! Build it native:           `fluxc build`  (in <out>)
//! Cross-build a Windows exe:  `fluxc build --target x86_64-pc-windows-gnu`
//!
//! That last step is the Electron-killer payoff — one fluxc command, a real
//! `.exe`, authored in FCX/TS, rendered by Slint.

use crate::{parse_program, root_component, to_slint_program};
use anyhow::Result;

/// A generated app as (relative-path, file-content) pairs — write it with
/// [`write_app`] or inspect it in tests without touching disk.
#[derive(Debug, Clone, PartialEq)]
pub struct AppProject {
    pub app_name: String,
    pub component: String,
    pub files: Vec<(String, String)>,
}

impl AppProject {
    pub fn get(&self, path: &str) -> Option<&str> {
        self.files.iter().find(|(p, _)| p == path).map(|(_, c)| c.as_str())
    }
}

/// Build a complete app project from FCX source.
pub fn emit_app(src: &str, app_name: &str) -> Result<AppProject> {
    let components = parse_program(src)?;
    let ui = to_slint_program(&components);
    let comp = root_component(&components).name.clone();

    let cargo = format!(
        "[package]\n\
         name = \"{app_name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         # Generated by flux-fcx (FCX-PACK). Authored in FCX/TS, rendered by Slint.\n\
         \n\
         [dependencies]\n\
         # software renderer + winit = pure Rust, cross-compiles clean (skia/femtovg do NOT).\n\
         slint = {{ version = \"1\", default-features = false, features = [\"compat-1-2\", \"std\", \"renderer-software\", \"backend-winit\"] }}\n\
         \n\
         [build-dependencies]\n\
         slint-build = \"1\"\n\
         \n\
         # tiny release binary (the Electron-killer flex)\n\
         [profile.release]\n\
         opt-level = \"z\"\n\
         lto = true\n\
         strip = true\n\
         panic = \"abort\"\n\
         codegen-units = 1\n"
    );

    // Cross-build linker: windows-gnu → mingw-w64. Makes
    // `fluxc build --target x86_64-pc-windows-gnu` work out of the box.
    let cargo_config =
        "[target.x86_64-pc-windows-gnu]\nlinker = \"x86_64-w64-mingw32-gcc\"\n".to_string();

    let build_rs =
        "// Generated by flux-fcx. Compiles the transpiled UI at build time.\n\
         fn main() {\n    slint_build::compile(\"ui.slint\").unwrap();\n}\n"
            .to_string();

    let main_rs = format!(
        "// Generated by flux-fcx (FCX-PACK) — entry point.\n\
         // release = GUI app (no console window); debug keeps a console for logs.\n\
         #![cfg_attr(not(debug_assertions), windows_subsystem = \"windows\")]\n\
         // The UI module comes from build.rs compiling ui.slint.\n\
         slint::include_modules!();\n\
         \n\
         fn main() -> Result<(), slint::PlatformError> {{\n\
         \x20   let ui = {comp}::new()?;\n\
         \x20   ui.run()\n\
         }}\n"
    );

    Ok(AppProject {
        app_name: app_name.to_string(),
        component: comp,
        files: vec![
            ("Cargo.toml".to_string(), cargo),
            (".cargo/config.toml".to_string(), cargo_config),
            ("build.rs".to_string(), build_rs),
            ("ui.slint".to_string(), ui),
            ("src/main.rs".to_string(), main_rs),
        ],
    })
}

/// Write a generated app to `out_dir`, creating directories as needed.
/// Returns the absolute paths written.
pub fn write_app(src: &str, app_name: &str, out_dir: &std::path::Path) -> Result<Vec<std::path::PathBuf>> {
    let project = emit_app(src, app_name)?;
    let mut written = Vec::new();
    for (rel, content) in &project.files {
        let path = out_dir.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, content)?;
        written.push(path);
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    const COUNTER: &str = r#"
export function Counter() {
  const [count, setCount] = useState(0);
  return (
    <vbox>
      <text>Count: {count}</text>
      <button onClick={() => setCount(count + 1)}>Increment</button>
    </vbox>
  );
}
"#;

    #[test]
    fn emits_the_project_files() {
        let app = emit_app(COUNTER, "counter-app").unwrap();
        let paths: Vec<&str> = app.files.iter().map(|(p, _)| p.as_str()).collect();
        assert_eq!(
            paths,
            vec!["Cargo.toml", ".cargo/config.toml", "build.rs", "ui.slint", "src/main.rs"]
        );
        assert_eq!(app.component, "Counter");
    }

    #[test]
    fn cargo_toml_is_cross_build_ready() {
        let app = emit_app(COUNTER, "counter-app").unwrap();
        let cargo = app.get("Cargo.toml").unwrap();
        assert!(cargo.contains("name = \"counter-app\""));
        assert!(cargo.contains("renderer-software"), "must use cross-friendly software renderer");
        assert!(cargo.contains("slint-build = \"1\""));
        assert!(cargo.contains("opt-level = \"z\""), "tiny release profile");
        // mingw linker wired for windows-gnu cross-build
        assert!(app.get(".cargo/config.toml").unwrap().contains("x86_64-w64-mingw32-gcc"));
    }

    #[test]
    fn main_rs_drops_console_in_release() {
        let app = emit_app(COUNTER, "counter-app").unwrap();
        assert!(app
            .get("src/main.rs")
            .unwrap()
            .contains("windows_subsystem = \"windows\""));
    }

    #[test]
    fn main_rs_instantiates_and_runs_the_component() {
        let app = emit_app(COUNTER, "counter-app").unwrap();
        let main = app.get("src/main.rs").unwrap();
        assert!(main.contains("slint::include_modules!();"));
        assert!(main.contains("let ui = Counter::new()?;"));
        assert!(main.contains("ui.run()"));
    }

    #[test]
    fn build_rs_compiles_the_ui() {
        let app = emit_app(COUNTER, "counter-app").unwrap();
        assert!(app.get("build.rs").unwrap().contains("slint_build::compile(\"ui.slint\")"));
    }

    #[test]
    fn ui_slint_is_the_transpiled_component() {
        let app = emit_app(COUNTER, "counter-app").unwrap();
        let ui = app.get("ui.slint").unwrap();
        assert!(ui.contains("export component Counter inherits Window {"));
        assert!(ui.contains("clicked => { count = count + 1; }"));
    }

    #[test]
    fn write_app_creates_files_on_disk() {
        let dir = std::env::temp_dir().join(format!("flux-fcx-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let written = write_app(COUNTER, "counter-app", &dir).unwrap();
        assert_eq!(written.len(), 5);
        assert!(dir.join("src/main.rs").exists());
        assert!(dir.join("ui.slint").exists());
        assert!(dir.join(".cargo/config.toml").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
