//! Slint code generation — UI-IR → `.slint` markup.
//!
//! Maps the FCX dialect onto Slint: `useState` → `property`, `vbox`/`hbox` →
//! `VerticalBox`/`HorizontalBox`, `text`/`button` → `Text`/`Button`, text
//! interpolation `{count}` → Slint's `\{count}`, and `onClick={()=>setX(e)}`
//! → `clicked => { x = e; }`. The output compiles with `slint-build`/`slint`
//! and renders via flux-gui's Slint runtime — no Chromium, no JS at runtime.

use crate::ir::*;

/// Transpile a single parsed [`Component`] to `.slint` source.
pub fn to_slint(c: &Component) -> String {
    to_slint_program(std::slice::from_ref(c))
}

/// Transpile a whole program (1+ components) to `.slint`. Components referenced
/// by others are emitted as plain sub-components (defined first); the rest are
/// the app roots (`export ... inherits Window`).
pub fn to_slint_program(comps: &[Component]) -> String {
    let mut out = String::new();
    let title = comps.first().map(|c| c.name.as_str()).unwrap_or("App");
    out.push_str(&format!("// Generated by flux-fcx from {title}.fcx — do not edit by hand.\n"));

    // imports = union of std-widgets used across every component tree
    let mut imports = std::collections::BTreeSet::new();
    for c in comps {
        walk(&c.root, &mut imports);
    }
    if !imports.is_empty() {
        let list: Vec<String> = imports.into_iter().collect();
        out.push_str(&format!(
            "import {{ {} }} from \"std-widgets.slint\";\n",
            list.join(", ")
        ));
    }
    out.push('\n');

    let referenced = referenced_components(comps);
    // sub-components first (defined before use), then app roots
    for c in comps {
        if referenced.contains(&c.name) {
            out.push_str(&gen_component(c, false));
            out.push('\n');
        }
    }
    for c in comps {
        if !referenced.contains(&c.name) {
            out.push_str(&gen_component(c, true));
            out.push('\n');
        }
    }
    out
}

/// The app's entry component (first one not used by any other).
pub fn root_component(comps: &[Component]) -> &Component {
    let referenced = referenced_components(comps);
    comps
        .iter()
        .find(|c| !referenced.contains(&c.name))
        .unwrap_or(&comps[0])
}

fn gen_component(c: &Component, is_root: bool) -> String {
    let mut out = String::new();
    if is_root {
        out.push_str(&format!("export component {} inherits Window {{\n", c.name));
        // v0.5: a tasteful default theme so packed apps look designed out of
        // the box (Catppuccin-Mocha palette). The dev writes zero styling.
        out.push_str(&format!("    title: \"{}\";\n", c.name));
        out.push_str("    preferred-width: 460px;\n");
        out.push_str("    preferred-height: 360px;\n");
        out.push_str("    background: #1e1e2e;\n");
        out.push_str("    default-font-size: 16px;\n");
        out.push_str("    default-font-family: \"Inter\";\n");
    } else {
        out.push_str(&format!("component {} {{\n", c.name));
    }
    for s in &c.states {
        // useState is mutable read/write → `in-out` so the Slint runtime AND native Rust can both
        // get/set it. This is what lets a packed app feed live data into the UI (e.g. flux-deck
        // streaming real terminal output via ui.set_<state>()). A plain `property` is private (E0624).
        out.push_str(&format!(
            "    in-out property <{}> {}: {};\n",
            s.ty.slint_ty(),
            s.name,
            slint_init(s)
        ));
    }
    // Native callbacks: a handler like onClick={() => run("upload")} whose name is NOT a useState
    // setter is a NATIVE action — declare it as a Slint callback the packed app's Rust binds
    // (ui.on_run(...)). This is what lets FCX buttons/inputs actually DO things (run a shell, scp).
    let mut cbs = std::collections::BTreeSet::new();
    collect_callbacks(&c.root, c, &mut cbs);
    for cb in &cbs {
        out.push_str(&format!("    callback {}(string);\n", cb));
    }
    out.push_str(&gen_node(&c.root, c, 1));
    out.push_str("}\n");
    out
}

// Collect native-callback names: handlers whose setter doesn't match any useState setter.
fn collect_callbacks(node: &Node, comp: &Component, out: &mut std::collections::BTreeSet<String>) {
    match node {
        Node::Element(e) => {
            for p in &e.props {
                if let PropValue::Handler(h) = &p.value {
                    if comp.state_for_setter(&h.setter).is_none() {
                        out.insert(h.setter.clone());
                    }
                }
            }
            for ch in &e.children {
                collect_callbacks(ch, comp, out);
            }
        }
        Node::If { body, .. } | Node::For { body, .. } => collect_callbacks(body, comp, out),
        Node::Text(_) => {}
    }
}

fn referenced_components(comps: &[Component]) -> std::collections::BTreeSet<String> {
    let names: std::collections::BTreeSet<String> = comps.iter().map(|c| c.name.clone()).collect();
    let mut refd = std::collections::BTreeSet::new();
    for c in comps {
        collect_refs(&c.root, &names, &mut refd);
    }
    refd
}

fn collect_refs(
    node: &Node,
    names: &std::collections::BTreeSet<String>,
    refd: &mut std::collections::BTreeSet<String>,
) {
    match node {
        Node::Element(e) => {
            if names.contains(&e.tag) {
                refd.insert(e.tag.clone());
            }
            for ch in &e.children {
                collect_refs(ch, names, refd);
            }
        }
        Node::If { body, .. } | Node::For { body, .. } => collect_refs(body, names, refd),
        Node::Text(_) => {}
    }
}

/// Slint widget name for an FCX tag.
fn slint_tag(tag: &str) -> String {
    match tag {
        "vbox" => "VerticalBox".to_string(),
        "hbox" => "HorizontalBox".to_string(),
        "button" => "Button".to_string(),
        "text" => "Text".to_string(),
        // <terminal>{frame}</terminal> — embed a ratatui/flux-cockpit TUI: a monospace Text
        // bound to a `frame` string (the TUI rendered to text via flux_fcx::terminal::buffer_to_frame).
        "terminal" => "Text".to_string(),
        "input" => "LineEdit".to_string(), // text input → typed commands / paths (native callback)
        "keys" => "FocusScope".to_string(), // captures physical arrow/Enter/Esc keys → navkey() callback
        other => {
            let mut ch = other.chars();
            match ch.next() {
                Some(f) => f.to_uppercase().collect::<String>() + ch.as_str(),
                None => String::new(),
            }
        }
    }
}

/// Which std-widgets need importing (Text is built-in, needs none).
fn walk(node: &Node, set: &mut std::collections::BTreeSet<String>) {
    match node {
        Node::Element(e) => {
            match e.tag.as_str() {
                "vbox" => {
                    set.insert("VerticalBox".into());
                }
                "hbox" => {
                    set.insert("HorizontalBox".into());
                }
                "button" => {
                    set.insert("Button".into());
                }
                "input" => {
                    set.insert("LineEdit".into());
                }
                _ => {}
            }
            for c in &e.children {
                walk(c, set);
            }
        }
        Node::If { body, .. } | Node::For { body, .. } => walk(body, set),
        Node::Text(_) => {}
    }
}

fn slint_init(s: &State) -> String {
    match s.ty {
        StateTy::Str => {
            // normalise single-quoted JS strings to Slint double-quotes
            let t = s.init.trim();
            if t.starts_with('\'') && t.ends_with('\'') && t.len() >= 2 {
                format!("\"{}\"", &t[1..t.len() - 1])
            } else {
                t.to_string()
            }
        }
        _ => s.init.clone(),
    }
}

fn gen_node(node: &Node, comp: &Component, indent: usize) -> String {
    match node {
        // bare Text is consumed by its parent element as the `text:` property
        Node::Text(_) => String::new(),
        Node::Element(e) => gen_element(e, comp, indent),
        Node::If { cond, body } => {
            let pad = "    ".repeat(indent);
            let inner = gen_node(body, comp, indent);
            // splice `if cond : ` in front of the body element (replacing its pad)
            match inner.strip_prefix(&pad) {
                Some(rest) => format!("{pad}if {cond} : {rest}"),
                None => format!("{pad}if {cond} : {}", inner.trim_start()),
            }
        }
        Node::For { item, list, body } => {
            let pad = "    ".repeat(indent);
            let inner = gen_node(body, comp, indent);
            match inner.strip_prefix(&pad) {
                Some(rest) => format!("{pad}for {item} in {list} : {rest}"),
                None => format!("{pad}for {item} in {list} : {}", inner.trim_start()),
            }
        }
    }
}

fn gen_element(e: &Element, comp: &Component, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let tag = slint_tag(&e.tag);

    // text content: from a child Text node, else a `text`/`label` string prop
    let text_expr = e
        .children
        .iter()
        .find_map(|n| match n {
            Node::Text(t) => Some(text_to_slint(t)),
            _ => None,
        })
        .or_else(|| {
            e.props.iter().find_map(|p| match (&p.name[..], &p.value) {
                ("text" | "label", PropValue::Literal(l)) => Some(format!("\"{}\"", escape(l))),
                _ => None,
            })
        });

    let handler = e.props.iter().find_map(|p| match &p.value {
        PropValue::Handler(h) => Some(h),
        _ => None,
    });

    let mut body = String::new();
    if let Some(tx) = text_expr {
        body.push_str(&format!("{pad}    text: {tx};\n"));
    }
    // size props: w/width, h/height (a number) → fixed px, so FCX can lay out a real grid (600px cells).
    for p in &e.props {
        let v = match &p.value { PropValue::Literal(l) => Some(l.clone()), PropValue::Bind(b) => Some(b.clone()), _ => None };
        if let Some(v) = v {
            let v = v.trim().trim_end_matches("px");
            match &p.name[..] {
                "w" | "width" => body.push_str(&format!("{pad}    width: {}px;\n", v)),
                "h" | "height" => body.push_str(&format!("{pad}    height: {}px;\n", v)),
                _ => {}
            }
        }
    }
    // <terminal> embeds a TUI (ratatui/flux-cockpit): monospace, terminal-green, no reflow so the
    // rendered frame's columns/box-drawing line up exactly. Otherwise plain readable Text.
    if e.tag == "terminal" {
        body.push_str(&format!("{pad}    font-family: \"monospace\";\n"));
        body.push_str(&format!("{pad}    color: #a6e3a1;\n"));
        body.push_str(&format!("{pad}    wrap: no-wrap;\n"));
    } else if tag == "Text" {
        body.push_str(&format!("{pad}    color: #cdd6f4;\n"));
    }
    // <keys> → FocusScope: forward physical arrow/Enter/Esc to the `navkey` callback so terminal
    // selection menus (Claude Code yes/no prompts) are drivable with the real keyboard. Auto-grabs focus.
    if e.tag == "keys" {
        // NOTE: do NOT auto-grab focus — that steals keystrokes from the prompt box (broke login typing).
        // The scope captures arrows only once the user clicks into the grid to focus it.
        body.push_str(&format!("{pad}    key-pressed(event) => {{\n"));
        body.push_str(&format!("{pad}        if (event.text == Key.UpArrow) {{ navkey(\"up\"); return EventResult.accept; }}\n"));
        body.push_str(&format!("{pad}        if (event.text == Key.DownArrow) {{ navkey(\"down\"); return EventResult.accept; }}\n"));
        body.push_str(&format!("{pad}        if (event.text == Key.Return) {{ navkey(\"enter\"); return EventResult.accept; }}\n"));
        body.push_str(&format!("{pad}        if (event.text == Key.Escape) {{ navkey(\"esc\"); return EventResult.accept; }}\n"));
        body.push_str(&format!("{pad}        return EventResult.reject;\n"));
        body.push_str(&format!("{pad}    }}\n"));
    }
    // <input> → LineEdit: placeholder from the `placeholder` prop.
    if e.tag == "input" {
        if let Some(ph) = e.props.iter().find_map(|p| match (&p.name[..], &p.value) {
            ("placeholder", PropValue::Literal(l)) => Some(l.clone()),
            _ => None,
        }) {
            body.push_str(&format!("{pad}    placeholder-text: \"{}\";\n", escape(&ph)));
        }
    }
    if let Some(h) = handler {
        if e.tag == "input" {
            // typed text + Enter → native callback gets the value: accepted(txt) => cmd(txt)
            body.push_str(&format!("{pad}    accepted(txt) => {{ {}(txt); }}\n", h.setter));
        } else if let Some(s) = comp.state_for_setter(&h.setter) {
            // useState setter → property assignment
            body.push_str(&format!("{pad}    clicked => {{ {} = {}; }}\n", s.name, h.expr));
        } else {
            // native callback (run a shell, scp, …) — bound in Rust via ui.on_<name>()
            let arg = if h.expr.trim().is_empty() { String::from("\"\"") } else { h.expr.clone() };
            body.push_str(&format!("{pad}    clicked => {{ {}({}); }}\n", h.setter, arg));
        }
    }
    // nested container children (elements + conditionals + lists)
    for ch in &e.children {
        if matches!(ch, Node::Element(_) | Node::If { .. } | Node::For { .. }) {
            body.push_str(&gen_node(ch, comp, indent + 1));
        }
    }

    format!("{pad}{tag} {{\n{body}{pad}}}\n")
}

/// Build one Slint string literal from interpolated text parts.
fn text_to_slint(t: &Text) -> String {
    let mut s = String::from("\"");
    for (i, part) in t.parts.iter().enumerate() {
        if i > 0 {
            s.push(' ');
        }
        match part {
            TextPart::Lit(l) => s.push_str(&escape(l)),
            TextPart::Interp(e) => {
                s.push_str("\\{");
                s.push_str(e);
                s.push('}');
            }
        }
    }
    s.push('"');
    s
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse_component;

    const COUNTER: &str = r#"
export function Counter() {
  const [count, setCount] = useState(0);
  return (
    <vbox>
      <text>Count: {count}</text>
      <button onClick={() => setCount(count + 1)}>Increment</button>
    </vbox>
  );
}
"#;

    #[test]
    fn generates_property_from_state() {
        let c = parse_component(COUNTER).unwrap();
        let slint = to_slint(&c);
        assert!(slint.contains("property <int> count: 0;"), "got:\n{slint}");
    }

    #[test]
    fn maps_tags_and_imports() {
        let slint = to_slint(&parse_component(COUNTER).unwrap());
        assert!(slint.contains("import { Button, VerticalBox } from \"std-widgets.slint\";"), "got:\n{slint}");
        assert!(slint.contains("VerticalBox {"));
        assert!(slint.contains("Button {"));
        assert!(slint.contains("Text {"));
    }

    #[test]
    fn interpolation_becomes_slint_backslash_brace() {
        let slint = to_slint(&parse_component(COUNTER).unwrap());
        assert!(slint.contains(r#"text: "Count: \{count}";"#), "got:\n{slint}");
    }

    #[test]
    fn onclick_becomes_clicked_assignment() {
        let slint = to_slint(&parse_component(COUNTER).unwrap());
        assert!(slint.contains("clicked => { count = count + 1; }"), "got:\n{slint}");
    }

    #[test]
    fn declares_exported_component() {
        let slint = to_slint(&parse_component(COUNTER).unwrap());
        assert!(slint.contains("export component Counter inherits Window {"));
    }

    // Embed a flux-cockpit / ratatui TUI inside an FCX app: <terminal>{frame}</terminal> →
    // a monospace, no-wrap Slint Text bound to the `frame` string (the TUI rendered to text).
    const COCKPIT_EMBED: &str = r#"
export function CockpitApp() {
  const [frame, setFrame] = useState('loading...');
  return (
    <vbox>
      <text>flux-cockpit (embedded TUI)</text>
      <terminal>{frame}</terminal>
    </vbox>
  );
}
"#;

    #[test]
    fn terminal_tag_embeds_monospace_tui_frame() {
        let slint = to_slint(&parse_component(COCKPIT_EMBED).unwrap());
        // monospace + no reflow so the rendered TUI frame lines up
        assert!(slint.contains("font-family: \"monospace\""), "no monospace:\n{slint}");
        assert!(slint.contains("wrap: no-wrap"), "no no-wrap:\n{slint}");
        // the frame state is declared and bound into the terminal's text
        assert!(slint.contains("property <string> frame:"), "frame state missing:\n{slint}");
        assert!(slint.contains("\\{frame}"), "frame not bound into terminal text:\n{slint}");
        // it's a Text element (no unknown widget import needed)
        assert!(!slint.contains("Terminal {"), "should map to Text, not a Terminal widget:\n{slint}");
    }
}
