// v0.17-B — static HTML docsite generator.
//
// One self-contained HTML page that documents both the REST surface
// (from a generate_openapi Value) and the live event surface (from a
// Vec<EventVariant>). Designed to land at `quillon.xyz/api/<crate>/index.html`
// served by q-flux or any static host. No JS framework, no build step.
//
// Layout (server-rendered, no JS required to view):
//   <h1>title</h1>
//   <h2>REST endpoints</h2>
//     <section per path > <method> <summary> <params> </section>
//   <h2>Live events</h2>
//     <section per variant > <type> <fields> </section>
//   <pre>full OpenAPI JSON</pre>      ← embedded for JS readers
//   <pre>events JSON</pre>            ← same, embedded

use crate::event_types::EventVariant;
use serde_json::Value;

pub fn render_docsite(title: &str, openapi: &Value, events: &[EventVariant]) -> String {
    let mut s = String::new();
    s.push_str("<!doctype html>\n");
    s.push_str("<html lang=\"en\">\n<head>\n");
    s.push_str("<meta charset=\"utf-8\" />\n");
    s.push_str(&format!("<title>{} — API docs</title>\n", html_escape(title)));
    s.push_str("<style>\n");
    s.push_str(include_str!("docsite.css.inline.txt"));
    s.push_str(DOCSITE_EXTRA_CSS);
    s.push_str("</style>\n");
    s.push_str("</head>\n<body>\n");
    s.push_str(&format!("<h1>{}</h1>\n", html_escape(title)));
    s.push_str(&format!(
        "<p class=\"sub\">Generated by Flux API Builder. {} REST endpoint(s), {} event variant(s).</p>\n",
        count_endpoints(openapi),
        events.len()
    ));
    // Live filter — type to narrow the endpoint list (no deps, no build step).
    s.push_str(
        "<input id=\"ep-filter\" class=\"ep-filter\" placeholder=\"Filter endpoints — path, verb, or summary…\" oninput=\"fluxFilter(this.value)\" />\n",
    );

    render_rest_section(&mut s, openapi);
    render_events_section(&mut s, events);
    render_embedded_json(&mut s, openapi, events);

    s.push_str(DOCSITE_SCRIPT);
    s.push_str("</body>\n</html>\n");
    s
}

/// Supplementary styling layered over `docsite.css.inline.txt` — the filter box,
/// the curl snippet block, and a copy button. Kept inline so the docsite stays a
/// single self-contained file.
const DOCSITE_EXTRA_CSS: &str = "\n.ep-filter{width:100%;box-sizing:border-box;margin:8px 0 18px;padding:10px 12px;border-radius:8px;border:1px solid #ffffff22;background:#0b0712;color:#e8e3f5;font:14px ui-monospace,monospace}\n.ep-filter:focus{outline:none;border-color:#88c0d0;box-shadow:0 0 0 2px #88c0d033}\n.curl{display:flex;gap:8px;align-items:center;margin:8px 0 0}\n.curl pre{flex:1;margin:0;padding:8px 10px;background:#05030c;border-radius:6px;overflow:auto;font:12px ui-monospace,monospace;color:#a3be8c}\n.curl button{background:#88c0d022;border:1px solid #88c0d055;color:#88c0d0;border-radius:6px;padding:6px 10px;cursor:pointer;font:12px ui-monospace,monospace}\n.curl button:hover{background:#88c0d044}\n";

/// Tiny vanilla-JS controller: live filter over `section.endpoint` + copy-curl.
const DOCSITE_SCRIPT: &str = "<script>\nfunction fluxFilter(q){q=(q||'').toLowerCase();document.querySelectorAll('section.endpoint').forEach(function(el){el.style.display=el.textContent.toLowerCase().indexOf(q)>-1?'':'none';});}\nfunction fluxCopy(b){var pre=b.parentElement.querySelector('pre');navigator.clipboard&&navigator.clipboard.writeText(pre.textContent);b.textContent='copied';setTimeout(function(){b.textContent='copy';},1200);}\n</script>\n";

fn count_endpoints(openapi: &Value) -> usize {
    openapi["paths"]
        .as_object()
        .map(|p| {
            p.values()
                .map(|path_obj| {
                    path_obj
                        .as_object()
                        .map(|o| {
                            o.keys()
                                .filter(|k| matches!(k.as_str(),
                                    "get" | "post" | "put" | "delete" | "patch"))
                                .count()
                        })
                        .unwrap_or(0)
                })
                .sum()
        })
        .unwrap_or(0)
}

fn render_rest_section(s: &mut String, openapi: &Value) {
    s.push_str("<h2>REST endpoints</h2>\n");
    let Some(paths) = openapi["paths"].as_object() else {
        s.push_str("<p class=\"empty\">No paths defined.</p>\n");
        return;
    };
    if paths.is_empty() {
        s.push_str("<p class=\"empty\">No paths defined.</p>\n");
        return;
    }
    // Base URL for the copy-curl snippets (falls back to a relative path).
    let base = openapi["servers"][0]["url"].as_str().unwrap_or("");
    let mut sorted: Vec<_> = paths.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(b.0));
    for (path, ops) in sorted {
        let Some(ops_obj) = ops.as_object() else { continue };
        let mut methods: Vec<_> = ops_obj.iter().collect();
        methods.sort_by(|a, b| a.0.cmp(b.0));
        for (verb, op) in methods {
            if !matches!(verb.as_str(), "get" | "post" | "put" | "delete" | "patch") {
                continue;
            }
            s.push_str("<section class=\"endpoint\">\n");
            s.push_str(&format!(
                "<h3><span class=\"verb verb-{}\">{}</span> <code>{}</code></h3>\n",
                verb,
                verb.to_uppercase(),
                html_escape(path),
            ));
            if let Some(summary) = op["summary"].as_str() {
                if !summary.is_empty() {
                    s.push_str(&format!("<p class=\"summary\">{}</p>\n", html_escape(summary)));
                }
            }
            if let Some(params) = op["parameters"].as_array() {
                if !params.is_empty() {
                    s.push_str("<table class=\"params\"><thead><tr><th>name</th><th>in</th><th>required</th><th>type</th></tr></thead><tbody>\n");
                    for p in params {
                        s.push_str(&format!(
                            "<tr><td><code>{}</code></td><td>{}</td><td>{}</td><td><code>{}</code></td></tr>\n",
                            html_escape(p["name"].as_str().unwrap_or("")),
                            html_escape(p["in"].as_str().unwrap_or("")),
                            if p["required"].as_bool().unwrap_or(false) { "yes" } else { "no" },
                            html_escape(p["schema"]["type"].as_str().unwrap_or("?")),
                        ));
                    }
                    s.push_str("</tbody></table>\n");
                }
            }
            // Copy-as-curl — a try-it affordance with zero runtime deps.
            s.push_str(&format!(
                "<div class=\"curl\"><pre>curl -X {} {}{}</pre><button onclick=\"fluxCopy(this)\">copy</button></div>\n",
                verb.to_uppercase(),
                html_escape(base),
                html_escape(path),
            ));
            if op.get("requestBody").is_some() {
                let body_ref = op["requestBody"]["content"]["application/json"]["schema"]
                    .get("$ref")
                    .and_then(|v| v.as_str())
                    .unwrap_or("(inline)");
                s.push_str(&format!(
                    "<p class=\"body\">Request body: <code>{}</code></p>\n",
                    html_escape(body_ref),
                ));
            }
            s.push_str("</section>\n");
        }
    }
}

fn render_events_section(s: &mut String, events: &[EventVariant]) {
    s.push_str("<h2>Live events</h2>\n");
    if events.is_empty() {
        s.push_str("<p class=\"empty\">No events defined.</p>\n");
        return;
    }
    for v in events {
        s.push_str("<section class=\"event\">\n");
        s.push_str(&format!(
            "<h3><code>type: \"{}\"</code></h3>\n",
            html_escape(&v.tag)
        ));
        if v.fields.is_empty() {
            s.push_str("<p class=\"empty\">No fields.</p>\n");
        } else {
            s.push_str("<table class=\"fields\"><thead><tr><th>name</th><th>type</th></tr></thead><tbody>\n");
            for (name, ty) in &v.fields {
                s.push_str(&format!(
                    "<tr><td><code>{}</code></td><td><code>{}</code></td></tr>\n",
                    html_escape(name),
                    html_escape(ty),
                ));
            }
            s.push_str("</tbody></table>\n");
        }
        s.push_str("</section>\n");
    }
}

fn render_embedded_json(s: &mut String, openapi: &Value, events: &[EventVariant]) {
    let openapi_str = serde_json::to_string(openapi).unwrap_or_default();
    let events_str = serde_json::to_string(events).unwrap_or_default();
    s.push_str("<details><summary>Raw OpenAPI JSON</summary>\n");
    s.push_str(&format!(
        "<pre id=\"openapi-json\">{}</pre>\n",
        html_escape(&openapi_str)
    ));
    s.push_str("</details>\n");
    s.push_str("<details><summary>Raw events JSON</summary>\n");
    s.push_str(&format!(
        "<pre id=\"events-json\">{}</pre>\n",
        html_escape(&events_str)
    ));
    s.push_str("</details>\n");
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::event_types::flux_ue_bridge_events;
    use crate::openapi::generate_openapi;

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }

    fn fixture() -> (Value, Vec<EventVariant>) {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let doc = generate_openapi("flux-ue-bridge", "0.17.0", &eps);
        let events = flux_ue_bridge_events();
        (doc, events)
    }

    #[test]
    fn docsite_starts_with_doctype_and_contains_title() {
        let (doc, ev) = fixture();
        let html = render_docsite("flux-ue-bridge", &doc, &ev);
        assert!(html.starts_with("<!doctype html>"));
        assert!(html.contains("<title>flux-ue-bridge — API docs</title>"));
        assert!(html.contains("<h1>flux-ue-bridge</h1>"));
    }

    #[test]
    fn docsite_has_live_filter_and_copy_curl() {
        let (doc, ev) = fixture();
        let html = render_docsite("ue", &doc, &ev);
        // live filter input + its handler
        assert!(html.contains("class=\"ep-filter\""), "missing filter input");
        assert!(html.contains("function fluxFilter"), "missing filter script");
        // copy-as-curl affordance per endpoint
        assert!(html.contains("<div class=\"curl\">"), "missing curl block");
        assert!(html.contains("curl -X "), "missing curl command");
        assert!(html.contains("function fluxCopy"), "missing copy script");
    }

    #[test]
    fn docsite_lists_every_endpoint_with_verb_chip() {
        let (doc, ev) = fixture();
        let html = render_docsite("ue", &doc, &ev);
        for (path, verb) in [
            ("/v1/webhook", "POST"),
            ("/v1/workspace", "GET"),
            ("/v1/events", "GET"),
        ] {
            assert!(html.contains(&format!("<code>{path}</code>")), "missing path {path}");
            assert!(html.contains(verb), "missing verb {verb} in chip");
        }
    }

    #[test]
    fn docsite_lists_every_event_variant() {
        let (doc, ev) = fixture();
        let html = render_docsite("ue", &doc, &ev);
        for tag in ["iterate_complete", "test_complete", "build_failed", "hello", "heartbeat"] {
            // Quotes inside <code> are text content — no entity escaping needed
            // and the renderer emits them literally.
            assert!(
                html.contains(&format!("type: \"{tag}\"")),
                "missing event tag {tag} in docsite"
            );
        }
    }

    #[test]
    fn docsite_embeds_raw_openapi_and_events_json() {
        let (doc, ev) = fixture();
        let html = render_docsite("ue", &doc, &ev);
        assert!(html.contains("id=\"openapi-json\""));
        assert!(html.contains("id=\"events-json\""));
        // tag string survives the round trip
        assert!(html.contains("iterate_complete"));
    }

    #[test]
    fn empty_inputs_render_clean_empty_state() {
        let html = render_docsite("Nothing", &serde_json::json!({}), &[]);
        assert!(html.contains("No paths defined."));
        assert!(html.contains("No events defined."));
    }

    #[test]
    fn html_escapes_user_strings() {
        let evil = vec![EventVariant {
            tag: "<script>alert(1)</script>".into(),
            fields: vec![("nm".into(), "string".into())],
        }];
        let html = render_docsite("x", &serde_json::json!({}), &evil);
        assert!(!html.contains("<script>alert(1)</script>"));
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
    }
}
