// Event-surface codegen — the "moat" axis.
//
// v0.11.x: TypeScript-only generator (hand-curated from the flux-ue-bridge
//          `Event` enum).
// v0.16-A/B (rocky 2026-05-29): added Python (TypedDict + Literal + Union),
//          Go (interface + tagged unmarshal), Rust (serde tagged enum), and
//          Kotlin (sealed class + @SerialName) generators. 5 languages from
//          one `Vec<EventVariant>` source — this is what flux-api ships that
//          Stainless doesn't: typed live-event clients from one Rust truth.
//
// Field types are still strings ("string", "number", "boolean",
// "string | null") inherited from the TS-first design. Each generator maps
// these to its language's natural equivalent via `lang_*_type`. Mixed
// numeric/integer nuance is deferred to v0.16.x — the current map widens
// everything to the language's default real/int.

use crate::casing::pascal_case;
use serde::{Deserialize, Serialize};

/// One variant of a Flux event enum. `tag` is the serde `#[serde(tag)]`
/// rename string ("iterate_complete"); each field is (name, TS-style type).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventVariant {
    pub tag: String,
    pub fields: Vec<(String, String)>,
}

/// flux-ue-bridge's `Event` enum, lowered. Source of truth for every
/// language generator below.
pub fn flux_ue_bridge_events() -> Vec<EventVariant> {
    vec![
        EventVariant {
            tag: "iterate_complete".into(),
            fields: vec![
                ("package".into(), "string".into()),
                ("success".into(), "boolean".into()),
                ("compile_ms".into(), "number".into()),
                ("cache_rate".into(), "number".into()),
            ],
        },
        EventVariant {
            tag: "test_complete".into(),
            fields: vec![
                ("package".into(), "string".into()),
                ("passed".into(), "number".into()),
                ("failed".into(), "number".into()),
                ("elapsed_ms".into(), "number".into()),
            ],
        },
        EventVariant {
            tag: "build_failed".into(),
            fields: vec![
                ("package".into(), "string".into()),
                ("compile_ms".into(), "number".into()),
                ("error_excerpt".into(), "string | null".into()),
            ],
        },
        EventVariant {
            tag: "hello".into(),
            fields: vec![
                ("bridge_version".into(), "string".into()),
                ("workspace_path".into(), "string".into()),
            ],
        },
        EventVariant {
            tag: "heartbeat".into(),
            fields: vec![("now_unix".into(), "number".into())],
        },
    ]
}

// ---------- TypeScript ----------------------------------------------------

pub fn generate_ts_event_types(union_name: &str, variants: &[EventVariant]) -> String {
    let mut s = String::from("// Auto-generated by Flux API Builder — Event Surface\n\n");
    let mut variant_names = Vec::with_capacity(variants.len());
    for v in variants {
        let iface = format!("{}_{}", union_name, pascal_case(&v.tag.replace('-', "_")));
        variant_names.push(iface.clone());
        s.push_str(&format!(
            "export interface {} {{\n  type: \"{}\";\n",
            iface, v.tag
        ));
        for (name, ty) in &v.fields {
            s.push_str(&format!("  {}: {};\n", name, ty));
        }
        s.push_str("}\n\n");
    }
    s.push_str(&format!(
        "export type {} =\n  | {};\n",
        union_name,
        variant_names.join("\n  | ")
    ));
    s
}

// ---------- Python (TypedDict + Literal + Union) --------------------------

fn lang_py_type(ts: &str) -> String {
    match ts.trim() {
        "string" => "str".into(),
        "number" => "float".into(),
        "boolean" => "bool".into(),
        "string | null" => "Optional[str]".into(),
        "number | null" => "Optional[float]".into(),
        "boolean | null" => "Optional[bool]".into(),
        other => other.into(),
    }
}

pub fn generate_python_event_types(union_name: &str, variants: &[EventVariant]) -> String {
    let mut s = String::from("# Auto-generated by Flux API Builder — Event Surface\n");
    s.push_str("from typing import Literal, Optional, TypedDict, Union\n\n");
    let mut variant_names = Vec::with_capacity(variants.len());
    for v in variants {
        let class = format!("{}_{}", union_name, pascal_case(&v.tag.replace('-', "_")));
        variant_names.push(class.clone());
        s.push_str(&format!("class {class}(TypedDict):\n"));
        s.push_str(&format!("    type: Literal[\"{}\"]\n", v.tag));
        for (name, ty) in &v.fields {
            s.push_str(&format!("    {}: {}\n", name, lang_py_type(ty)));
        }
        s.push('\n');
    }
    s.push_str(&format!(
        "{union_name} = Union[{}]\n",
        variant_names.join(", ")
    ));
    s
}

// ---------- Go (interface + tagged unmarshal) ----------------------------

fn lang_go_type(ts: &str) -> String {
    match ts.trim() {
        "string" => "string".into(),
        "number" => "float64".into(),
        "boolean" => "bool".into(),
        "string | null" => "*string".into(),
        "number | null" => "*float64".into(),
        "boolean | null" => "*bool".into(),
        other => other.into(),
    }
}

/// Go doesn't have native discriminated unions. We emit:
///   * one struct per variant with `Type string` + the variant's fields
///   * a marker interface `BridgeEvent`
///   * a `UnmarshalBridgeEvent(b []byte) (BridgeEvent, error)` helper that
///     peeks `"type"` and dispatches to the right struct
pub fn generate_go_event_types(
    union_name: &str,
    variants: &[EventVariant],
    package_name: &str,
) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Event Surface\n");
    s.push_str(&format!("package {package_name}\n\n"));
    s.push_str("import (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n\n");
    s.push_str(&format!(
        "// {union_name} is the marker interface every event variant implements.\n\
         type {union_name} interface {{ is{union_name}() }}\n\n"
    ));
    for v in variants {
        let st = format!("{}_{}", union_name, pascal_case(&v.tag.replace('-', "_")));
        s.push_str(&format!("type {st} struct {{\n"));
        s.push_str(&format!(
            "\tType string `json:\"type\"` // = \"{}\"\n",
            v.tag
        ));
        for (name, ty) in &v.fields {
            let go_name = pascal_case(&name.replace('-', "_"));
            s.push_str(&format!(
                "\t{go_name} {go_ty} `json:\"{name}\"`\n",
                go_name = go_name,
                go_ty = lang_go_type(ty),
                name = name,
            ));
        }
        s.push_str("}\n\n");
        s.push_str(&format!("func ({st}) is{union_name}() {{}}\n\n"));
    }
    s.push_str(&format!(
        "// Unmarshal{union_name} peeks the `type` discriminator and decodes into the right variant.\n\
         func Unmarshal{union_name}(b []byte) ({union_name}, error) {{\n\
         \tvar tag struct {{ Type string `json:\"type\"` }}\n\
         \tif err := json.Unmarshal(b, &tag); err != nil {{ return nil, err }}\n\
         \tswitch tag.Type {{\n"
    ));
    for v in variants {
        let st = format!("{}_{}", union_name, pascal_case(&v.tag.replace('-', "_")));
        s.push_str(&format!(
            "\tcase \"{}\":\n\t\tvar out {st}\n\t\tif err := json.Unmarshal(b, &out); err != nil {{ return nil, err }}\n\t\treturn out, nil\n",
            v.tag
        ));
    }
    s.push_str("\tdefault:\n\t\treturn nil, fmt.Errorf(\"unknown event type %q\", tag.Type)\n");
    s.push_str("\t}\n}\n");
    s
}

// ---------- Rust (serde tagged enum) -------------------------------------

fn lang_rust_type(ts: &str) -> String {
    match ts.trim() {
        "string" => "String".into(),
        "number" => "f64".into(),
        "boolean" => "bool".into(),
        "string | null" => "Option<String>".into(),
        "number | null" => "Option<f64>".into(),
        "boolean | null" => "Option<bool>".into(),
        other => other.into(),
    }
}

/// Rust's `#[serde(tag = "type")]` enum maps the same JSON envelope as TS.
/// The emitted enum implements `Serialize + Deserialize` directly.
pub fn generate_rust_event_types(union_name: &str, variants: &[EventVariant]) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Event Surface\n\n");
    s.push_str("use serde::{Deserialize, Serialize};\n\n");
    s.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    s.push_str("#[serde(tag = \"type\", rename_all = \"snake_case\")]\n");
    s.push_str(&format!("pub enum {union_name} {{\n"));
    for v in variants {
        let var = pascal_case(&v.tag.replace('-', "_"));
        if v.fields.is_empty() {
            s.push_str(&format!("\t#[serde(rename = \"{}\")]\n\t{var},\n", v.tag));
        } else {
            s.push_str(&format!("\t#[serde(rename = \"{}\")]\n\t{var} {{\n", v.tag));
            for (name, ty) in &v.fields {
                s.push_str(&format!("\t\t{}: {},\n", name, lang_rust_type(ty)));
            }
            s.push_str("\t},\n");
        }
    }
    s.push_str("}\n");
    s
}

// ---------- Kotlin (sealed class + @SerialName) --------------------------

fn lang_kotlin_type(ts: &str) -> String {
    match ts.trim() {
        "string" => "String".into(),
        "number" => "Double".into(),
        "boolean" => "Boolean".into(),
        "string | null" => "String?".into(),
        "number | null" => "Double?".into(),
        "boolean | null" => "Boolean?".into(),
        other => other.into(),
    }
}

/// Kotlin sealed class + kotlinx.serialization. Each variant is an inner
/// data class with `@SerialName("<tag>")`.
pub fn generate_kotlin_event_types(
    union_name: &str,
    variants: &[EventVariant],
    package_name: &str,
) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Event Surface\n");
    s.push_str(&format!("package {package_name}\n\n"));
    s.push_str("import kotlinx.serialization.SerialName\n");
    s.push_str("import kotlinx.serialization.Serializable\n");
    s.push_str("import kotlinx.serialization.json.JsonClassDiscriminator\n");
    s.push_str("import kotlinx.serialization.ExperimentalSerializationApi\n\n");
    s.push_str("@OptIn(ExperimentalSerializationApi::class)\n");
    s.push_str("@Serializable\n");
    s.push_str("@JsonClassDiscriminator(\"type\")\n");
    s.push_str(&format!("sealed class {union_name} {{\n"));
    for v in variants {
        let var = pascal_case(&v.tag.replace('-', "_"));
        s.push_str("\t@Serializable\n");
        s.push_str(&format!("\t@SerialName(\"{}\")\n", v.tag));
        if v.fields.is_empty() {
            s.push_str(&format!("\tobject {var} : {union_name}()\n\n"));
        } else {
            s.push_str(&format!("\tdata class {var}(\n"));
            for (name, ty) in &v.fields {
                // `package` is a Kotlin keyword; backtick-escape the field
                // name so the generated source compiles.
                let name_out = if name == "package" || name == "object" || name == "class" {
                    format!("`{name}`")
                } else {
                    name.clone()
                };
                s.push_str(&format!(
                    "\t\tval {name_out}: {ty},\n",
                    ty = lang_kotlin_type(ty)
                ));
            }
            s.push_str(&format!("\t) : {union_name}()\n\n"));
        }
    }
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Vec<EventVariant> {
        flux_ue_bridge_events()
    }

    // --- TS preserved from v0.11.x ---

    #[test]
    fn ts_emits_discriminated_union() {
        let ts = generate_ts_event_types("BridgeEvent", &sample());
        assert!(ts.contains("export interface BridgeEvent_IterateComplete"));
        assert!(ts.contains("type: \"iterate_complete\""));
        assert!(ts.contains("error_excerpt: string | null;"));
        assert!(ts.contains("export type BridgeEvent ="));
        assert!(ts.contains("| BridgeEvent_Heartbeat"));
    }

    // --- Python ---

    #[test]
    fn python_emits_typeddict_per_variant() {
        let py = generate_python_event_types("BridgeEvent", &sample());
        assert!(py.contains("class BridgeEvent_IterateComplete(TypedDict):"));
        assert!(py.contains("type: Literal[\"iterate_complete\"]"));
        assert!(py.contains("package: str"));
        assert!(py.contains("success: bool"));
        assert!(py.contains("compile_ms: float"));
        assert!(py.contains("error_excerpt: Optional[str]"));
        assert!(py.contains("BridgeEvent = Union["));
        assert!(py.contains("BridgeEvent_Heartbeat"));
    }

    #[test]
    fn python_imports_typing_aliases() {
        let py = generate_python_event_types("X", &sample());
        assert!(py.contains("from typing import Literal, Optional, TypedDict, Union"));
    }

    // --- Go ---

    #[test]
    fn go_emits_interface_and_structs() {
        let go = generate_go_event_types("BridgeEvent", &sample(), "events");
        assert!(go.contains("package events"));
        assert!(go.contains("type BridgeEvent interface { isBridgeEvent() }"));
        assert!(go.contains("type BridgeEvent_IterateComplete struct"));
        assert!(go.contains("`json:\"package\"`"));
        assert!(go.contains("`json:\"success\"`"));
        assert!(go.contains("func (BridgeEvent_Heartbeat) isBridgeEvent() {}"));
    }

    #[test]
    fn go_emits_unmarshal_dispatch() {
        let go = generate_go_event_types("BridgeEvent", &sample(), "events");
        assert!(go.contains("func UnmarshalBridgeEvent(b []byte) (BridgeEvent, error)"));
        assert!(go.contains("case \"iterate_complete\":"));
        assert!(go.contains("case \"build_failed\":"));
        assert!(go.contains("default:"));
    }

    #[test]
    fn go_maps_nullable_to_pointer() {
        let go = generate_go_event_types("BridgeEvent", &sample(), "events");
        // error_excerpt: "string | null" → Go *string
        assert!(go.contains("*string"));
    }

    // --- Rust ---

    #[test]
    fn rust_emits_serde_tagged_enum() {
        let rs = generate_rust_event_types("BridgeEvent", &sample());
        assert!(rs.contains("use serde::{Deserialize, Serialize};"));
        assert!(rs.contains("#[serde(tag = \"type\""));
        assert!(rs.contains("pub enum BridgeEvent"));
        assert!(rs.contains("#[serde(rename = \"iterate_complete\")]"));
        assert!(rs.contains("package: String,"));
        assert!(rs.contains("success: bool,"));
        assert!(rs.contains("compile_ms: f64,"));
        assert!(rs.contains("error_excerpt: Option<String>,"));
    }

    // --- Kotlin ---

    #[test]
    fn kotlin_emits_sealed_class_with_serialnames() {
        let kt = generate_kotlin_event_types("BridgeEvent", &sample(), "io.flux.events");
        assert!(kt.contains("package io.flux.events"));
        assert!(kt.contains("sealed class BridgeEvent"));
        assert!(kt.contains("@SerialName(\"iterate_complete\")"));
        assert!(kt.contains("data class IterateComplete("));
        assert!(kt.contains("val success: Boolean"));
        assert!(kt.contains("val compile_ms: Double"));
        assert!(kt.contains("val error_excerpt: String?"));
        // `package` is a reserved word — must be backtick-escaped
        assert!(kt.contains("val `package`: String"));
        assert!(kt.contains("@JsonClassDiscriminator(\"type\")"));
    }

    // --- Cross-lang sanity ---

    #[test]
    fn all_languages_emit_every_variant() {
        let variants = sample();
        let ts = generate_ts_event_types("E", &variants);
        let py = generate_python_event_types("E", &variants);
        let go = generate_go_event_types("E", &variants, "events");
        let rs = generate_rust_event_types("E", &variants);
        let kt = generate_kotlin_event_types("E", &variants, "io.flux.e");
        for tag in ["iterate_complete", "test_complete", "build_failed", "hello", "heartbeat"] {
            for (lang, src) in [("ts", &ts), ("py", &py), ("go", &go), ("rs", &rs), ("kt", &kt)] {
                assert!(
                    src.contains(tag),
                    "{lang} output missing tag {tag}\n--- output ---\n{src}"
                );
            }
        }
    }
}
