// Rust client SDK generator.
//
// v0.14-B: reqwest-based async clients; one struct per tag, methods return
// `Result<reqwest::Response, reqwest::Error>`.
// v0.15-C (rocky 2026-05-29): when any endpoint in a tag carries an active
// `MiddlewareSpec` with bearer auth, add a `token: Option<String>` field and
// inject `.bearer_auth()` per call.

use crate::casing::{pascal_case, snake_case};
use crate::middleware::AuthKind;
use crate::schema::ApiEndpoint;

pub fn generate_rust_client_sdk(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Rust client SDK (v0.14)\n\n");

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = format!("{}Client", pascal_case(&tag.replace('-', "_")));
        let bearer = eps.iter().any(|e| {
            e.middleware
                .as_ref()
                .map(|m| matches!(m.auth, AuthKind::Bearer))
                .unwrap_or(false)
        });

        // Struct.
        s.push_str(&format!("pub struct {cn} {{\n"));
        s.push_str("\tpub base_url: String,\n");
        s.push_str("\tpub http: reqwest::Client,\n");
        if bearer {
            s.push_str("\tpub token: Option<String>,\n");
        }
        s.push_str("}\n\n");

        // Constructor.
        s.push_str(&format!("impl {cn} {{\n"));
        if bearer {
            s.push_str(&format!(
                "\tpub fn new(base_url: impl Into<String>, token: Option<String>) -> Self {{\n\
                 \t\tlet base_url = base_url.into();\n\
                 \t\tlet base_url = if base_url.is_empty() {{ \"{base_url}\".into() }} else {{ base_url }};\n\
                 \t\tSelf {{ base_url, http: reqwest::Client::new(), token }}\n\
                 \t}}\n\n"
            ));
        } else {
            s.push_str(&format!(
                "\tpub fn new(base_url: impl Into<String>) -> Self {{\n\
                 \t\tlet base_url = base_url.into();\n\
                 \t\tlet base_url = if base_url.is_empty() {{ \"{base_url}\".into() }} else {{ base_url }};\n\
                 \t\tSelf {{ base_url, http: reqwest::Client::new() }}\n\
                 \t}}\n\n"
            ));
        }

        for ep in &eps {
            let method_name = snake_case(&ep.operation_id);
            let verb = format!("{:?}", ep.method).to_lowercase();
            s.push_str(&format!(
                "\t/// {summary}\n\
                 \tpub async fn {method_name}(&self) -> Result<reqwest::Response, reqwest::Error> {{\n\
                 \t\tlet url = self.base_url.clone() + \"{path}\";\n",
                summary = ep.summary,
                method_name = method_name,
                path = ep.path,
            ));
            if bearer {
                s.push_str(&format!(
                    "\t\tlet mut req = self.http.{verb}(url);\n\
                     \t\tif let Some(t) = &self.token {{ req = req.bearer_auth(t); }}\n\
                     \t\treq.send().await\n"
                ));
            } else {
                s.push_str(&format!("\t\tself.http.{verb}(url).send().await\n"));
            }
            s.push_str("\t}\n\n");
        }

        s.push_str("}\n\n");
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::MiddlewareSpec;
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: "/me".into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn rust_sdk_emits_struct_per_tag() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_rust_client_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("pub struct FluxUeBridgeClient"));
        assert!(sdk.contains("pub base_url: String"));
        assert!(sdk.contains("pub http: reqwest::Client"));
        assert!(!sdk.contains("pub token:"));
    }

    #[test]
    fn rust_sdk_methods_use_lowercase_verbs() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_rust_client_sdk(&eps, "http://api.example/");
        assert!(sdk.contains("pub async fn wickes_cms_1(&self)"));
        assert!(sdk.contains(".post(url)"));
        assert!(sdk.contains(".get(url)"));
        assert!(sdk.contains("Result<reqwest::Response, reqwest::Error>"));
    }

    #[test]
    fn rust_sdk_default_base_url_fallback() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_rust_client_sdk(&eps, "https://example.test");
        assert!(sdk.contains("if base_url.is_empty() { \"https://example.test\".into() }"));
    }

    #[test]
    fn rust_sdk_composes_url_via_concat() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_rust_client_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("self.base_url.clone() + \"/v1/workspace\""));
        assert!(sdk.contains("self.base_url.clone() + \"/v1/webhook\""));
    }

    #[test]
    fn rust_sdk_handles_path_params_without_format_collision() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_rust_client_sdk(&eps, "http://localhost:8080");
        assert!(sdk.contains("self.base_url.clone() + \"/api/pages/{id}\""));
    }

    #[test]
    fn rust_sdk_bearer_middleware_adds_token_field_and_bearer_auth() {
        let eps = vec![ep_with_mw(MiddlewareSpec::bearer_auth())];
        let sdk = generate_rust_client_sdk(&eps, "https://api");
        assert!(sdk.contains("pub token: Option<String>"));
        assert!(sdk.contains("pub fn new(base_url: impl Into<String>, token: Option<String>)"));
        assert!(sdk.contains("req = req.bearer_auth(t)"));
    }
}
