// Python REST SDK generator.
//
// v0.14: bare httpx.
// v0.15-B (rocky 2026-05-29): when an endpoint carries an active
// MiddlewareSpec we emit a richer client: optional `token=` constructor arg
// for bearer auth + an internal `_request` helper that injects the
// `Authorization` header and retries with exp-backoff on the configured
// status codes. Endpoints without active middleware keep the v0.14 emission.

use crate::casing::{pascal_case, snake_case};
use crate::middleware::{AuthKind, MiddlewareSpec};
use crate::schema::ApiEndpoint;

pub fn generate_python_sdk(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    let mut s = String::from("# Auto-generated by Flux API Builder — Phase 3a\nimport httpx\n");
    // `time` only used by the retry path; emit unconditionally so the file
    // parses cleanly when toggled in/out across regenerations.
    s.push_str("import time\n\n");

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = pascal_case(&tag.replace('-', "_"));
        let effective = eps
            .iter()
            .find_map(|e| e.middleware.as_ref())
            .filter(|m| m.is_active())
            .cloned();

        if let Some(mw) = effective {
            emit_middleware_client(&mut s, &cn, base_url, &eps, &mw);
        } else {
            emit_basic_client(&mut s, &cn, base_url, &eps);
        }
    }
    s
}

fn emit_basic_client(s: &mut String, cn: &str, base_url: &str, eps: &[&ApiEndpoint]) {
    s.push_str(&format!(
        "class {cn}Client:\n    def __init__(self, base_url: str = \"{base_url}\"):\n        self.c = httpx.Client(base_url=base_url)\n\n"
    ));
    for ep in eps {
        s.push_str(&format!(
            "    def {}(self):\n        return self.c.{}(\"{}\").json()\n\n",
            snake_case(&ep.operation_id),
            format!("{:?}", ep.method).to_lowercase(),
            ep.path
        ));
    }
}

fn emit_middleware_client(
    s: &mut String,
    cn: &str,
    base_url: &str,
    eps: &[&ApiEndpoint],
    mw: &MiddlewareSpec,
) {
    let bearer = matches!(mw.auth, AuthKind::Bearer);
    let retry = &mw.retry;

    s.push_str(&format!("class {cn}Client:\n"));
    if bearer {
        s.push_str(&format!(
            "    def __init__(self, base_url: str = \"{base_url}\", token: str | None = None):\n        self.c = httpx.Client(base_url=base_url)\n        self.token = token\n\n"
        ));
    } else {
        s.push_str(&format!(
            "    def __init__(self, base_url: str = \"{base_url}\"):\n        self.c = httpx.Client(base_url=base_url)\n\n"
        ));
    }

    s.push_str("    def _request(self, method: str, path: str):\n");
    s.push_str("        headers = {}\n");
    if bearer {
        s.push_str("        if self.token:\n            headers[\"Authorization\"] = f\"Bearer {self.token}\"\n");
    }
    if retry.is_active() {
        let max_attempts = retry.max_attempts;
        let init_ms = retry.initial_backoff_ms;
        let max_ms = retry.max_backoff_ms;
        let retry_list = retry
            .retry_on_status
            .iter()
            .map(|c| c.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!(
            "        retry_on = {{{retry_list}}}\n\
             \tattempt = 0\n\
             \twhile True:\n\
             \t    r = self.c.request(method, path, headers=headers)\n\
             \t    if r.status_code not in retry_on or attempt >= {max_attempts} - 1:\n\
             \t        return r\n\
             \t    backoff = min({init_ms} * (2 ** attempt), {max_ms}) / 1000.0\n\
             \t    time.sleep(backoff)\n\
             \t    attempt += 1\n"
        ).replace('\t', "        "));
    } else {
        s.push_str("        return self.c.request(method, path, headers=headers)\n");
    }
    s.push_str("\n");

    for ep in eps {
        let mn = snake_case(&ep.operation_id);
        let verb = format!("{:?}", ep.method).to_uppercase();
        s.push_str(&format!(
            "    def {mn}(self):\n        return self._request(\"{verb}\", \"{}\").json()\n\n",
            ep.path
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::{MiddlewareSpec, RetryPolicy};
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(path: &str, mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: path.into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn no_middleware_keeps_v0_14_emission() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_python_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("class FluxUeBridgeClient:"));
        assert!(!sdk.contains("_request"));
        assert!(!sdk.contains("Authorization"));
    }

    #[test]
    fn bearer_auth_emits_token_arg_and_header() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("token: str | None = None"));
        assert!(sdk.contains("Authorization"));
        assert!(sdk.contains("f\"Bearer {self.token}\""));
    }

    #[test]
    fn retry_policy_emits_loop_and_sleep() {
        let eps = vec![ep_with_mw(
            "/poll",
            MiddlewareSpec::default().with_retry(RetryPolicy::standard()),
        )];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("retry_on = {"));
        assert!(sdk.contains("429"));
        assert!(sdk.contains("503"));
        assert!(sdk.contains("time.sleep"));
        assert!(sdk.contains("2 ** attempt"));
    }

    #[test]
    fn middleware_methods_route_through_request_helper() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("self._request"));
        assert!(!sdk.contains("self.c.get(\"/me\")"));
    }
}
