// Kotlin SDK generator.
//
// v0.14-C: coroutine-based OkHttp clients.
// v0.15-C (rocky 2026-05-29): when any endpoint in a tag carries an active
// `MiddlewareSpec` with bearer auth, add a `token: String? = null`
// constructor arg and call `.addHeader("Authorization", "Bearer $token")`
// before building each request.

use crate::casing::{camel_case, pascal_case};
use crate::codegen::{
    as_object, body_type_name, has_body, path_params, prim_of, query_params, render_path,
    SchemaDefs,
};
use crate::middleware::AuthKind;
use crate::schema::{ApiEndpoint, ApiSchema, HttpMethod, PrimType};
use std::collections::BTreeMap;

fn kt_type(schema: &ApiSchema) -> &'static str {
    match prim_of(schema) {
        Some(PrimType::Integer) => "Long",
        Some(PrimType::Number) => "Double",
        Some(PrimType::Boolean) => "Boolean",
        Some(PrimType::String) | None => "String",
    }
}

/// Property type: refs → the data-class name, arrays → `List<..>`, nullables →
/// `..?`, inline objects/oneOf → `kotlinx.serialization.json.JsonElement`.
fn kt_type_ref(schema: &ApiSchema) -> String {
    match schema {
        ApiSchema::Primitive { .. } | ApiSchema::Enum { .. } => kt_type(schema).to_string(),
        ApiSchema::Ref { name } => pascal_case(&name.replace('-', "_")),
        ApiSchema::Array { items } => format!("List<{}>", kt_type_ref(items)),
        ApiSchema::Nullable { inner } => format!("{}?", kt_type_ref(inner)),
        ApiSchema::Object { .. } | ApiSchema::OneOf { .. } => {
            "kotlinx.serialization.json.JsonElement".into()
        }
    }
}

/// Emit a `@Serializable data class <Name>(...)` per object schema.
fn emit_kt_types(s: &mut String, defs: &SchemaDefs) {
    for (name, schema) in defs {
        let tn = pascal_case(&name.replace('-', "_"));
        match as_object(schema) {
            Some((props, required)) => {
                s.push_str("@Serializable\n");
                s.push_str(&format!("data class {tn}(\n"));
                let fields: Vec<String> = props
                    .iter()
                    .map(|(field, fschema)| {
                        let ty = kt_type_ref(fschema);
                        if required.contains(field) {
                            format!("\tval {field}: {ty}")
                        } else {
                            format!("\tval {field}: {ty}? = null")
                        }
                    })
                    .collect();
                s.push_str(&fields.join(",\n"));
                s.push_str("\n)\n\n");
            }
            None => {
                s.push_str(&format!("typealias {tn} = {}\n\n", kt_type_ref(schema)));
            }
        }
    }
}

/// Back-compat entry point: no registry → raw `String?` bodies, no data classes.
pub fn generate_kotlin_sdk(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    package_name: &str,
) -> String {
    generate_kotlin_sdk_with_types(endpoints, base_url, package_name, &BTreeMap::new())
}

/// Emit the Kotlin SDK with a `@Serializable data class` per registry schema
/// and a typed `body: <Name>?` arg (serialized via `Json.encodeToString`).
pub fn generate_kotlin_sdk_with_types(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    package_name: &str,
    defs: &SchemaDefs,
) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Kotlin SDK (v0.14)\n");
    s.push_str(&format!("package {package_name}\n\n"));
    s.push_str("import kotlinx.coroutines.Dispatchers\n");
    s.push_str("import kotlinx.coroutines.withContext\n");
    if !defs.is_empty() {
        s.push_str("import kotlinx.serialization.Serializable\n");
        s.push_str("import kotlinx.serialization.encodeToString\n");
        s.push_str("import kotlinx.serialization.json.Json\n");
    }
    s.push_str("import okhttp3.OkHttpClient\n");
    s.push_str("import okhttp3.Request\n");
    s.push_str("import okhttp3.RequestBody.Companion.toRequestBody\n");
    s.push_str("import okhttp3.Response\n\n");

    emit_kt_types(&mut s, defs);

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = format!("{}Client", pascal_case(&tag.replace('-', "_")));
        let bearer = eps.iter().any(|e| {
            e.middleware
                .as_ref()
                .map(|m| matches!(m.auth, AuthKind::Bearer))
                .unwrap_or(false)
        });

        // Class header.
        s.push_str(&format!("class {cn}(\n"));
        s.push_str(&format!(
            "\tprivate val baseUrl: String = \"{base_url}\",\n"
        ));
        s.push_str("\tprivate val client: OkHttpClient = OkHttpClient(),\n");
        if bearer {
            s.push_str("\tprivate val token: String? = null,\n");
        }
        s.push_str(") {\n\n");

        for ep in &eps {
            let method_name = camel_case(&ep.operation_id);
            let pps = path_params(ep);
            let qps = query_params(ep);
            let body = has_body(ep);

            // A named body becomes a typed data-class arg (serialized below);
            // an unnamed/inline body stays a raw JSON `String?`.
            let body_named = body_type_name(ep.request_body.as_ref(), defs)
                .map(|n| pascal_case(&n.replace('-', "_")));

            // Signature: path params (typed) → body → query map.
            let mut sig: Vec<String> = vec![];
            for p in &pps {
                sig.push(format!("{}: {}", camel_case(&p.name), kt_type(&p.schema)));
            }
            if body {
                match &body_named {
                    Some(tn) => sig.push(format!("body: {tn}? = null")),
                    None => sig.push("body: String? = null".into()),
                }
            }
            if !qps.is_empty() {
                sig.push("query: Map<String, String> = emptyMap()".into());
            }

            let path_tmpl = render_path(&ep.path, |n| format!("${{{}}}", camel_case(n)));

            s.push_str(&format!(
                "\t/** {summary} */\n\tsuspend fun {method_name}({sig}): Response = withContext(Dispatchers.IO) {{\n",
                summary = ep.summary,
                sig = sig.join(", "),
            ));
            if body_named.is_some() {
                s.push_str("\t\tval bodyJson = body?.let { Json.encodeToString(it) } ?: \"\"\n");
            }

            // URL — inline for static/path-only routes (keeps `.url("$baseUrl..")`
            // stable); StringBuilder when query params need appending.
            if qps.is_empty() {
                s.push_str(&format!(
                    "\t\tval builder = Request.Builder()\n\t\t\t.url(\"$baseUrl{path_tmpl}\")\n"
                ));
            } else {
                s.push_str(&format!("\t\tval sb = StringBuilder(\"$baseUrl{path_tmpl}\")\n"));
                s.push_str(
                    "\t\tif (query.isNotEmpty()) {\n\
                     \t\t\tsb.append(\"?\")\n\
                     \t\t\tsb.append(query.entries.joinToString(\"&\") { \"${it.key}=${it.value}\" })\n\
                     \t\t}\n",
                );
                s.push_str("\t\tval builder = Request.Builder()\n\t\t\t.url(sb.toString())\n");
            }

            let body_expr = if body_named.is_some() {
                "bodyJson.toRequestBody()"
            } else if body {
                "(body ?: \"\").toRequestBody()"
            } else {
                "\"\".toRequestBody()"
            };
            match ep.method {
                HttpMethod::GET => s.push_str("\t\t\t.get()\n"),
                HttpMethod::POST => s.push_str(&format!("\t\t\t.post({body_expr})\n")),
                HttpMethod::PUT => s.push_str(&format!("\t\t\t.put({body_expr})\n")),
                HttpMethod::PATCH => s.push_str(&format!("\t\t\t.patch({body_expr})\n")),
                HttpMethod::DELETE => s.push_str("\t\t\t.delete()\n"),
            }
            if body {
                s.push_str("\t\tbuilder.addHeader(\"Content-Type\", \"application/json\")\n");
            }
            if bearer {
                s.push_str("\t\ttoken?.let { builder.addHeader(\"Authorization\", \"Bearer $it\") }\n");
            }
            s.push_str("\t\tval req = builder.build()\n");
            s.push_str("\t\tclient.newCall(req).execute()\n");
            s.push_str("\t}\n\n");
        }

        s.push_str("}\n\n");
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::MiddlewareSpec;
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: "/me".into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn kotlin_sdk_has_package_and_imports() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_kotlin_sdk(&eps, "http://localhost:9989", "io.flux.ue");
        assert!(sdk.contains("package io.flux.ue"));
        assert!(sdk.contains("import kotlinx.coroutines.Dispatchers"));
        assert!(sdk.contains("import okhttp3.OkHttpClient"));
        assert!(sdk.contains("import okhttp3.Response"));
    }

    #[test]
    fn kotlin_sdk_emits_class_per_tag() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_kotlin_sdk(&eps, "http://localhost:9989", "io.flux.ue");
        assert!(sdk.contains("class FluxUeBridgeClient("));
        assert!(sdk.contains("private val baseUrl: String = \"http://localhost:9989\""));
        assert!(sdk.contains("private val client: OkHttpClient = OkHttpClient()"));
        assert!(!sdk.contains("private val token"));
    }

    #[test]
    fn kotlin_sdk_methods_are_suspend_fun_with_dispatchers_io() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_kotlin_sdk(&eps, "http://localhost:9989", "io.flux.ue");
        // fluxUeBridge1 = GET /v1/workspace (no params) — stays zero-arg.
        assert!(sdk.contains("suspend fun fluxUeBridge1()"));
        assert!(sdk.contains("withContext(Dispatchers.IO)"));
        assert!(sdk.contains("client.newCall(req).execute()"));
    }

    #[test]
    fn kotlin_sdk_uses_correct_okhttp_verbs() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_kotlin_sdk(&eps, "https://example.test", "com.wickes.cms");
        assert!(sdk.contains(".get()"));
        // POST /api/pages carries a body now → body-bearing request.
        assert!(sdk.contains(".post((body ?: \"\").toRequestBody())"));
    }

    #[test]
    fn kotlin_sdk_substitutes_path_param_in_url() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_kotlin_sdk(&eps, "https://example.test", "com.wickes.cms");
        // GET /api/pages/{id} → wickesCms2(id: String) with $id interpolated.
        assert!(sdk.contains("wickesCms2(id: String)"), "missing id arg:\n{sdk}");
        assert!(sdk.contains(".url(\"$baseUrl/api/pages/${id}\")"), "id not interpolated:\n{sdk}");
        assert!(!sdk.contains("/api/pages/{id}"), "literal placeholder leaked:\n{sdk}");
    }

    #[test]
    fn kotlin_sdk_query_endpoint_appends_querystring() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_kotlin_sdk(&eps, "https://example.test", "com.wickes.cms");
        assert!(sdk.contains("query: Map<String, String> = emptyMap()"));
        assert!(sdk.contains("query.entries.joinToString"));
    }

    #[test]
    fn kotlin_sdk_body_endpoint_takes_body_arg_and_content_type() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_kotlin_sdk(&eps, "https://example.test", "com.wickes.cms");
        assert!(sdk.contains("body: String? = null"));
        assert!(sdk.contains("builder.addHeader(\"Content-Type\", \"application/json\")"));
    }

    #[test]
    fn kotlin_sdk_interpolates_base_url_in_path() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_kotlin_sdk(&eps, "http://localhost:9989", "io.flux.ue");
        assert!(sdk.contains(".url(\"$baseUrl/v1/workspace\")"));
        assert!(sdk.contains(".url(\"$baseUrl/v1/webhook\")"));
    }

    #[test]
    fn kotlin_sdk_bearer_middleware_adds_token_param_and_header() {
        let eps = vec![ep_with_mw(MiddlewareSpec::bearer_auth())];
        let sdk = generate_kotlin_sdk(&eps, "https://api", "io.demo");
        assert!(sdk.contains("private val token: String? = null"));
        assert!(sdk.contains("token?.let { builder.addHeader(\"Authorization\", \"Bearer $it\") }"));
    }

    #[test]
    fn with_types_emits_data_class_and_typed_body() {
        use crate::discover::discover_schemas;
        let g = ws(&["wickes-cms"]);
        let eps = discover_endpoints(&g);
        let sdk = generate_kotlin_sdk_with_types(&eps, "https://api", "com.wickes.cms", &discover_schemas(&g));
        assert!(sdk.contains("import kotlinx.serialization.Serializable"));
        assert!(sdk.contains("@Serializable"));
        assert!(sdk.contains("data class Page("), "missing data class:\n{sdk}");
        assert!(sdk.contains("val id: String"));
        assert!(sdk.contains("val status: String? = null"), "optional field:\n{sdk}");
        assert!(sdk.contains("body: Page? = null"), "body not typed Page:\n{sdk}");
        assert!(sdk.contains("val bodyJson = body?.let { Json.encodeToString(it) } ?: \"\""));
        assert!(sdk.contains("bodyJson.toRequestBody()"));
    }

    #[test]
    fn without_registry_keeps_raw_string_body() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_kotlin_sdk(&eps, "https://api", "com.wickes.cms");
        assert!(!sdk.contains("@Serializable"));
        assert!(sdk.contains("body: String? = null"));
    }
}
