// Rust client SDK generator.
//
// v0.14-B: reqwest-based async clients; one struct per tag, methods return
// `Result<reqwest::Response, reqwest::Error>`.
// v0.15-C (rocky 2026-05-29): when any endpoint in a tag carries an active
// `MiddlewareSpec` with bearer auth, add a `token: Option<String>` field and
// inject `.bearer_auth()` per call.

use crate::casing::{pascal_case, snake_case};
use crate::codegen::{
    as_object, body_type_name, has_body, path_params, prim_of, query_params, render_path,
    SchemaDefs,
};
use crate::middleware::AuthKind;
use crate::schema::{ApiEndpoint, ApiSchema, PrimType};
use std::collections::BTreeMap;

/// Borrowed primitive type for a path param.
fn rust_type(schema: &ApiSchema) -> &'static str {
    match prim_of(schema) {
        Some(PrimType::Integer) => "i64",
        Some(PrimType::Number) => "f64",
        Some(PrimType::Boolean) => "bool",
        Some(PrimType::String) | None => "&str",
    }
}

/// Owned type for a struct field: refs → the struct name, arrays → `Vec<..>`,
/// nullables → `Option<..>`, inline objects/oneOf → `serde_json::Value`.
fn rust_type_ref(schema: &ApiSchema) -> String {
    match schema {
        ApiSchema::Primitive { ty, .. } | ApiSchema::Enum { ty, .. } => match ty {
            PrimType::Integer => "i64".into(),
            PrimType::Number => "f64".into(),
            PrimType::Boolean => "bool".into(),
            PrimType::String => "String".into(),
        },
        ApiSchema::Ref { name } => pascal_case(&name.replace('-', "_")),
        ApiSchema::Array { items } => format!("Vec<{}>", rust_type_ref(items)),
        ApiSchema::Nullable { inner } => format!("Option<{}>", rust_type_ref(inner)),
        ApiSchema::Object { .. } | ApiSchema::OneOf { .. } => "serde_json::Value".into(),
    }
}

/// Emit a serde-deriving `pub struct` per object schema (type alias otherwise).
fn emit_rust_types(s: &mut String, defs: &SchemaDefs) {
    for (name, schema) in defs {
        let tn = pascal_case(&name.replace('-', "_"));
        match as_object(schema) {
            Some((props, required)) => {
                s.push_str("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n");
                s.push_str(&format!("pub struct {tn} {{\n"));
                for (field, fschema) in props {
                    let ty = rust_type_ref(fschema);
                    let ty = if required.contains(field) { ty } else { format!("Option<{ty}>") };
                    s.push_str(&format!("\tpub {field}: {ty},\n"));
                }
                s.push_str("}\n\n");
            }
            None => {
                s.push_str(&format!("pub type {tn} = {};\n\n", rust_type_ref(schema)));
            }
        }
    }
}

/// Back-compat entry point: no schema registry, so bodies are
/// `&serde_json::Value` and no named structs are emitted.
pub fn generate_rust_client_sdk(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    generate_rust_client_sdk_with_types(endpoints, base_url, &BTreeMap::new())
}

/// Emit the Rust client SDK with a serde-deriving `pub struct` per registry
/// schema, and type each `Ref`-bodied endpoint's `body: &<Name>`.
pub fn generate_rust_client_sdk_with_types(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    defs: &SchemaDefs,
) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Rust client SDK (v0.14)\n\n");
    emit_rust_types(&mut s, defs);

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = format!("{}Client", pascal_case(&tag.replace('-', "_")));
        let bearer = eps.iter().any(|e| {
            e.middleware
                .as_ref()
                .map(|m| matches!(m.auth, AuthKind::Bearer))
                .unwrap_or(false)
        });

        // Struct.
        s.push_str(&format!("pub struct {cn} {{\n"));
        s.push_str("\tpub base_url: String,\n");
        s.push_str("\tpub http: reqwest::Client,\n");
        if bearer {
            s.push_str("\tpub token: Option<String>,\n");
        }
        s.push_str("}\n\n");

        // Constructor.
        s.push_str(&format!("impl {cn} {{\n"));
        if bearer {
            s.push_str(&format!(
                "\tpub fn new(base_url: impl Into<String>, token: Option<String>) -> Self {{\n\
                 \t\tlet base_url = base_url.into();\n\
                 \t\tlet base_url = if base_url.is_empty() {{ \"{base_url}\".into() }} else {{ base_url }};\n\
                 \t\tSelf {{ base_url, http: reqwest::Client::new(), token }}\n\
                 \t}}\n\n"
            ));
        } else {
            s.push_str(&format!(
                "\tpub fn new(base_url: impl Into<String>) -> Self {{\n\
                 \t\tlet base_url = base_url.into();\n\
                 \t\tlet base_url = if base_url.is_empty() {{ \"{base_url}\".into() }} else {{ base_url }};\n\
                 \t\tSelf {{ base_url, http: reqwest::Client::new() }}\n\
                 \t}}\n\n"
            ));
        }

        for ep in &eps {
            let method_name = snake_case(&ep.operation_id);
            let verb = format!("{:?}", ep.method).to_lowercase();
            let pps = path_params(ep);
            let qps = query_params(ep);
            let body = has_body(ep);

            // Signature: path params (positional, typed) → `body: &serde_json::Value`
            // → `query: &[(&str, &str)]`.
            let mut sig: Vec<String> = vec!["&self".into()];
            for p in &pps {
                sig.push(format!("{}: {}", snake_case(&p.name), rust_type(&p.schema)));
            }
            if body {
                let bt = body_type_name(ep.request_body.as_ref(), defs)
                    .map(|n| format!("&{}", pascal_case(&n.replace('-', "_"))))
                    .unwrap_or_else(|| "&serde_json::Value".into());
                sig.push(format!("body: {bt}"));
            }
            if !qps.is_empty() {
                sig.push("query: &[(&str, &str)]".into());
            }

            s.push_str(&format!(
                "\t/// {summary}\n\
                 \tpub async fn {method_name}({sig}) -> Result<reqwest::Response, reqwest::Error> {{\n",
                summary = ep.summary,
                method_name = method_name,
                sig = sig.join(", "),
            ));

            // URL: literal concat for static paths; `format!` substitution when
            // there are path params (the `{}` positions match the arg order).
            if pps.is_empty() {
                s.push_str(&format!(
                    "\t\tlet url = self.base_url.clone() + \"{}\";\n",
                    ep.path
                ));
            } else {
                let fmt = render_path(&ep.path, |_| "{}".to_string());
                let args: Vec<String> =
                    pps.iter().map(|p| snake_case(&p.name)).collect();
                s.push_str(&format!(
                    "\t\tlet url = self.base_url.clone() + &format!(\"{fmt}\", {});\n",
                    args.join(", ")
                ));
            }

            let needs_mut = body || !qps.is_empty() || bearer;
            let binding = if needs_mut { "let mut req" } else { "let req" };
            s.push_str(&format!("\t\t{binding} = self.http.{verb}(url);\n"));
            if !qps.is_empty() {
                s.push_str("\t\treq = req.query(query);\n");
            }
            if body {
                s.push_str("\t\treq = req.json(body);\n");
            }
            if bearer {
                s.push_str(
                    "\t\tif let Some(t) = &self.token { req = req.bearer_auth(t); }\n",
                );
            }
            s.push_str("\t\treq.send().await\n");
            s.push_str("\t}\n\n");
        }

        s.push_str("}\n\n");
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::MiddlewareSpec;
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: "/me".into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn rust_sdk_emits_struct_per_tag() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_rust_client_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("pub struct FluxUeBridgeClient"));
        assert!(sdk.contains("pub base_url: String"));
        assert!(sdk.contains("pub http: reqwest::Client"));
        assert!(!sdk.contains("pub token:"));
    }

    #[test]
    fn rust_sdk_methods_use_lowercase_verbs() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_rust_client_sdk(&eps, "http://api.example/");
        // wickes_cms_1 = POST /api/pages, which now carries a JSON body arg.
        assert!(sdk.contains("pub async fn wickes_cms_1(&self, body: &serde_json::Value)"));
        assert!(sdk.contains(".post(url)"));
        assert!(sdk.contains(".get(url)"));
        assert!(sdk.contains("Result<reqwest::Response, reqwest::Error>"));
    }

    #[test]
    fn rust_sdk_default_base_url_fallback() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_rust_client_sdk(&eps, "https://example.test");
        assert!(sdk.contains("if base_url.is_empty() { \"https://example.test\".into() }"));
    }

    #[test]
    fn rust_sdk_composes_url_via_concat() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_rust_client_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("self.base_url.clone() + \"/v1/workspace\""));
        assert!(sdk.contains("self.base_url.clone() + \"/v1/webhook\""));
    }

    #[test]
    fn rust_sdk_substitutes_path_params_via_format() {
        // GET /api/pages/{id} now binds an `id: &str` arg and substitutes it
        // through `format!`, instead of leaking the literal `{id}` into the URL.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_rust_client_sdk(&eps, "http://localhost:8080");
        assert!(sdk.contains("pub async fn wickes_cms_2(&self, id: &str)"), "missing id arg:\n{sdk}");
        assert!(
            sdk.contains("self.base_url.clone() + &format!(\"/api/pages/{}\", id)"),
            "id not substituted via format!:\n{sdk}"
        );
        assert!(!sdk.contains("+ \"/api/pages/{id}\""), "literal placeholder leaked:\n{sdk}");
    }

    #[test]
    fn rust_sdk_query_endpoint_takes_query_slice() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_rust_client_sdk(&eps, "http://localhost:8080");
        assert!(sdk.contains("query: &[(&str, &str)]"));
        assert!(sdk.contains("req = req.query(query);"));
    }

    #[test]
    fn rust_sdk_body_endpoint_takes_json_value() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_rust_client_sdk(&eps, "http://localhost:8080");
        assert!(sdk.contains("body: &serde_json::Value"));
        assert!(sdk.contains("req = req.json(body);"));
    }

    #[test]
    fn with_types_emits_struct_and_typed_body() {
        use crate::discover::discover_schemas;
        let g = ws(&["wickes-cms"]);
        let eps = discover_endpoints(&g);
        let sdk = generate_rust_client_sdk_with_types(&eps, "http://api", &discover_schemas(&g));
        assert!(sdk.contains("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]"));
        assert!(sdk.contains("pub struct Page {"), "missing struct:\n{sdk}");
        assert!(sdk.contains("pub id: String,"));
        assert!(sdk.contains("pub status: Option<String>,"), "optional field:\n{sdk}");
        // POST body typed &Page, not the open Value.
        assert!(sdk.contains("body: &Page"), "body not typed &Page:\n{sdk}");
        assert!(sdk.contains("req = req.json(body);"));
    }

    #[test]
    fn with_types_resolves_transitive_struct() {
        use crate::discover::discover_schemas;
        let g = ws(&["wickes-erp"]);
        let sdk = generate_rust_client_sdk_with_types(
            &discover_endpoints(&g),
            "http://api",
            &discover_schemas(&g),
        );
        // Order has items: Vec<LineItem>, and LineItem is its own struct.
        assert!(sdk.contains("pub struct Order {"));
        assert!(sdk.contains("pub items: Option<Vec<LineItem>>"), "transitive Vec<LineItem>:\n{sdk}");
        assert!(sdk.contains("pub struct LineItem {"));
    }

    #[test]
    fn rust_sdk_bearer_middleware_adds_token_field_and_bearer_auth() {
        let eps = vec![ep_with_mw(MiddlewareSpec::bearer_auth())];
        let sdk = generate_rust_client_sdk(&eps, "https://api");
        assert!(sdk.contains("pub token: Option<String>"));
        assert!(sdk.contains("pub fn new(base_url: impl Into<String>, token: Option<String>)"));
        assert!(sdk.contains("req = req.bearer_auth(t)"));
    }
}
