// TypeScript REST SDK generator.
//
// v0.14: bare fetch() + JSON parse.
// v0.15-B (rocky 2026-05-29): when any endpoint in a tag carries an active
//   MiddlewareSpec (bearer auth, retry, pagination, streaming), emit a
//   middleware-aware client: optional `token` constructor arg + a private
//   `_fetch` helper that injects `Authorization: Bearer ...` and retries on
//   the configured status codes with exp-backoff. Endpoints without active
//   middleware keep the v0.14 emission for byte-stable output.

use crate::casing::{camel_case, pascal_case};
use crate::middleware::{AuthKind, MiddlewareSpec};
use crate::schema::ApiEndpoint;

pub fn generate_typescript_sdk(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    let mut s = String::from("// Auto-generated by Flux API Builder — Phase 3a\n");
    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = pascal_case(&tag.replace('-', "_"));
        // Effective middleware for this tag = first endpoint's active spec
        // (or none). Mixed-middleware-within-a-tag is a v0.16+ concern.
        let effective = eps
            .iter()
            .find_map(|e| e.middleware.as_ref())
            .filter(|m| m.is_active())
            .cloned();

        if let Some(mw) = effective {
            emit_middleware_client(&mut s, &cn, base_url, &eps, &mw);
        } else {
            emit_basic_client(&mut s, &cn, base_url, &eps);
        }
    }
    s
}

fn emit_basic_client(s: &mut String, cn: &str, base_url: &str, eps: &[&ApiEndpoint]) {
    s.push_str(&format!(
        "export class {cn}Client {{\n  private baseUrl: string;\n  constructor(b: string = \"{base_url}\") {{ this.baseUrl = b; }}\n"
    ));
    for ep in eps {
        s.push_str(&format!(
            "  async {}({}): Promise<any> {{\n    const r = await fetch(`${{this.baseUrl}}{}`, {{ method: \"{}\" }});\n    return r.json();\n  }}\n",
            camel_case(&ep.operation_id),
            "",
            ep.path,
            format!("{:?}", ep.method).to_uppercase()
        ));
    }
    s.push_str("}\n\n");
}

fn emit_middleware_client(
    s: &mut String,
    cn: &str,
    base_url: &str,
    eps: &[&ApiEndpoint],
    mw: &MiddlewareSpec,
) {
    let bearer = matches!(mw.auth, AuthKind::Bearer);
    let retry = &mw.retry;

    // Class header — optional token arg when bearer auth is on.
    s.push_str(&format!("export class {cn}Client {{\n"));
    s.push_str("  private baseUrl: string;\n");
    if bearer {
        s.push_str("  private token: string | null;\n");
    }
    if bearer {
        s.push_str(&format!(
            "  constructor(b: string = \"{base_url}\", token?: string) {{\n    this.baseUrl = b;\n    this.token = token ?? null;\n  }}\n"
        ));
    } else {
        s.push_str(&format!(
            "  constructor(b: string = \"{base_url}\") {{ this.baseUrl = b; }}\n"
        ));
    }

    // Shared _fetch with auth header + retry. Retry list and timings
    // hard-coded from the MiddlewareSpec so the emitted code has no surprises
    // at runtime.
    s.push_str("  private async _fetch(url: string, init: RequestInit): Promise<Response> {\n");
    s.push_str("    const headers: Record<string, string> = { ...(init.headers as any) };\n");
    if bearer {
        s.push_str("    if (this.token) headers[\"Authorization\"] = `Bearer ${this.token}`;\n");
    }
    if retry.is_active() {
        let max_attempts = retry.max_attempts;
        let init_ms = retry.initial_backoff_ms;
        let max_ms = retry.max_backoff_ms;
        let retry_list = retry
            .retry_on_status
            .iter()
            .map(|c| c.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!(
            "    const retryOn = new Set<number>([{retry_list}]);\n\
             \tlet attempt = 0;\n\
             \twhile (true) {{\n\
             \t  const r = await fetch(url, {{ ...init, headers }});\n\
             \t  if (!retryOn.has(r.status) || attempt >= {max_attempts} - 1) return r;\n\
             \t  const backoff = Math.min({init_ms} * Math.pow(2, attempt), {max_ms});\n\
             \t  await new Promise(res => setTimeout(res, backoff));\n\
             \t  attempt++;\n\
             \t}}\n"
        ).replace('\t', "    "));
    } else {
        s.push_str("    return fetch(url, { ...init, headers });\n");
    }
    s.push_str("  }\n");

    // Methods — route through _fetch.
    for ep in eps {
        let mn = camel_case(&ep.operation_id);
        let verb = format!("{:?}", ep.method).to_uppercase();
        s.push_str(&format!(
            "  async {mn}(): Promise<any> {{\n    const r = await this._fetch(`${{this.baseUrl}}{}`, {{ method: \"{verb}\" }});\n    return r.json();\n  }}\n",
            ep.path
        ));
    }
    s.push_str("}\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::{MiddlewareSpec, RetryPolicy};
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }

    fn ep_with_mw(path: &str, mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: path.into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn no_middleware_keeps_v0_14_emission() {
        // Backwards-compat: existing v0.14 callers see no behaviour change.
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_typescript_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("export class FluxUeBridgeClient"));
        assert!(!sdk.contains("_fetch"));
        assert!(!sdk.contains("Authorization"));
    }

    #[test]
    fn bearer_auth_emits_token_arg_and_header() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("private token: string | null"));
        assert!(sdk.contains("constructor(b: string = \"http://api\", token?: string)"));
        assert!(sdk.contains("Authorization"));
        assert!(sdk.contains("`Bearer ${this.token}`"));
    }

    #[test]
    fn retry_policy_emits_loop_and_backoff() {
        let eps = vec![ep_with_mw(
            "/poll",
            MiddlewareSpec::default().with_retry(RetryPolicy::standard()),
        )];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("const retryOn = new Set<number>"));
        assert!(sdk.contains("429"));
        assert!(sdk.contains("503"));
        assert!(sdk.contains("Math.pow(2, attempt)"));
        assert!(sdk.contains("setTimeout"));
    }

    #[test]
    fn middleware_methods_route_through_fetch_helper() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("this._fetch"));
        assert!(!sdk.contains("await fetch(`")); // direct fetch must not appear in methods
    }
}
