// Chrome extension (Manifest V3) target generator.
//
// v0.16 (rocky 2026-05-31): a new emit target alongside the language SDKs. Where
// `sdk_ts`/`sdk_python`/… emit a library you import, this emits a *complete,
// installable* MV3 Chrome extension that wraps the same API surface:
//   • manifest.json    — MV3 manifest, host_permissions scoped to the API origin
//   • flux-client.js   — vanilla-JS client (one class per tag, one method per
//                        operation) — the SDK, but runnable in a service worker
//   • background.js     — service worker that exposes the client over
//                        chrome.runtime messaging (popup/content → API)
//   • popup.html/.js    — a themed popup that lists every endpoint, holds a
//                        bearer token in chrome.storage, and renders responses
//
// Bearer auth is honored exactly like the TS SDK: when a tag's endpoints carry an
// active `AuthKind::Bearer` middleware, the client reads a token (from the call
// opts or the stored token) and attaches `Authorization: Bearer …`.

use crate::casing::{camel_case, pascal_case};
use crate::middleware::AuthKind;
use crate::schema::ApiEndpoint;

/// A generated Chrome extension as a set of (filename, content) files. Write each
/// to a directory and `chrome://extensions → Load unpacked` points at it.
#[derive(Debug, Clone)]
pub struct ChromeExtensionBundle {
    pub files: Vec<(String, String)>,
}

impl ChromeExtensionBundle {
    /// Look up one emitted file's content by name.
    pub fn file(&self, name: &str) -> Option<&str> {
        self.files.iter().find(|(n, _)| n == name).map(|(_, c)| c.as_str())
    }
}

/// Derive an MV3 `host_permissions` origin pattern (`scheme://host/*`) from a base URL.
fn origin_pattern(base_url: &str) -> String {
    let (scheme, rest) = base_url.split_once("://").unwrap_or(("https", base_url));
    let host = rest.split(['/', '?', '#']).next().unwrap_or(rest);
    format!("{scheme}://{host}/*")
}

/// Generate a complete MV3 Chrome extension for the given API surface.
pub fn generate_chrome_extension(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    name: &str,
) -> ChromeExtensionBundle {
    let files = vec![
        ("manifest.json".to_string(), manifest(base_url, name)),
        ("flux-client.js".to_string(), client_js(endpoints, base_url)),
        ("background.js".to_string(), background_js(endpoints)),
        ("popup.html".to_string(), popup_html(name)),
        ("popup.js".to_string(), popup_js(endpoints)),
    ];
    ChromeExtensionBundle { files }
}

fn manifest(base_url: &str, name: &str) -> String {
    // Hand-built so the output is byte-stable and obviously MV3-correct.
    format!(
        "{{\n  \"manifest_version\": 3,\n  \"name\": \"{name} API\",\n  \"version\": \"0.1.0\",\n  \"description\": \"Auto-generated by Flux API Builder — Chrome extension for {name}.\",\n  \"permissions\": [\"storage\"],\n  \"host_permissions\": [\"{origin}\"],\n  \"background\": {{ \"service_worker\": \"background.js\" }},\n  \"action\": {{ \"default_popup\": \"popup.html\", \"default_title\": \"{name} API\" }}\n}}\n",
        name = name,
        origin = origin_pattern(base_url),
    )
}

/// Group endpoints by tag (BTreeSet for stable order), as the TS SDK does.
fn tags_of(endpoints: &[ApiEndpoint]) -> Vec<String> {
    endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect()
}

fn client_js(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    let mut s = String::from(
        "// Auto-generated by Flux API Builder — Chrome MV3 client.\n// Runs in the service worker and the popup. No bundler required.\n",
    );
    for tag in tags_of(endpoints) {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(&tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = pascal_case(&tag.replace('-', "_"));
        let bearer = eps
            .iter()
            .any(|e| e.middleware.as_ref().is_some_and(|m| m.is_active() && matches!(m.auth, AuthKind::Bearer)));

        s.push_str(&format!("class {cn}Client {{\n"));
        s.push_str(&format!(
            "  constructor(baseUrl = \"{base_url}\", token = null) {{ this.baseUrl = baseUrl; this.token = token; }}\n"
        ));
        // shared request helper — path params, query, JSON body, bearer header
        s.push_str("  async _req(method, template, opts = {}) {\n");
        s.push_str("    const path = template.replace(/\\{(\\w+)\\}/g, (_, k) => encodeURIComponent((opts.path || {})[k]));\n");
        s.push_str("    const url = new URL(this.baseUrl + path);\n");
        s.push_str("    for (const [k, v] of Object.entries(opts.query || {})) url.searchParams.set(k, v);\n");
        s.push_str("    const headers = { \"Content-Type\": \"application/json\" };\n");
        if bearer {
            s.push_str("    const token = opts.token ?? this.token;\n");
            s.push_str("    if (token) headers[\"Authorization\"] = \"Bearer \" + token;\n");
        }
        s.push_str("    const init = { method, headers };\n");
        s.push_str("    if (opts.body !== undefined) init.body = JSON.stringify(opts.body);\n");
        s.push_str("    const r = await fetch(url, init);\n");
        s.push_str("    const text = await r.text();\n");
        s.push_str("    try { return { status: r.status, body: JSON.parse(text) }; } catch { return { status: r.status, body: text }; }\n");
        s.push_str("  }\n");
        for ep in &eps {
            let mn = camel_case(&ep.operation_id);
            let verb = format!("{:?}", ep.method).to_uppercase();
            s.push_str(&format!(
                "  async {mn}(opts = {{}}) {{ return this._req(\"{verb}\", \"{}\", opts); }}\n",
                ep.path
            ));
        }
        s.push_str("}\n");
    }
    // expose every client + an endpoint catalogue on the global scope so the
    // service worker (importScripts) and popup can both reach them.
    s.push_str("\nconst FLUX_CLIENTS = {");
    for tag in tags_of(endpoints) {
        let cn = pascal_case(&tag.replace('-', "_"));
        s.push_str(&format!(" \"{cn}\": {cn}Client,"));
    }
    s.push_str(" };\n");
    s.push_str("const FLUX_ENDPOINTS = [\n");
    for ep in endpoints {
        let tag = ep.tags.first().cloned().unwrap_or_default();
        let cn = pascal_case(&tag.replace('-', "_"));
        s.push_str(&format!(
            "  {{ client: \"{cn}\", method: \"{}\", verb: \"{}\", op: \"{}\", path: \"{}\", summary: \"{}\" }},\n",
            camel_case(&ep.operation_id),
            format!("{:?}", ep.method).to_uppercase(),
            ep.operation_id,
            ep.path,
            ep.summary.replace('"', "'"),
        ));
    }
    s.push_str("];\n");
    s.push_str("if (typeof globalThis !== \"undefined\") { globalThis.FLUX_CLIENTS = FLUX_CLIENTS; globalThis.FLUX_ENDPOINTS = FLUX_ENDPOINTS; }\n");
    s
}

fn background_js(_endpoints: &[ApiEndpoint]) -> String {
    // Service worker: load the client, answer call requests over messaging.
    String::from(
        "// Auto-generated by Flux API Builder — MV3 service worker.\n\
         importScripts(\"flux-client.js\");\n\
         \n\
         chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {\n\
         \x20 if (msg?.type !== \"flux-call\") return false;\n\
         \x20 (async () => {\n\
         \x20\x20\x20 try {\n\
         \x20\x20\x20\x20\x20 const { client, method, opts } = msg;\n\
         \x20\x20\x20\x20\x20 const stored = await chrome.storage.local.get(\"token\");\n\
         \x20\x20\x20\x20\x20 const Ctor = globalThis.FLUX_CLIENTS[client];\n\
         \x20\x20\x20\x20\x20 if (!Ctor) throw new Error(\"unknown client: \" + client);\n\
         \x20\x20\x20\x20\x20 const c = new Ctor(undefined, stored.token ?? null);\n\
         \x20\x20\x20\x20\x20 const res = await c[method](opts || {});\n\
         \x20\x20\x20\x20\x20 sendResponse({ ok: true, res });\n\
         \x20\x20\x20 } catch (e) {\n\
         \x20\x20\x20\x20\x20 sendResponse({ ok: false, error: String(e) });\n\
         \x20\x20\x20 }\n\
         \x20 })();\n\
         \x20 return true; // async response\n\
         });\n",
    )
}

fn popup_html(name: &str) -> String {
    // Hyprland-skin themed popup — better flux rendering: method-colored badges,
    // a token field persisted to chrome.storage, a live response pane.
    format!(
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\"/>\n\
         <title>{name} API</title>\n<style>\n\
         :root{{--bg:#0b0712;--panel:#171026;--ink:#e8e3f5;--mauve:#b48ead;--cyan:#88c0d0;--gold:#f5c542;--green:#a3be8c;--red:#ff5277;}}\n\
         body{{width:420px;margin:0;background:radial-gradient(420px 300px at 50% -10%,#1d1238,var(--bg));color:var(--ink);font:13px/1.5 Inter,system-ui,sans-serif}}\n\
         header{{padding:12px 14px 6px}} h1{{margin:0;font-size:16px}} h1 .v{{color:var(--gold);font-family:ui-monospace,monospace;font-size:11px}}\n\
         .tok{{display:flex;gap:6px;padding:6px 14px}} .tok input{{flex:1;background:#0006;border:1px solid #ffffff22;border-radius:6px;color:var(--ink);padding:6px 8px;font-family:ui-monospace,monospace}}\n\
         button{{font:inherit;background:#ffffff14;border:1px solid #ffffff22;color:var(--ink);border-radius:6px;padding:5px 9px;cursor:pointer}} button:hover{{background:#ffffff24}}\n\
         .ep{{display:flex;align-items:center;gap:8px;padding:6px 14px;border-top:1px solid #ffffff10}}\n\
         .verb{{font-family:ui-monospace,monospace;font-size:10px;font-weight:700;padding:2px 6px;border-radius:4px;min-width:46px;text-align:center}}\n\
         .GET{{background:#88c0d022;color:var(--cyan)}} .POST{{background:#a3be8c22;color:var(--green)}} .PUT{{background:#f5c54222;color:var(--gold)}} .DELETE{{background:#ff527722;color:var(--red)}} .PATCH{{background:#b48ead22;color:var(--mauve)}}\n\
         .op{{flex:1;font-family:ui-monospace,monospace;font-size:11px;color:#cfc7e6;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}\n\
         pre{{margin:0;padding:10px 14px;background:#05030c;white-space:pre-wrap;word-break:break-word;max-height:240px;overflow:auto;font-family:ui-monospace,monospace;font-size:11px;color:var(--green)}}\n\
         </style></head><body>\n\
         <header><h1>{name} <span class=\"v\">API · flux-gen</span></h1></header>\n\
         <div class=\"tok\"><input id=\"token\" placeholder=\"Bearer token (stored locally)\"/><button id=\"save\">Save</button></div>\n\
         <div id=\"list\"></div>\n<pre id=\"out\">— pick an endpoint —</pre>\n\
         <script src=\"flux-client.js\"></script><script src=\"popup.js\"></script>\n</body></html>\n",
    )
}

fn popup_js(_endpoints: &[ApiEndpoint]) -> String {
    String::from(
        "// Auto-generated by Flux API Builder — popup controller.\n\
         const out = document.getElementById(\"out\");\n\
         const tokenEl = document.getElementById(\"token\");\n\
         chrome.storage.local.get(\"token\").then(s => { if (s.token) tokenEl.value = s.token; });\n\
         document.getElementById(\"save\").onclick = () => chrome.storage.local.set({ token: tokenEl.value || null }).then(() => { out.textContent = \"token saved\"; });\n\
         const list = document.getElementById(\"list\");\n\
         for (const ep of globalThis.FLUX_ENDPOINTS) {\n\
         \x20 const row = document.createElement(\"div\"); row.className = \"ep\";\n\
         \x20 const v = document.createElement(\"span\"); v.className = \"verb \" + ep.verb; v.textContent = ep.verb; row.appendChild(v);\n\
         \x20 const o = document.createElement(\"span\"); o.className = \"op\"; o.title = ep.summary || ep.path; o.textContent = ep.path; row.appendChild(o);\n\
         \x20 const b = document.createElement(\"button\"); b.textContent = \"call\";\n\
         \x20 b.onclick = () => { out.textContent = \"…\"; chrome.runtime.sendMessage({ type: \"flux-call\", client: ep.client, method: ep.method, opts: {} }, (r) => { out.textContent = r && r.ok ? JSON.stringify(r.res, null, 2) : (\"error: \" + (r ? r.error : \"no response\")); }); };\n\
         \x20 row.appendChild(b); list.appendChild(row);\n\
         }\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::middleware::MiddlewareSpec;
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};
    use serde_json::Value;

    fn ep(op: &str, method: HttpMethod, path: &str, tag: &str, mw: Option<MiddlewareSpec>) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method,
            path: path.into(),
            operation_id: op.into(),
            summary: "demo op".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec![tag.into()],
            middleware: mw,
        }
    }

    fn sample() -> Vec<ApiEndpoint> {
        vec![
            ep("list_pools", HttpMethod::GET, "/v1/pools", "dex", None),
            ep("get_pool", HttpMethod::GET, "/v1/pools/{id}", "dex", None),
            ep("submit_share", HttpMethod::POST, "/v1/share", "mining", Some(MiddlewareSpec::bearer_auth())),
        ]
    }

    #[test]
    fn bundle_has_all_mv3_files() {
        let b = generate_chrome_extension(&sample(), "https://sigilgraph.quillon.xyz", "SIGIL");
        for f in ["manifest.json", "flux-client.js", "background.js", "popup.html", "popup.js"] {
            assert!(b.file(f).is_some(), "missing {f}");
        }
    }

    #[test]
    fn manifest_is_valid_mv3_with_scoped_origin() {
        let b = generate_chrome_extension(&sample(), "https://sigilgraph.quillon.xyz/api", "SIGIL");
        let m: Value = serde_json::from_str(b.file("manifest.json").unwrap()).expect("manifest is valid JSON");
        assert_eq!(m["manifest_version"], 3);
        assert_eq!(m["background"]["service_worker"], "background.js");
        assert_eq!(m["action"]["default_popup"], "popup.html");
        let origins = m["host_permissions"].as_array().unwrap();
        assert_eq!(origins[0], "https://sigilgraph.quillon.xyz/*", "origin must be scoped to the API host");
    }

    #[test]
    fn client_emits_class_per_tag_and_method_per_op() {
        let js = client_js(&sample(), "https://api");
        assert!(js.contains("class DexClient"));
        assert!(js.contains("class MiningClient"));
        assert!(js.contains("async listPools(opts = {})"));
        assert!(js.contains("async getPool(opts = {})"));
        assert!(js.contains("async submitShare(opts = {})"));
        // path-param substitution + catalogue
        assert!(js.contains("/v1/pools/{id}"));
        assert!(js.contains("FLUX_ENDPOINTS"));
    }

    #[test]
    fn bearer_tag_attaches_authorization_header() {
        let js = client_js(&sample(), "https://api");
        // mining tag has bearer middleware → its client injects the header
        assert!(js.contains("Authorization"));
        assert!(js.contains("\"Bearer \" + token"));
    }

    #[test]
    fn service_worker_wires_messaging() {
        let b = generate_chrome_extension(&sample(), "https://api", "SIGIL");
        let bg = b.file("background.js").unwrap();
        assert!(bg.contains("importScripts(\"flux-client.js\")"));
        assert!(bg.contains("chrome.runtime.onMessage.addListener"));
        assert!(bg.contains("flux-call"));
    }
}
