// Go REST SDK generator.
//
// v0.14-A: idiomatic context.Context + *http.Client; one struct per tag.
// v0.15-C (rocky 2026-05-29): when any endpoint in a tag carries an active
// `MiddlewareSpec` with bearer auth, add a `Token string` field and inject
// `Authorization: Bearer ...` per request. Retry/pagination/streaming are a
// v0.15.x polish — they're tracked in the roadmap but not lowered into Go
// yet to keep the v0.15-C surface tight.

use crate::casing::pascal_case;
use crate::codegen::{
    as_object, body_type_name, has_body, path_params, prim_of, query_params, render_path,
    SchemaDefs,
};
use crate::middleware::AuthKind;
use crate::schema::{ApiEndpoint, ApiSchema, PrimType};
use std::collections::BTreeMap;

fn go_type(schema: &ApiSchema) -> &'static str {
    match prim_of(schema) {
        Some(PrimType::Integer) => "int64",
        Some(PrimType::Number) => "float64",
        Some(PrimType::Boolean) => "bool",
        Some(PrimType::String) | None => "string",
    }
}

/// Field type for a struct: refs → the struct name, arrays → `[]..`, nullables
/// → `*..` (pointer so the zero value is distinguishable / omitempty works),
/// inline objects/oneOf → `map[string]interface{}` / `interface{}`.
fn go_type_ref(schema: &ApiSchema) -> String {
    match schema {
        ApiSchema::Primitive { .. } | ApiSchema::Enum { .. } => go_type(schema).to_string(),
        ApiSchema::Ref { name } => pascal_case(&name.replace('-', "_")),
        ApiSchema::Array { items } => format!("[]{}", go_type_ref(items)),
        ApiSchema::Nullable { inner } => format!("*{}", go_type_ref(inner)),
        ApiSchema::Object { .. } => "map[string]interface{}".into(),
        ApiSchema::OneOf { .. } => "interface{}".into(),
    }
}

/// Emit a `type <Name> struct { ... }` with json tags per object schema.
fn emit_go_types(s: &mut String, defs: &SchemaDefs) {
    for (name, schema) in defs {
        let tn = pascal_case(&name.replace('-', "_"));
        match as_object(schema) {
            Some((props, required)) => {
                s.push_str(&format!("type {tn} struct {{\n"));
                for (field, fschema) in props {
                    let fname = pascal_case(&field.replace('-', "_"));
                    let omit = if required.contains(field) { "" } else { ",omitempty" };
                    s.push_str(&format!(
                        "\t{fname} {} `json:\"{field}{omit}\"`\n",
                        go_type_ref(fschema)
                    ));
                }
                s.push_str("}\n\n");
            }
            None => {
                s.push_str(&format!("type {tn} = {}\n\n", go_type_ref(schema)));
            }
        }
    }
}

/// Back-compat entry point: no registry → bodies are `any`, no structs emitted.
pub fn generate_go_sdk(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    package_name: &str,
) -> String {
    generate_go_sdk_with_types(endpoints, base_url, package_name, &BTreeMap::new())
}

/// Emit the Go SDK with a json-tagged `struct` per registry schema and a typed
/// `body <Name>` arg on `Ref`-bodied endpoints.
pub fn generate_go_sdk_with_types(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    package_name: &str,
    defs: &SchemaDefs,
) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Go SDK (v0.14)\n");
    s.push_str(&format!("package {package_name}\n\n"));

    // Go forbids unused imports, so include only what the emitted methods use.
    let any_path = endpoints.iter().any(|e| !path_params(e).is_empty());
    let any_query = endpoints.iter().any(|e| !query_params(e).is_empty());
    let any_body = endpoints.iter().any(has_body);
    s.push_str("import (\n");
    if any_body {
        s.push_str("\t\"bytes\"\n");
    }
    s.push_str("\t\"context\"\n");
    if any_body {
        s.push_str("\t\"encoding/json\"\n");
    }
    if any_path {
        s.push_str("\t\"fmt\"\n");
    }
    s.push_str("\t\"net/http\"\n");
    if any_query {
        s.push_str("\t\"net/url\"\n");
    }
    s.push_str(")\n\n");

    emit_go_types(&mut s, defs);

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = format!("{}Client", pascal_case(&tag.replace('-', "_")));
        let bearer = eps.iter().any(|e| {
            e.middleware
                .as_ref()
                .map(|m| matches!(m.auth, AuthKind::Bearer))
                .unwrap_or(false)
        });

        // Struct fields.
        s.push_str(&format!("type {cn} struct {{\n"));
        s.push_str("\tBaseURL string\n");
        s.push_str("\tHTTP    *http.Client\n");
        if bearer {
            s.push_str("\tToken   string\n");
        }
        s.push_str("}\n\n");

        // Constructor — the bearer variant takes a second arg.
        if bearer {
            s.push_str(&format!(
                "func New{cn}(baseURL, token string) *{cn} {{\n\
                 \tif baseURL == \"\" {{ baseURL = \"{base_url}\" }}\n\
                 \treturn &{cn}{{BaseURL: baseURL, HTTP: http.DefaultClient, Token: token}}\n\
                 }}\n\n"
            ));
        } else {
            s.push_str(&format!(
                "func New{cn}(baseURL string) *{cn} {{\n\
                 \tif baseURL == \"\" {{ baseURL = \"{base_url}\" }}\n\
                 \treturn &{cn}{{BaseURL: baseURL, HTTP: http.DefaultClient}}\n\
                 }}\n\n"
            ));
        }

        for ep in &eps {
            let method_name = pascal_case(&ep.operation_id);
            let http_verb = format!("{:?}", ep.method).to_uppercase();
            let pps = path_params(ep);
            let qps = query_params(ep);
            let body = has_body(ep);

            // Signature: ctx → path params (typed) → body any → query map.
            let mut sig: Vec<String> = vec!["ctx context.Context".into()];
            for p in &pps {
                sig.push(format!("{} {}", p.name, go_type(&p.schema)));
            }
            if body {
                let bt = body_type_name(ep.request_body.as_ref(), defs)
                    .map(|n| pascal_case(&n.replace('-', "_")))
                    .unwrap_or_else(|| "any".into());
                sig.push(format!("body {bt}"));
            }
            if !qps.is_empty() {
                sig.push("query map[string]string".into());
            }
            s.push_str(&format!(
                "// {summary}\nfunc (c *{cn}) {method_name}({sig}) (*http.Response, error) {{\n",
                summary = ep.summary,
                sig = sig.join(", "),
            ));

            // URL.
            if pps.is_empty() {
                s.push_str(&format!("\turlStr := c.BaseURL + \"{}\"\n", ep.path));
            } else {
                let fmt = render_path(&ep.path, |_| "%v".to_string());
                let args: Vec<String> = pps.iter().map(|p| p.name.clone()).collect();
                s.push_str(&format!(
                    "\turlStr := c.BaseURL + fmt.Sprintf(\"{fmt}\", {})\n",
                    args.join(", ")
                ));
            }
            if !qps.is_empty() {
                s.push_str(
                    "\tif len(query) > 0 {\n\
                     \t\tq := url.Values{}\n\
                     \t\tfor k, v := range query {\n\
                     \t\t\tq.Set(k, v)\n\
                     \t\t}\n\
                     \t\turlStr += \"?\" + q.Encode()\n\
                     \t}\n",
                );
            }

            // Request (+ JSON body when present).
            if body {
                s.push_str(&format!(
                    "\tbodyBytes, err := json.Marshal(body)\n\
                     \tif err != nil {{ return nil, err }}\n\
                     \treq, err := http.NewRequestWithContext(ctx, \"{http_verb}\", urlStr, bytes.NewReader(bodyBytes))\n\
                     \tif err != nil {{ return nil, err }}\n\
                     \treq.Header.Set(\"Content-Type\", \"application/json\")\n"
                ));
            } else {
                s.push_str(&format!(
                    "\treq, err := http.NewRequestWithContext(ctx, \"{http_verb}\", urlStr, nil)\n\
                     \tif err != nil {{ return nil, err }}\n"
                ));
            }
            if bearer {
                s.push_str(
                    "\tif c.Token != \"\" {\n\
                     \t\treq.Header.Set(\"Authorization\", \"Bearer \"+c.Token)\n\
                     \t}\n",
                );
            }
            s.push_str("\treturn c.HTTP.Do(req)\n}\n\n");
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::MiddlewareSpec;
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: "/me".into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn go_sdk_has_package_and_imports() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:8080", "wickescms");
        assert!(sdk.starts_with("// Auto-generated"));
        assert!(sdk.contains("package wickescms"));
        assert!(sdk.contains("\"context\""));
        assert!(sdk.contains("\"net/http\""));
    }

    #[test]
    fn go_sdk_emits_client_struct_per_tag() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:9989", "uebridge");
        assert!(sdk.contains("type FluxUeBridgeClient struct"));
        assert!(sdk.contains("BaseURL string"));
        assert!(sdk.contains("HTTP    *http.Client"));
        assert!(sdk.contains("func NewFluxUeBridgeClient(baseURL string) *FluxUeBridgeClient"));
        assert!(!sdk.contains("Token   string"));
    }

    #[test]
    fn go_sdk_methods_use_context_and_method_verbs() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:8080", "wickescms");
        // WickesCms1 = POST /api/pages, which now takes a JSON body arg.
        assert!(sdk.contains("func (c *WickesCmsClient) WickesCms1(ctx context.Context, body any)"));
        assert!(sdk.contains("\"POST\""));
        assert!(sdk.contains("http.NewRequestWithContext"));
    }

    #[test]
    fn go_sdk_substitutes_path_params_via_sprintf() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:8080", "wickescms");
        assert!(sdk.contains("WickesCms2(ctx context.Context, id string)"), "missing id arg:\n{sdk}");
        assert!(sdk.contains("fmt.Sprintf(\"/api/pages/%v\", id)"), "id not Sprintf'd:\n{sdk}");
        assert!(!sdk.contains("c.BaseURL + \"/api/pages/{id}\""), "literal placeholder leaked:\n{sdk}");
        assert!(sdk.contains("\t\"fmt\"\n"), "fmt import missing:\n{sdk}");
    }

    #[test]
    fn go_sdk_query_endpoint_encodes_url_values() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:8080", "wickescms");
        assert!(sdk.contains("query map[string]string"));
        assert!(sdk.contains("url.Values{}"));
        assert!(sdk.contains("q.Encode()"));
        assert!(sdk.contains("\t\"net/url\"\n"));
    }

    #[test]
    fn go_sdk_body_endpoint_marshals_json() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:8080", "wickescms");
        assert!(sdk.contains("json.Marshal(body)"));
        assert!(sdk.contains("bytes.NewReader(bodyBytes)"));
        assert!(sdk.contains("req.Header.Set(\"Content-Type\", \"application/json\")"));
        assert!(sdk.contains("\t\"encoding/json\"\n"));
        assert!(sdk.contains("\t\"bytes\"\n"));
    }

    #[test]
    fn with_types_emits_struct_with_json_tags_and_typed_body() {
        use crate::discover::discover_schemas;
        let g = ws(&["wickes-cms"]);
        let eps = discover_endpoints(&g);
        let sdk = generate_go_sdk_with_types(&eps, "http://api", "wickescms", &discover_schemas(&g));
        assert!(sdk.contains("type Page struct {"), "missing struct:\n{sdk}");
        assert!(sdk.contains("Id string `json:\"id\"`"), "id field+tag:\n{sdk}");
        assert!(sdk.contains("Status string `json:\"status,omitempty\"`"), "optional tag:\n{sdk}");
        // POST body typed Page, marshaled.
        assert!(sdk.contains("body Page)"), "body not typed Page:\n{sdk}");
        assert!(sdk.contains("json.Marshal(body)"));
    }

    #[test]
    fn go_sdk_static_endpoint_keeps_plain_imports() {
        // flux-ue-bridge GET endpoints have no path/query, but the webhook POST
        // carries a body — so bytes/json are imported, fmt/url are not.
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:9989", "uebridge");
        assert!(!sdk.contains("\t\"fmt\"\n"), "fmt should not be imported (no path params):\n{sdk}");
        assert!(!sdk.contains("\t\"net/url\"\n"), "net/url should not be imported (no query):\n{sdk}");
    }

    #[test]
    fn go_sdk_default_base_url_fallback() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "https://example.test", "wickescms");
        assert!(sdk.contains("if baseURL == \"\" { baseURL = \"https://example.test\" }"));
    }

    #[test]
    fn go_sdk_bearer_middleware_adds_token_field_and_header() {
        let eps = vec![ep_with_mw(MiddlewareSpec::bearer_auth())];
        let sdk = generate_go_sdk(&eps, "https://api", "demo");
        assert!(sdk.contains("Token   string"));
        assert!(sdk.contains("func NewDemoClient(baseURL, token string)"));
        assert!(sdk.contains("Token: token"));
        assert!(sdk.contains("req.Header.Set(\"Authorization\", \"Bearer \"+c.Token)"));
    }
}
