// Python REST SDK generator.
//
// v0.14: bare httpx.
// v0.15-B (rocky 2026-05-29): when an endpoint carries an active
// MiddlewareSpec we emit a richer client: optional `token=` constructor arg
// for bearer auth + an internal `_request` helper that injects the
// `Authorization` header and retries with exp-backoff on the configured
// status codes. Endpoints without active middleware keep the v0.14 emission.

use crate::casing::{pascal_case, snake_case};
use crate::codegen::{
    as_object, body_type_name, has_body, path_params, prim_of, query_params, render_path,
    SchemaDefs,
};
use crate::middleware::{AuthKind, MiddlewareSpec};
use crate::schema::{ApiEndpoint, ApiSchema, PrimType};
use std::collections::BTreeMap;

/// Back-compat entry point: no schema registry, so bodies are untyped (`body=None`)
/// and no `TypedDict`s are emitted.
pub fn generate_python_sdk(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    generate_python_sdk_with_types(endpoints, base_url, &BTreeMap::new())
}

/// Emit the Python SDK with a `TypedDict` per registry schema, and annotate each
/// `Ref`-bodied endpoint's `body` param with that name.
pub fn generate_python_sdk_with_types(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    defs: &SchemaDefs,
) -> String {
    let mut s = String::from("# Auto-generated by Flux API Builder — Phase 3a\nimport httpx\n");
    // `time` only used by the retry path; emit unconditionally so the file
    // parses cleanly when toggled in/out across regenerations.
    s.push_str("import time\n");
    if !defs.is_empty() {
        s.push_str("from typing import List, Optional, TypedDict\n");
    }
    s.push_str("\n");
    emit_py_types(&mut s, defs);

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = pascal_case(&tag.replace('-', "_"));
        let effective = eps
            .iter()
            .find_map(|e| e.middleware.as_ref())
            .filter(|m| m.is_active())
            .cloned();

        if let Some(mw) = effective {
            emit_middleware_client(&mut s, &cn, base_url, &eps, &mw, defs);
        } else {
            emit_basic_client(&mut s, &cn, base_url, &eps, defs);
        }
    }
    s
}

fn py_type(schema: &ApiSchema) -> &'static str {
    match prim_of(schema) {
        Some(PrimType::Integer) => "int",
        Some(PrimType::Number) => "float",
        Some(PrimType::Boolean) => "bool",
        Some(PrimType::String) | None => "str",
    }
}

/// Rich annotation: refs become the TypedDict name, arrays become `List[..]`,
/// nullables `Optional[..]`, inline objects `dict`.
fn py_type_ref(schema: &ApiSchema) -> String {
    match schema {
        ApiSchema::Primitive { .. } | ApiSchema::Enum { .. } => py_type(schema).to_string(),
        ApiSchema::Ref { name } => pascal_case(&name.replace('-', "_")),
        ApiSchema::Array { items } => format!("List[{}]", py_type_ref(items)),
        ApiSchema::Nullable { inner } => format!("Optional[{}]", py_type_ref(inner)),
        ApiSchema::Object { .. } => "dict".into(),
        ApiSchema::OneOf { .. } => "object".into(),
    }
}

/// Emit a `TypedDict` per object schema (type alias for non-objects).
fn emit_py_types(s: &mut String, defs: &SchemaDefs) {
    for (name, schema) in defs {
        let tn = pascal_case(&name.replace('-', "_"));
        match as_object(schema) {
            Some((props, required)) => {
                s.push_str(&format!("class {tn}(TypedDict):\n"));
                if props.is_empty() {
                    s.push_str("    pass\n");
                }
                for (field, fschema) in props {
                    let ty = py_type_ref(fschema);
                    let ann = if required.contains(field) { ty } else { format!("Optional[{ty}]") };
                    s.push_str(&format!("    {field}: {ann}\n"));
                }
                s.push_str("\n\n");
            }
            None => {
                s.push_str(&format!("{tn} = {}\n\n\n", py_type_ref(schema)));
            }
        }
    }
}

/// Build the `(self, <path args>, [body=None], [params=None])` signature and
/// the `f"<path>"` template + trailing kwargs (`, json=body`, `, params=params`)
/// shared by the basic and middleware method emitters. `defs` types the body
/// param when it's a known `Ref`.
fn py_sig_and_call(ep: &ApiEndpoint, defs: &SchemaDefs) -> (String, String, String) {
    let mut args: Vec<String> = vec!["self".into()];
    for p in path_params(ep) {
        args.push(format!("{}: {}", snake_case(&p.name), py_type(&p.schema)));
    }
    let body = has_body(ep);
    let qps = query_params(ep);
    if body {
        match body_type_name(ep.request_body.as_ref(), defs) {
            Some(n) => args.push(format!("body: {} = None", pascal_case(&n.replace('-', "_")))),
            None => args.push("body=None".into()),
        }
    }
    if !qps.is_empty() {
        args.push("params=None".into());
    }
    let tmpl = render_path(&ep.path, |n| format!("{{{}}}", snake_case(n)));
    let mut kwargs = String::new();
    if !qps.is_empty() {
        kwargs.push_str(", params=params");
    }
    if body {
        kwargs.push_str(", json=body");
    }
    (args.join(", "), tmpl, kwargs)
}

fn emit_basic_client(s: &mut String, cn: &str, base_url: &str, eps: &[&ApiEndpoint], defs: &SchemaDefs) {
    s.push_str(&format!(
        "class {cn}Client:\n    def __init__(self, base_url: str = \"{base_url}\"):\n        self.c = httpx.Client(base_url=base_url)\n\n"
    ));
    for ep in eps {
        let (sig, tmpl, kwargs) = py_sig_and_call(ep, defs);
        s.push_str(&format!(
            "    def {}({sig}):\n        return self.c.{}(f\"{tmpl}\"{kwargs}).json()\n\n",
            snake_case(&ep.operation_id),
            format!("{:?}", ep.method).to_lowercase(),
        ));
    }
}

fn emit_middleware_client(
    s: &mut String,
    cn: &str,
    base_url: &str,
    eps: &[&ApiEndpoint],
    mw: &MiddlewareSpec,
    defs: &SchemaDefs,
) {
    let bearer = matches!(mw.auth, AuthKind::Bearer);
    let retry = &mw.retry;

    s.push_str(&format!("class {cn}Client:\n"));
    if bearer {
        s.push_str(&format!(
            "    def __init__(self, base_url: str = \"{base_url}\", token: str | None = None):\n        self.c = httpx.Client(base_url=base_url)\n        self.token = token\n\n"
        ));
    } else {
        s.push_str(&format!(
            "    def __init__(self, base_url: str = \"{base_url}\"):\n        self.c = httpx.Client(base_url=base_url)\n\n"
        ));
    }

    s.push_str("    def _request(self, method: str, path: str, params=None, json=None):\n");
    s.push_str("        headers = {}\n");
    if bearer {
        s.push_str("        if self.token:\n            headers[\"Authorization\"] = f\"Bearer {self.token}\"\n");
    }
    if retry.is_active() {
        let max_attempts = retry.max_attempts;
        let init_ms = retry.initial_backoff_ms;
        let max_ms = retry.max_backoff_ms;
        let retry_list = retry
            .retry_on_status
            .iter()
            .map(|c| c.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!(
            "        retry_on = {{{retry_list}}}\n\
             \tattempt = 0\n\
             \twhile True:\n\
             \t    r = self.c.request(method, path, headers=headers, params=params, json=json)\n\
             \t    if r.status_code not in retry_on or attempt >= {max_attempts} - 1:\n\
             \t        return r\n\
             \t    backoff = min({init_ms} * (2 ** attempt), {max_ms}) / 1000.0\n\
             \t    time.sleep(backoff)\n\
             \t    attempt += 1\n"
        ).replace('\t', "        "));
    } else {
        s.push_str("        return self.c.request(method, path, headers=headers, params=params, json=json)\n");
    }
    s.push_str("\n");

    for ep in eps {
        let mn = snake_case(&ep.operation_id);
        let verb = format!("{:?}", ep.method).to_uppercase();
        let (sig, tmpl, kwargs) = py_sig_and_call(ep, defs);
        s.push_str(&format!(
            "    def {mn}({sig}):\n        return self._request(\"{verb}\", f\"{tmpl}\"{kwargs}).json()\n\n"
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::{MiddlewareSpec, RetryPolicy};
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(path: &str, mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: path.into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn no_middleware_keeps_v0_14_emission() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_python_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("class FluxUeBridgeClient:"));
        assert!(!sdk.contains("_request"));
        assert!(!sdk.contains("Authorization"));
    }

    #[test]
    fn bearer_auth_emits_token_arg_and_header() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("token: str | None = None"));
        assert!(sdk.contains("Authorization"));
        assert!(sdk.contains("f\"Bearer {self.token}\""));
    }

    #[test]
    fn retry_policy_emits_loop_and_sleep() {
        let eps = vec![ep_with_mw(
            "/poll",
            MiddlewareSpec::default().with_retry(RetryPolicy::standard()),
        )];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("retry_on = {"));
        assert!(sdk.contains("429"));
        assert!(sdk.contains("503"));
        assert!(sdk.contains("time.sleep"));
        assert!(sdk.contains("2 ** attempt"));
    }

    #[test]
    fn middleware_methods_route_through_request_helper() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("self._request"));
        assert!(!sdk.contains("self.c.get(\"/me\")"));
    }

    #[test]
    fn path_param_is_typed_arg_and_fstring_substituted() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("id: str"), "missing typed id arg:\n{sdk}");
        // The path is an f-string so `{id}` binds the arg at call time. The
        // non-f form (a plain httpx call on the literal placeholder) must not
        // appear — that would hit the URL `/api/pages/{id}` verbatim.
        assert!(sdk.contains("f\"/api/pages/{id}\""), "id not f-string substituted:\n{sdk}");
        assert!(!sdk.contains("self.c.get(\"/api/pages/{id}\")"), "non-f literal call leaked:\n{sdk}");
    }

    #[test]
    fn query_param_passes_params_kwarg() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("params=None"));
        assert!(sdk.contains(", params=params)"));
    }

    #[test]
    fn body_endpoint_passes_json_kwarg() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("body=None"));
        assert!(sdk.contains(", json=body)"));
    }

    #[test]
    fn middleware_request_helper_forwards_params_and_json() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("def _request(self, method: str, path: str, params=None, json=None)"));
        assert!(sdk.contains("params=params, json=json"));
    }

    #[test]
    fn with_types_emits_typeddict_and_typed_body() {
        use crate::discover::discover_schemas;
        let g = ws(&["wickes-cms"]);
        let eps = discover_endpoints(&g);
        let sdk = generate_python_sdk_with_types(&eps, "http://api", &discover_schemas(&g));
        assert!(sdk.contains("from typing import List, Optional, TypedDict"));
        assert!(sdk.contains("class Page(TypedDict):"), "missing TypedDict:\n{sdk}");
        assert!(sdk.contains("    id: str"));
        assert!(sdk.contains("    title: str"));
        assert!(sdk.contains("    status: Optional[str]"), "optional enum field:\n{sdk}");
        // POST body param annotated Page.
        assert!(sdk.contains("body: Page = None"), "body not typed Page:\n{sdk}");
    }

    #[test]
    fn without_registry_no_typeddict_body_untyped() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(!sdk.contains("TypedDict"));
        assert!(sdk.contains("body=None"));
    }
}
