// Kotlin SDK generator.
//
// v0.14-C: coroutine-based OkHttp clients.
// v0.15-C (rocky 2026-05-29): when any endpoint in a tag carries an active
// `MiddlewareSpec` with bearer auth, add a `token: String? = null`
// constructor arg and call `.addHeader("Authorization", "Bearer $token")`
// before building each request.

use crate::casing::{camel_case, pascal_case};
use crate::middleware::AuthKind;
use crate::schema::{ApiEndpoint, HttpMethod};

pub fn generate_kotlin_sdk(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    package_name: &str,
) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Kotlin SDK (v0.14)\n");
    s.push_str(&format!("package {package_name}\n\n"));
    s.push_str("import kotlinx.coroutines.Dispatchers\n");
    s.push_str("import kotlinx.coroutines.withContext\n");
    s.push_str("import okhttp3.OkHttpClient\n");
    s.push_str("import okhttp3.Request\n");
    s.push_str("import okhttp3.RequestBody.Companion.toRequestBody\n");
    s.push_str("import okhttp3.Response\n\n");

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = format!("{}Client", pascal_case(&tag.replace('-', "_")));
        let bearer = eps.iter().any(|e| {
            e.middleware
                .as_ref()
                .map(|m| matches!(m.auth, AuthKind::Bearer))
                .unwrap_or(false)
        });

        // Class header.
        s.push_str(&format!("class {cn}(\n"));
        s.push_str(&format!(
            "\tprivate val baseUrl: String = \"{base_url}\",\n"
        ));
        s.push_str("\tprivate val client: OkHttpClient = OkHttpClient(),\n");
        if bearer {
            s.push_str("\tprivate val token: String? = null,\n");
        }
        s.push_str(") {\n\n");

        for ep in &eps {
            let method_name = camel_case(&ep.operation_id);
            s.push_str(&format!(
                "\t/** {summary} */\n\
                 \tsuspend fun {method_name}(): Response = withContext(Dispatchers.IO) {{\n\
                 \t\tval builder = Request.Builder()\n\
                 \t\t\t.url(\"$baseUrl{path}\")\n",
                summary = ep.summary,
                method_name = method_name,
                path = ep.path,
            ));
            match ep.method {
                HttpMethod::GET => s.push_str("\t\t\t.get()\n"),
                HttpMethod::POST => s.push_str("\t\t\t.post(\"\".toRequestBody())\n"),
                HttpMethod::PUT => s.push_str("\t\t\t.put(\"\".toRequestBody())\n"),
                HttpMethod::PATCH => s.push_str("\t\t\t.patch(\"\".toRequestBody())\n"),
                HttpMethod::DELETE => s.push_str("\t\t\t.delete()\n"),
            }
            if bearer {
                s.push_str("\t\ttoken?.let { builder.addHeader(\"Authorization\", \"Bearer $it\") }\n");
                s.push_str("\t\tval req = builder.build()\n");
            } else {
                s.push_str("\t\tval req = builder.build()\n");
            }
            s.push_str("\t\tclient.newCall(req).execute()\n");
            s.push_str("\t}\n\n");
        }

        s.push_str("}\n\n");
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::MiddlewareSpec;
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: "/me".into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn kotlin_sdk_has_package_and_imports() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_kotlin_sdk(&eps, "http://localhost:9989", "io.flux.ue");
        assert!(sdk.contains("package io.flux.ue"));
        assert!(sdk.contains("import kotlinx.coroutines.Dispatchers"));
        assert!(sdk.contains("import okhttp3.OkHttpClient"));
        assert!(sdk.contains("import okhttp3.Response"));
    }

    #[test]
    fn kotlin_sdk_emits_class_per_tag() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_kotlin_sdk(&eps, "http://localhost:9989", "io.flux.ue");
        assert!(sdk.contains("class FluxUeBridgeClient("));
        assert!(sdk.contains("private val baseUrl: String = \"http://localhost:9989\""));
        assert!(sdk.contains("private val client: OkHttpClient = OkHttpClient()"));
        assert!(!sdk.contains("private val token"));
    }

    #[test]
    fn kotlin_sdk_methods_are_suspend_fun_with_dispatchers_io() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_kotlin_sdk(&eps, "http://localhost:9989", "io.flux.ue");
        assert!(sdk.contains("suspend fun fluxUeBridge0()"));
        assert!(sdk.contains("withContext(Dispatchers.IO)"));
        assert!(sdk.contains("client.newCall(req).execute()"));
    }

    #[test]
    fn kotlin_sdk_uses_correct_okhttp_verbs() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_kotlin_sdk(&eps, "https://example.test", "com.wickes.cms");
        assert!(sdk.contains(".get()"));
        assert!(sdk.contains(".post(\"\".toRequestBody())"));
    }

    #[test]
    fn kotlin_sdk_interpolates_base_url_in_path() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_kotlin_sdk(&eps, "http://localhost:9989", "io.flux.ue");
        assert!(sdk.contains(".url(\"$baseUrl/v1/workspace\")"));
        assert!(sdk.contains(".url(\"$baseUrl/v1/webhook\")"));
    }

    #[test]
    fn kotlin_sdk_bearer_middleware_adds_token_param_and_header() {
        let eps = vec![ep_with_mw(MiddlewareSpec::bearer_auth())];
        let sdk = generate_kotlin_sdk(&eps, "https://api", "io.demo");
        assert!(sdk.contains("private val token: String? = null"));
        assert!(sdk.contains("token?.let { builder.addHeader(\"Authorization\", \"Bearer $it\") }"));
    }
}
