// TypeScript REST SDK generator.
//
// v0.14: bare fetch() + JSON parse.
// v0.15-B (rocky 2026-05-29): when any endpoint in a tag carries an active
//   MiddlewareSpec (bearer auth, retry, pagination, streaming), emit a
//   middleware-aware client: optional `token` constructor arg + a private
//   `_fetch` helper that injects `Authorization: Bearer ...` and retries on
//   the configured status codes with exp-backoff. Endpoints without active
//   middleware keep the v0.14 emission for byte-stable output.

use crate::casing::{camel_case, pascal_case};
use crate::codegen::{
    as_object, body_type_name, has_body, path_params, prim_of, query_params, render_path,
    SchemaDefs,
};
use crate::middleware::{AuthKind, MiddlewareSpec, PaginationStyle, DEFAULT_PAGE_SIZE};
use crate::schema::{ApiEndpoint, ApiSchema, PrimType};
use std::collections::BTreeMap;

/// Back-compat entry point: no schema registry, so request bodies stay `any`
/// and no named interfaces are emitted.
pub fn generate_typescript_sdk(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    generate_typescript_sdk_with_types(endpoints, base_url, &BTreeMap::new())
}

/// Emit the TS SDK with named `export interface` definitions for every schema
/// in `defs`, and type each `Ref`-bodied endpoint's `body` arg with that name.
pub fn generate_typescript_sdk_with_types(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    defs: &SchemaDefs,
) -> String {
    let mut s = String::from("// Auto-generated by Flux API Builder — Phase 3a\n");
    emit_ts_types(&mut s, defs);
    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = pascal_case(&tag.replace('-', "_"));
        // Effective middleware for this tag = first endpoint's active spec
        // (or none). Mixed-middleware-within-a-tag is a v0.16+ concern.
        let effective = eps
            .iter()
            .find_map(|e| e.middleware.as_ref())
            .filter(|m| m.is_active())
            .cloned();

        if let Some(mw) = effective {
            emit_middleware_client(&mut s, &cn, base_url, &eps, &mw, defs);
        } else {
            emit_basic_client(&mut s, &cn, base_url, &eps, defs);
        }
    }
    s
}

fn ts_type(schema: &ApiSchema) -> &'static str {
    match prim_of(schema) {
        Some(PrimType::Integer) | Some(PrimType::Number) => "number",
        Some(PrimType::Boolean) => "boolean",
        Some(PrimType::String) | None => "string",
    }
}

/// Rich type reference: enums become string-literal unions, refs become the
/// interface name, arrays/nullables compose, inline objects fall back to `any`.
fn ts_type_ref(schema: &ApiSchema) -> String {
    match schema {
        ApiSchema::Primitive { .. } => ts_type(schema).to_string(),
        ApiSchema::Ref { name } => pascal_case(&name.replace('-', "_")),
        ApiSchema::Array { items } => format!("{}[]", ts_type_ref(items)),
        ApiSchema::Nullable { inner } => format!("{} | null", ts_type_ref(inner)),
        ApiSchema::Enum { ty, values } if *ty == PrimType::String => values
            .iter()
            .filter_map(|v| v.as_str())
            .map(|v| format!("\"{v}\""))
            .collect::<Vec<_>>()
            .join(" | "),
        ApiSchema::Enum { ty, .. } => match ty {
            PrimType::Boolean => "boolean".into(),
            PrimType::String => "string".into(),
            _ => "number".into(),
        },
        ApiSchema::OneOf { variants } => variants
            .iter()
            .map(ts_type_ref)
            .collect::<Vec<_>>()
            .join(" | "),
        ApiSchema::Object { .. } => "any".into(),
    }
}

/// Emit `export interface <Name> { ... }` for each object schema in the
/// registry (type alias for non-objects). Names are sorted (BTreeMap) for
/// deterministic output.
fn emit_ts_types(s: &mut String, defs: &SchemaDefs) {
    for (name, schema) in defs {
        let tn = pascal_case(&name.replace('-', "_"));
        match as_object(schema) {
            Some((props, required)) => {
                s.push_str(&format!("export interface {tn} {{\n"));
                for (field, fschema) in props {
                    let opt = if required.contains(field) { "" } else { "?" };
                    s.push_str(&format!("  {field}{opt}: {};\n", ts_type_ref(fschema)));
                }
                s.push_str("}\n\n");
            }
            None => {
                s.push_str(&format!("export type {tn} = {};\n\n", ts_type_ref(schema)));
            }
        }
    }
}

/// Emit one method body. `callee` is the fetch expression — `fetch` for the
/// basic client, `this._fetch` for the middleware client. Both share param
/// binding, path-template substitution, query-string building, and JSON body
/// serialization so the two clients never drift.
fn emit_ts_method(s: &mut String, ep: &ApiEndpoint, callee: &str, defs: &SchemaDefs) {
    let mn = camel_case(&ep.operation_id);
    let verb = format!("{:?}", ep.method).to_uppercase();
    let pps = path_params(ep);
    let qps = query_params(ep);
    let body = has_body(ep);

    // Signature: path params (positional, typed) → optional body → optional query.
    let mut args: Vec<String> = pps
        .iter()
        .map(|p| format!("{}: {}", camel_case(&p.name), ts_type(&p.schema)))
        .collect();
    if body {
        // Named interface when the body is a known Ref, else `any`.
        let bt = body_type_name(ep.request_body.as_ref(), defs)
            .map(|n| pascal_case(&n.replace('-', "_")))
            .unwrap_or_else(|| "any".into());
        args.push(format!("body?: {bt}"));
    }
    if !qps.is_empty() {
        args.push("query?: Record<string, string | number | boolean>".into());
    }

    // URL: substitute `{id}` → `${id}` (camelCased to match the arg name).
    let path_tmpl = render_path(&ep.path, |n| format!("${{{}}}", camel_case(n)));

    s.push_str(&format!("  async {mn}({}): Promise<any> {{\n", args.join(", ")));
    let qs = if qps.is_empty() {
        ""
    } else {
        s.push_str(
            "    const qs = query ? \"?\" + new URLSearchParams(query as Record<string, any>).toString() : \"\";\n",
        );
        "${qs}"
    };
    let init = if body {
        format!("{{ method: \"{verb}\", headers: {{ \"Content-Type\": \"application/json\" }}, body: JSON.stringify(body) }}")
    } else {
        format!("{{ method: \"{verb}\" }}")
    };
    s.push_str(&format!(
        "    const r = await {callee}(`${{this.baseUrl}}{path_tmpl}{qs}`, {init});\n    return r.json();\n  }}\n"
    ));
}

/// Shared prelude for the paginator/stream emitters: the positional path-param
/// argument list and the `${...}`-interpolated path template. Both extras take
/// the same path args as the plain method so callers don't have to rebuild a
/// URL by hand.
fn ts_path_args(ep: &ApiEndpoint) -> (Vec<String>, String) {
    let args = path_params(ep)
        .iter()
        .map(|p| format!("{}: {}", camel_case(&p.name), ts_type(&p.schema)))
        .collect();
    let tmpl = render_path(&ep.path, |n| format!("${{{}}}", camel_case(n)));
    (args, tmpl)
}

/// Emit the two auto-pagination generators for one endpoint:
/// `<m>IterPages` yields whole page objects, `<m>IterItems` flattens them into
/// individual records. Items-on-top-of-pages so the two can never disagree
/// about traversal, and callers who need page metadata (totals, cursors) still
/// have a surface that exposes it.
fn emit_ts_paginator(s: &mut String, ep: &ApiEndpoint, mw: &MiddlewareSpec) {
    let mn = camel_case(&ep.operation_id);
    let (mut args, tmpl) = ts_path_args(ep);
    let call_args: Vec<String> = path_params(ep)
        .iter()
        .map(|p| camel_case(&p.name))
        .collect();
    args.push("query?: Record<string, string | number | boolean>".into());
    let items = mw.items_key();
    let sig = args.join(", ");

    s.push_str(&format!(
        "  async *{mn}IterPages({sig}): AsyncGenerator<any, void, unknown> {{\n"
    ));
    s.push_str("    const base: Record<string, any> = { ...(query ?? {}) };\n");

    match &mw.pagination {
        PaginationStyle::Cursor { cursor_param, response_field } => {
            s.push_str("    let cursor: string | null = null;\n    while (true) {\n");
            s.push_str("      const q = { ...base };\n");
            s.push_str(&format!(
                "      if (cursor !== null) q[\"{cursor_param}\"] = cursor;\n"
            ));
            s.push_str(&ts_page_fetch(&tmpl));
            s.push_str("      yield page;\n");
            s.push_str(&format!("      const next = page[\"{response_field}\"];\n"));
            s.push_str("      if (next === undefined || next === null || next === \"\") return;\n");
            s.push_str("      cursor = String(next);\n    }\n");
        }
        PaginationStyle::Page { page_param } => {
            s.push_str("    let pageNo = 1;\n    while (true) {\n");
            s.push_str("      const q = { ...base };\n");
            s.push_str(&format!("      q[\"{page_param}\"] = pageNo;\n"));
            s.push_str(&ts_page_fetch(&tmpl));
            // An empty page is the only reliable terminator for page-number
            // pagination — there is no next-cursor to test.
            s.push_str(&format!(
                "      const items = page[\"{items}\"] ?? [];\n      if (items.length === 0) return;\n"
            ));
            s.push_str("      yield page;\n      pageNo++;\n    }\n");
        }
        PaginationStyle::Offset { offset_param, limit_param } => {
            let size = DEFAULT_PAGE_SIZE;
            s.push_str(&format!("    let offset = 0;\n    const limit = {size};\n    while (true) {{\n"));
            s.push_str("      const q = { ...base };\n");
            s.push_str(&format!(
                "      q[\"{offset_param}\"] = offset;\n      q[\"{limit_param}\"] = limit;\n"
            ));
            s.push_str(&ts_page_fetch(&tmpl));
            s.push_str(&format!(
                "      const items = page[\"{items}\"] ?? [];\n      if (items.length === 0) return;\n"
            ));
            s.push_str("      yield page;\n");
            // A short page means the server ran out — stop without paying for
            // one more round-trip that would return nothing.
            s.push_str("      if (items.length < limit) return;\n      offset += items.length;\n    }\n");
        }
        PaginationStyle::None => unreachable!("paginator emitted for non-paginated endpoint"),
    }
    s.push_str("  }\n");

    // Item-level view, delegating traversal to the page generator above.
    let mut iter_args = call_args.clone();
    iter_args.push("query".into());
    s.push_str(&format!(
        "  async *{mn}IterItems({sig}): AsyncGenerator<any, void, unknown> {{\n\
         \x20   for await (const page of this.{mn}IterPages({})) {{\n\
         \x20     for (const item of (page[\"{items}\"] ?? [])) yield item;\n\
         \x20   }}\n  }}\n",
        iter_args.join(", ")
    ));
}

/// The fetch+decode lines shared by all three pagination styles.
fn ts_page_fetch(tmpl: &str) -> String {
    format!(
        "      const qs = \"?\" + new URLSearchParams(q as Record<string, any>).toString();\n\
         \x20     const r = await this._fetch(`${{this.baseUrl}}{tmpl}${{qs}}`, {{ method: \"GET\" }});\n\
         \x20     const page = await r.json();\n"
    )
}

/// Emit an SSE consumer: `<m>Stream(...)` is an async generator that yields one
/// decoded JSON object per `data:` frame. Buffers across chunk boundaries —
/// a naive per-chunk parse drops events whenever a frame straddles two reads.
fn emit_ts_stream(s: &mut String, ep: &ApiEndpoint) {
    let mn = camel_case(&ep.operation_id);
    let (mut args, tmpl) = ts_path_args(ep);
    args.push("query?: Record<string, string | number | boolean>".into());
    let sig = args.join(", ");

    s.push_str(&format!(
        "  async *{mn}Stream({sig}): AsyncGenerator<any, void, unknown> {{\n"
    ));
    s.push_str("    const qs = query ? \"?\" + new URLSearchParams(query as Record<string, any>).toString() : \"\";\n");
    s.push_str(&format!(
        "    const r = await this._fetch(`${{this.baseUrl}}{tmpl}${{qs}}`, {{ method: \"GET\", headers: {{ \"Accept\": \"text/event-stream\" }} }});\n"
    ));
    s.push_str("    if (!r.body) return;\n");
    s.push_str("    const reader = r.body.getReader();\n");
    s.push_str("    const decoder = new TextDecoder();\n");
    s.push_str("    let buf = \"\";\n");
    s.push_str("    while (true) {\n");
    s.push_str("      const { done, value } = await reader.read();\n");
    s.push_str("      if (done) break;\n");
    s.push_str("      buf += decoder.decode(value, { stream: true });\n");
    // Frames are separated by a blank line; keep the trailing partial in `buf`.
    s.push_str("      const frames = buf.split(\"\\n\\n\");\n");
    s.push_str("      buf = frames.pop() ?? \"\";\n");
    s.push_str("      for (const frame of frames) {\n");
    s.push_str("        for (const line of frame.split(\"\\n\")) {\n");
    s.push_str("          if (!line.startsWith(\"data:\")) continue;\n");
    s.push_str("          const payload = line.slice(5).trim();\n");
    s.push_str("          if (payload === \"\" || payload === \"[DONE]\") continue;\n");
    s.push_str("          try { yield JSON.parse(payload); } catch { yield payload; }\n");
    s.push_str("        }\n      }\n    }\n  }\n");
}

fn emit_basic_client(s: &mut String, cn: &str, base_url: &str, eps: &[&ApiEndpoint], defs: &SchemaDefs) {
    s.push_str(&format!(
        "export class {cn}Client {{\n  private baseUrl: string;\n  constructor(b: string = \"{base_url}\") {{ this.baseUrl = b; }}\n"
    ));
    for ep in eps {
        emit_ts_method(s, ep, "fetch", defs);
    }
    s.push_str("}\n\n");
}

fn emit_middleware_client(
    s: &mut String,
    cn: &str,
    base_url: &str,
    eps: &[&ApiEndpoint],
    mw: &MiddlewareSpec,
    defs: &SchemaDefs,
) {
    let bearer = matches!(mw.auth, AuthKind::Bearer);
    let retry = &mw.retry;

    // Class header — optional token arg when bearer auth is on.
    s.push_str(&format!("export class {cn}Client {{\n"));
    s.push_str("  private baseUrl: string;\n");
    if bearer {
        s.push_str("  private token: string | null;\n");
    }
    if bearer {
        s.push_str(&format!(
            "  constructor(b: string = \"{base_url}\", token?: string) {{\n    this.baseUrl = b;\n    this.token = token ?? null;\n  }}\n"
        ));
    } else {
        s.push_str(&format!(
            "  constructor(b: string = \"{base_url}\") {{ this.baseUrl = b; }}\n"
        ));
    }

    // Shared _fetch with auth header + retry. Retry list and timings
    // hard-coded from the MiddlewareSpec so the emitted code has no surprises
    // at runtime.
    s.push_str("  private async _fetch(url: string, init: RequestInit): Promise<Response> {\n");
    s.push_str("    const headers: Record<string, string> = { ...(init.headers as any) };\n");
    if bearer {
        s.push_str("    if (this.token) headers[\"Authorization\"] = `Bearer ${this.token}`;\n");
    }
    if retry.is_active() {
        let max_attempts = retry.max_attempts;
        let init_ms = retry.initial_backoff_ms;
        let max_ms = retry.max_backoff_ms;
        let retry_list = retry
            .retry_on_status
            .iter()
            .map(|c| c.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!(
            "    const retryOn = new Set<number>([{retry_list}]);\n\
             \tlet attempt = 0;\n\
             \twhile (true) {{\n\
             \t  const r = await fetch(url, {{ ...init, headers }});\n\
             \t  if (!retryOn.has(r.status) || attempt >= {max_attempts} - 1) return r;\n\
             \t  const backoff = Math.min({init_ms} * Math.pow(2, attempt), {max_ms});\n\
             \t  await new Promise(res => setTimeout(res, backoff));\n\
             \t  attempt++;\n\
             \t}}\n"
        ).replace('\t', "    "));
    } else {
        s.push_str("    return fetch(url, { ...init, headers });\n");
    }
    s.push_str("  }\n");

    // Methods — route through _fetch (same param-binding as the basic client).
    for ep in eps {
        emit_ts_method(s, ep, "this._fetch", defs);
    }

    // Middleware extras. Resolved per-endpoint (falling back to the tag's
    // effective spec) so a tag that mixes a paginated list with a plain GET
    // only grows a paginator on the endpoint that actually pages.
    for ep in eps {
        let spec = ep
            .middleware
            .as_ref()
            .filter(|m| m.is_active())
            .unwrap_or(mw);
        if spec.pagination.is_active() {
            emit_ts_paginator(s, ep, spec);
        }
        if spec.streaming.is_sse() {
            emit_ts_stream(s, ep);
        }
    }
    s.push_str("}\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::{MiddlewareSpec, RetryPolicy};
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }

    fn ep_with_mw(path: &str, mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: path.into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn no_middleware_keeps_v0_14_emission() {
        // Backwards-compat: existing v0.14 callers see no behaviour change.
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_typescript_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("export class FluxUeBridgeClient"));
        assert!(!sdk.contains("_fetch"));
        assert!(!sdk.contains("Authorization"));
    }

    #[test]
    fn bearer_auth_emits_token_arg_and_header() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("private token: string | null"));
        assert!(sdk.contains("constructor(b: string = \"http://api\", token?: string)"));
        assert!(sdk.contains("Authorization"));
        assert!(sdk.contains("`Bearer ${this.token}`"));
    }

    #[test]
    fn retry_policy_emits_loop_and_backoff() {
        let eps = vec![ep_with_mw(
            "/poll",
            MiddlewareSpec::default().with_retry(RetryPolicy::standard()),
        )];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("const retryOn = new Set<number>"));
        assert!(sdk.contains("429"));
        assert!(sdk.contains("503"));
        assert!(sdk.contains("Math.pow(2, attempt)"));
        assert!(sdk.contains("setTimeout"));
    }

    #[test]
    fn middleware_methods_route_through_fetch_helper() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("this._fetch"));
        assert!(!sdk.contains("await fetch(`")); // direct fetch must not appear in methods
    }

    // ---- v0.15-B pagination + streaming ------------------------------------

    use crate::middleware::{PaginationStyle, StreamKind};

    fn cursor_mw() -> MiddlewareSpec {
        MiddlewareSpec::default().with_pagination(PaginationStyle::Cursor {
            cursor_param: "after".into(),
            response_field: "next_cursor".into(),
        })
    }

    #[test]
    fn cursor_pagination_emits_both_generators() {
        let sdk = generate_typescript_sdk(&[ep_with_mw("/things", cursor_mw())], "http://api");
        assert!(sdk.contains("async *demoEndpointIterPages("), "no page generator:\n{sdk}");
        assert!(sdk.contains("async *demoEndpointIterItems("), "no item generator:\n{sdk}");
        // Cursor is sent under the configured param and read back from the
        // configured response field.
        assert!(sdk.contains("q[\"after\"] = cursor"), "cursor param wrong:\n{sdk}");
        assert!(sdk.contains("page[\"next_cursor\"]"), "next-cursor field wrong:\n{sdk}");
        // Termination must cover all three empty-ish shapes, not just null.
        assert!(sdk.contains("next === undefined || next === null || next === \"\""));
        // Items view delegates to the page view — never a second traversal.
        assert!(sdk.contains("for await (const page of this.demoEndpointIterPages(query))"));
    }

    #[test]
    fn items_field_defaults_to_data_and_is_overridable() {
        let sdk = generate_typescript_sdk(&[ep_with_mw("/things", cursor_mw())], "http://api");
        assert!(sdk.contains("page[\"data\"] ?? []"), "default items key:\n{sdk}");

        let custom = cursor_mw().with_items_field("results");
        let sdk2 = generate_typescript_sdk(&[ep_with_mw("/things", custom)], "http://api");
        assert!(sdk2.contains("page[\"results\"] ?? []"), "override ignored:\n{sdk2}");
        assert!(!sdk2.contains("page[\"data\"]"));
    }

    #[test]
    fn page_number_pagination_terminates_on_empty_page() {
        let mw = MiddlewareSpec::default()
            .with_pagination(PaginationStyle::Page { page_param: "page".into() });
        let sdk = generate_typescript_sdk(&[ep_with_mw("/things", mw)], "http://api");
        assert!(sdk.contains("let pageNo = 1"));
        assert!(sdk.contains("q[\"page\"] = pageNo"));
        assert!(sdk.contains("if (items.length === 0) return;"));
        assert!(sdk.contains("pageNo++"));
    }

    #[test]
    fn offset_pagination_advances_and_stops_on_short_page() {
        let mw = MiddlewareSpec::default().with_pagination(PaginationStyle::Offset {
            offset_param: "offset".into(),
            limit_param: "limit".into(),
        });
        let sdk = generate_typescript_sdk(&[ep_with_mw("/things", mw)], "http://api");
        assert!(sdk.contains("const limit = 100"));
        assert!(sdk.contains("q[\"offset\"] = offset"));
        assert!(sdk.contains("q[\"limit\"] = limit"));
        // Short page ends traversal without a wasted final round-trip.
        assert!(sdk.contains("if (items.length < limit) return;"));
        assert!(sdk.contains("offset += items.length"));
    }

    #[test]
    fn sse_emits_buffering_stream_generator() {
        let mw = MiddlewareSpec::default().with_streaming(StreamKind::Sse);
        let sdk = generate_typescript_sdk(&[ep_with_mw("/events", mw)], "http://api");
        assert!(sdk.contains("async *demoEndpointStream("), "no stream method:\n{sdk}");
        assert!(sdk.contains("\"Accept\": \"text/event-stream\""));
        assert!(sdk.contains("getReader()"));
        // The buffer-across-chunks behaviour is the whole point — a per-chunk
        // parse silently drops frames that straddle a read boundary.
        assert!(sdk.contains("buf += decoder.decode(value, { stream: true })"));
        assert!(sdk.contains("buf = frames.pop() ?? \"\""));
        assert!(sdk.contains("payload === \"[DONE]\""));
    }

    #[test]
    fn websocket_streaming_does_not_emit_an_sse_reader() {
        // WebSocket surfaces belong to event_types; the REST emitter must stay
        // out of the way rather than emit a bogus SSE reader.
        let mw = MiddlewareSpec::default().with_streaming(StreamKind::WebSocket);
        let sdk = generate_typescript_sdk(&[ep_with_mw("/ws", mw)], "http://api");
        assert!(!sdk.contains("Stream("), "emitted SSE reader for WebSocket:\n{sdk}");
    }

    #[test]
    fn inactive_pagination_emits_no_paginator() {
        // Back-compat: bearer-only middleware keeps the v0.15-A emission.
        let sdk = generate_typescript_sdk(
            &[ep_with_mw("/me", MiddlewareSpec::bearer_auth())],
            "http://api",
        );
        assert!(!sdk.contains("IterPages"));
        assert!(!sdk.contains("IterItems"));
        assert!(!sdk.contains("Stream("));
    }

    #[test]
    fn paginator_threads_path_params_through_to_the_page_generator() {
        // A paginated sub-resource (/orgs/{id}/things) must take `id` on BOTH
        // generators and forward it — dropping it would silently page the
        // wrong URL.
        let mut ep = ep_with_mw("/orgs/{id}/things", cursor_mw());
        ep.parameters = vec![crate::schema::ApiParameter {
            name: "id".into(),
            location: crate::schema::ParamLocation::Path,
            required: true,
            description: String::new(),
            schema: ApiSchema::Primitive { ty: PrimType::String, format: None },
        }];
        let sdk = generate_typescript_sdk(&[ep], "http://api");
        assert!(sdk.contains("async *demoEndpointIterPages(id: string, query?"), "sig:\n{sdk}");
        assert!(sdk.contains("this.demoEndpointIterPages(id, query)"), "forwarding:\n{sdk}");
        assert!(sdk.contains("/orgs/${id}/things"), "path interpolation:\n{sdk}");
    }

    #[test]
    fn path_param_becomes_typed_arg_and_is_substituted() {
        // wickes-cms has GET /api/pages/{id}. The generated method must take an
        // `id` arg and interpolate it — never leave the literal `{id}`.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("(id: string)"), "missing typed id arg in:\n{sdk}");
        assert!(sdk.contains("/api/pages/${id}`"), "id not interpolated in:\n{sdk}");
        assert!(!sdk.contains("/api/pages/{id}"), "literal placeholder leaked:\n{sdk}");
    }

    #[test]
    fn query_param_emits_options_arg_and_querystring() {
        // GET /api/pages carries a `limit` query param.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("query?: Record<string, string | number | boolean>"));
        assert!(sdk.contains("new URLSearchParams(query as Record<string, any>)"));
        assert!(sdk.contains("${qs}`"));
    }

    #[test]
    fn body_endpoint_serializes_json_with_content_type() {
        // POST /api/pages carries a Page body.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("body?: any"));
        assert!(sdk.contains("\"Content-Type\": \"application/json\""));
        assert!(sdk.contains("body: JSON.stringify(body)"));
    }

    #[test]
    fn with_types_emits_interface_and_typed_body() {
        use crate::discover::discover_schemas;
        let g = ws(&["wickes-cms"]);
        let eps = discover_endpoints(&g);
        let sdk = generate_typescript_sdk_with_types(&eps, "http://api", &discover_schemas(&g));
        // Named interface with field types + optionality + enum union + nullable.
        assert!(sdk.contains("export interface Page {"), "missing interface:\n{sdk}");
        assert!(sdk.contains("id: string;"));
        assert!(sdk.contains("status?: \"draft\" | \"published\" | \"archived\";"), "enum union:\n{sdk}");
        assert!(sdk.contains("body?: string | null;"), "nullable field:\n{sdk}");
        // POST body arg is typed as Page, not any.
        assert!(sdk.contains("body?: Page"), "body not typed Page:\n{sdk}");
        assert!(!sdk.contains("body?: any"), "body still any in typed mode:\n{sdk}");
    }

    #[test]
    fn without_registry_no_interfaces_body_any() {
        // Back-compat: empty registry → no interfaces, body stays any.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(!sdk.contains("export interface"));
        assert!(sdk.contains("body?: any"));
    }
}
