// Go REST SDK generator.
//
// v0.14-A: idiomatic context.Context + *http.Client; one struct per tag.
// v0.15-C (rocky 2026-05-29): when any endpoint in a tag carries an active
// `MiddlewareSpec` with bearer auth, add a `Token string` field and inject
// `Authorization: Bearer ...` per request. Retry/pagination/streaming are a
// v0.15.x polish — they're tracked in the roadmap but not lowered into Go
// yet to keep the v0.15-C surface tight.

use crate::casing::pascal_case;
use crate::middleware::AuthKind;
use crate::schema::ApiEndpoint;

pub fn generate_go_sdk(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    package_name: &str,
) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by Flux API Builder — Go SDK (v0.14)\n");
    s.push_str(&format!("package {package_name}\n\n"));
    s.push_str("import (\n");
    s.push_str("\t\"context\"\n");
    s.push_str("\t\"net/http\"\n");
    s.push_str(")\n\n");

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = format!("{}Client", pascal_case(&tag.replace('-', "_")));
        let bearer = eps.iter().any(|e| {
            e.middleware
                .as_ref()
                .map(|m| matches!(m.auth, AuthKind::Bearer))
                .unwrap_or(false)
        });

        // Struct fields.
        s.push_str(&format!("type {cn} struct {{\n"));
        s.push_str("\tBaseURL string\n");
        s.push_str("\tHTTP    *http.Client\n");
        if bearer {
            s.push_str("\tToken   string\n");
        }
        s.push_str("}\n\n");

        // Constructor — the bearer variant takes a second arg.
        if bearer {
            s.push_str(&format!(
                "func New{cn}(baseURL, token string) *{cn} {{\n\
                 \tif baseURL == \"\" {{ baseURL = \"{base_url}\" }}\n\
                 \treturn &{cn}{{BaseURL: baseURL, HTTP: http.DefaultClient, Token: token}}\n\
                 }}\n\n"
            ));
        } else {
            s.push_str(&format!(
                "func New{cn}(baseURL string) *{cn} {{\n\
                 \tif baseURL == \"\" {{ baseURL = \"{base_url}\" }}\n\
                 \treturn &{cn}{{BaseURL: baseURL, HTTP: http.DefaultClient}}\n\
                 }}\n\n"
            ));
        }

        for ep in &eps {
            let method_name = pascal_case(&ep.operation_id);
            let http_verb = format!("{:?}", ep.method).to_uppercase();
            s.push_str(&format!(
                "// {summary}\n\
                 func (c *{cn}) {method_name}(ctx context.Context) (*http.Response, error) {{\n\
                 \treq, err := http.NewRequestWithContext(ctx, \"{http_verb}\", c.BaseURL+\"{path}\", nil)\n\
                 \tif err != nil {{ return nil, err }}\n",
                summary = ep.summary,
                method_name = method_name,
                http_verb = http_verb,
                path = ep.path,
            ));
            if bearer {
                s.push_str(
                    "\tif c.Token != \"\" {\n\
                     \t\treq.Header.Set(\"Authorization\", \"Bearer \"+c.Token)\n\
                     \t}\n",
                );
            }
            s.push_str("\treturn c.HTTP.Do(req)\n}\n\n");
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::MiddlewareSpec;
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: "/me".into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn go_sdk_has_package_and_imports() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:8080", "wickescms");
        assert!(sdk.starts_with("// Auto-generated"));
        assert!(sdk.contains("package wickescms"));
        assert!(sdk.contains("\"context\""));
        assert!(sdk.contains("\"net/http\""));
    }

    #[test]
    fn go_sdk_emits_client_struct_per_tag() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:9989", "uebridge");
        assert!(sdk.contains("type FluxUeBridgeClient struct"));
        assert!(sdk.contains("BaseURL string"));
        assert!(sdk.contains("HTTP    *http.Client"));
        assert!(sdk.contains("func NewFluxUeBridgeClient(baseURL string) *FluxUeBridgeClient"));
        assert!(!sdk.contains("Token   string"));
    }

    #[test]
    fn go_sdk_methods_use_context_and_method_verbs() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "http://localhost:8080", "wickescms");
        assert!(sdk.contains("func (c *WickesCmsClient) WickesCms1(ctx context.Context)"));
        assert!(sdk.contains("\"POST\""));
        assert!(sdk.contains("http.NewRequestWithContext"));
    }

    #[test]
    fn go_sdk_default_base_url_fallback() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_go_sdk(&eps, "https://example.test", "wickescms");
        assert!(sdk.contains("if baseURL == \"\" { baseURL = \"https://example.test\" }"));
    }

    #[test]
    fn go_sdk_bearer_middleware_adds_token_field_and_header() {
        let eps = vec![ep_with_mw(MiddlewareSpec::bearer_auth())];
        let sdk = generate_go_sdk(&eps, "https://api", "demo");
        assert!(sdk.contains("Token   string"));
        assert!(sdk.contains("func NewDemoClient(baseURL, token string)"));
        assert!(sdk.contains("Token: token"));
        assert!(sdk.contains("req.Header.Set(\"Authorization\", \"Bearer \"+c.Token)"));
    }
}
