// TypeScript REST SDK generator.
//
// v0.14: bare fetch() + JSON parse.
// v0.15-B (rocky 2026-05-29): when any endpoint in a tag carries an active
//   MiddlewareSpec (bearer auth, retry, pagination, streaming), emit a
//   middleware-aware client: optional `token` constructor arg + a private
//   `_fetch` helper that injects `Authorization: Bearer ...` and retries on
//   the configured status codes with exp-backoff. Endpoints without active
//   middleware keep the v0.14 emission for byte-stable output.

use crate::casing::{camel_case, pascal_case};
use crate::codegen::{
    as_object, body_type_name, has_body, path_params, prim_of, query_params, render_path,
    SchemaDefs,
};
use crate::middleware::{AuthKind, MiddlewareSpec};
use crate::schema::{ApiEndpoint, ApiSchema, PrimType};
use std::collections::BTreeMap;

/// Back-compat entry point: no schema registry, so request bodies stay `any`
/// and no named interfaces are emitted.
pub fn generate_typescript_sdk(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    generate_typescript_sdk_with_types(endpoints, base_url, &BTreeMap::new())
}

/// Emit the TS SDK with named `export interface` definitions for every schema
/// in `defs`, and type each `Ref`-bodied endpoint's `body` arg with that name.
pub fn generate_typescript_sdk_with_types(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    defs: &SchemaDefs,
) -> String {
    let mut s = String::from("// Auto-generated by Flux API Builder — Phase 3a\n");
    emit_ts_types(&mut s, defs);
    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = pascal_case(&tag.replace('-', "_"));
        // Effective middleware for this tag = first endpoint's active spec
        // (or none). Mixed-middleware-within-a-tag is a v0.16+ concern.
        let effective = eps
            .iter()
            .find_map(|e| e.middleware.as_ref())
            .filter(|m| m.is_active())
            .cloned();

        if let Some(mw) = effective {
            emit_middleware_client(&mut s, &cn, base_url, &eps, &mw, defs);
        } else {
            emit_basic_client(&mut s, &cn, base_url, &eps, defs);
        }
    }
    s
}

fn ts_type(schema: &ApiSchema) -> &'static str {
    match prim_of(schema) {
        Some(PrimType::Integer) | Some(PrimType::Number) => "number",
        Some(PrimType::Boolean) => "boolean",
        Some(PrimType::String) | None => "string",
    }
}

/// Rich type reference: enums become string-literal unions, refs become the
/// interface name, arrays/nullables compose, inline objects fall back to `any`.
fn ts_type_ref(schema: &ApiSchema) -> String {
    match schema {
        ApiSchema::Primitive { .. } => ts_type(schema).to_string(),
        ApiSchema::Ref { name } => pascal_case(&name.replace('-', "_")),
        ApiSchema::Array { items } => format!("{}[]", ts_type_ref(items)),
        ApiSchema::Nullable { inner } => format!("{} | null", ts_type_ref(inner)),
        ApiSchema::Enum { ty, values } if *ty == PrimType::String => values
            .iter()
            .filter_map(|v| v.as_str())
            .map(|v| format!("\"{v}\""))
            .collect::<Vec<_>>()
            .join(" | "),
        ApiSchema::Enum { ty, .. } => match ty {
            PrimType::Boolean => "boolean".into(),
            PrimType::String => "string".into(),
            _ => "number".into(),
        },
        ApiSchema::OneOf { variants } => variants
            .iter()
            .map(ts_type_ref)
            .collect::<Vec<_>>()
            .join(" | "),
        ApiSchema::Object { .. } => "any".into(),
    }
}

/// Emit `export interface <Name> { ... }` for each object schema in the
/// registry (type alias for non-objects). Names are sorted (BTreeMap) for
/// deterministic output.
fn emit_ts_types(s: &mut String, defs: &SchemaDefs) {
    for (name, schema) in defs {
        let tn = pascal_case(&name.replace('-', "_"));
        match as_object(schema) {
            Some((props, required)) => {
                s.push_str(&format!("export interface {tn} {{\n"));
                for (field, fschema) in props {
                    let opt = if required.contains(field) { "" } else { "?" };
                    s.push_str(&format!("  {field}{opt}: {};\n", ts_type_ref(fschema)));
                }
                s.push_str("}\n\n");
            }
            None => {
                s.push_str(&format!("export type {tn} = {};\n\n", ts_type_ref(schema)));
            }
        }
    }
}

/// Emit one method body. `callee` is the fetch expression — `fetch` for the
/// basic client, `this._fetch` for the middleware client. Both share param
/// binding, path-template substitution, query-string building, and JSON body
/// serialization so the two clients never drift.
fn emit_ts_method(s: &mut String, ep: &ApiEndpoint, callee: &str, defs: &SchemaDefs) {
    let mn = camel_case(&ep.operation_id);
    let verb = format!("{:?}", ep.method).to_uppercase();
    let pps = path_params(ep);
    let qps = query_params(ep);
    let body = has_body(ep);

    // Signature: path params (positional, typed) → optional body → optional query.
    let mut args: Vec<String> = pps
        .iter()
        .map(|p| format!("{}: {}", camel_case(&p.name), ts_type(&p.schema)))
        .collect();
    if body {
        // Named interface when the body is a known Ref, else `any`.
        let bt = body_type_name(ep.request_body.as_ref(), defs)
            .map(|n| pascal_case(&n.replace('-', "_")))
            .unwrap_or_else(|| "any".into());
        args.push(format!("body?: {bt}"));
    }
    if !qps.is_empty() {
        args.push("query?: Record<string, string | number | boolean>".into());
    }

    // URL: substitute `{id}` → `${id}` (camelCased to match the arg name).
    let path_tmpl = render_path(&ep.path, |n| format!("${{{}}}", camel_case(n)));

    s.push_str(&format!("  async {mn}({}): Promise<any> {{\n", args.join(", ")));
    let qs = if qps.is_empty() {
        ""
    } else {
        s.push_str(
            "    const qs = query ? \"?\" + new URLSearchParams(query as Record<string, any>).toString() : \"\";\n",
        );
        "${qs}"
    };
    let init = if body {
        format!("{{ method: \"{verb}\", headers: {{ \"Content-Type\": \"application/json\" }}, body: JSON.stringify(body) }}")
    } else {
        format!("{{ method: \"{verb}\" }}")
    };
    s.push_str(&format!(
        "    const r = await {callee}(`${{this.baseUrl}}{path_tmpl}{qs}`, {init});\n    return r.json();\n  }}\n"
    ));
}

fn emit_basic_client(s: &mut String, cn: &str, base_url: &str, eps: &[&ApiEndpoint], defs: &SchemaDefs) {
    s.push_str(&format!(
        "export class {cn}Client {{\n  private baseUrl: string;\n  constructor(b: string = \"{base_url}\") {{ this.baseUrl = b; }}\n"
    ));
    for ep in eps {
        emit_ts_method(s, ep, "fetch", defs);
    }
    s.push_str("}\n\n");
}

fn emit_middleware_client(
    s: &mut String,
    cn: &str,
    base_url: &str,
    eps: &[&ApiEndpoint],
    mw: &MiddlewareSpec,
    defs: &SchemaDefs,
) {
    let bearer = matches!(mw.auth, AuthKind::Bearer);
    let retry = &mw.retry;

    // Class header — optional token arg when bearer auth is on.
    s.push_str(&format!("export class {cn}Client {{\n"));
    s.push_str("  private baseUrl: string;\n");
    if bearer {
        s.push_str("  private token: string | null;\n");
    }
    if bearer {
        s.push_str(&format!(
            "  constructor(b: string = \"{base_url}\", token?: string) {{\n    this.baseUrl = b;\n    this.token = token ?? null;\n  }}\n"
        ));
    } else {
        s.push_str(&format!(
            "  constructor(b: string = \"{base_url}\") {{ this.baseUrl = b; }}\n"
        ));
    }

    // Shared _fetch with auth header + retry. Retry list and timings
    // hard-coded from the MiddlewareSpec so the emitted code has no surprises
    // at runtime.
    s.push_str("  private async _fetch(url: string, init: RequestInit): Promise<Response> {\n");
    s.push_str("    const headers: Record<string, string> = { ...(init.headers as any) };\n");
    if bearer {
        s.push_str("    if (this.token) headers[\"Authorization\"] = `Bearer ${this.token}`;\n");
    }
    if retry.is_active() {
        let max_attempts = retry.max_attempts;
        let init_ms = retry.initial_backoff_ms;
        let max_ms = retry.max_backoff_ms;
        let retry_list = retry
            .retry_on_status
            .iter()
            .map(|c| c.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!(
            "    const retryOn = new Set<number>([{retry_list}]);\n\
             \tlet attempt = 0;\n\
             \twhile (true) {{\n\
             \t  const r = await fetch(url, {{ ...init, headers }});\n\
             \t  if (!retryOn.has(r.status) || attempt >= {max_attempts} - 1) return r;\n\
             \t  const backoff = Math.min({init_ms} * Math.pow(2, attempt), {max_ms});\n\
             \t  await new Promise(res => setTimeout(res, backoff));\n\
             \t  attempt++;\n\
             \t}}\n"
        ).replace('\t', "    "));
    } else {
        s.push_str("    return fetch(url, { ...init, headers });\n");
    }
    s.push_str("  }\n");

    // Methods — route through _fetch (same param-binding as the basic client).
    for ep in eps {
        emit_ts_method(s, ep, "this._fetch", defs);
    }
    s.push_str("}\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::{MiddlewareSpec, RetryPolicy};
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }

    fn ep_with_mw(path: &str, mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: path.into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    #[test]
    fn no_middleware_keeps_v0_14_emission() {
        // Backwards-compat: existing v0.14 callers see no behaviour change.
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_typescript_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("export class FluxUeBridgeClient"));
        assert!(!sdk.contains("_fetch"));
        assert!(!sdk.contains("Authorization"));
    }

    #[test]
    fn bearer_auth_emits_token_arg_and_header() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("private token: string | null"));
        assert!(sdk.contains("constructor(b: string = \"http://api\", token?: string)"));
        assert!(sdk.contains("Authorization"));
        assert!(sdk.contains("`Bearer ${this.token}`"));
    }

    #[test]
    fn retry_policy_emits_loop_and_backoff() {
        let eps = vec![ep_with_mw(
            "/poll",
            MiddlewareSpec::default().with_retry(RetryPolicy::standard()),
        )];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("const retryOn = new Set<number>"));
        assert!(sdk.contains("429"));
        assert!(sdk.contains("503"));
        assert!(sdk.contains("Math.pow(2, attempt)"));
        assert!(sdk.contains("setTimeout"));
    }

    #[test]
    fn middleware_methods_route_through_fetch_helper() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("this._fetch"));
        assert!(!sdk.contains("await fetch(`")); // direct fetch must not appear in methods
    }

    #[test]
    fn path_param_becomes_typed_arg_and_is_substituted() {
        // wickes-cms has GET /api/pages/{id}. The generated method must take an
        // `id` arg and interpolate it — never leave the literal `{id}`.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("(id: string)"), "missing typed id arg in:\n{sdk}");
        assert!(sdk.contains("/api/pages/${id}`"), "id not interpolated in:\n{sdk}");
        assert!(!sdk.contains("/api/pages/{id}"), "literal placeholder leaked:\n{sdk}");
    }

    #[test]
    fn query_param_emits_options_arg_and_querystring() {
        // GET /api/pages carries a `limit` query param.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("query?: Record<string, string | number | boolean>"));
        assert!(sdk.contains("new URLSearchParams(query as Record<string, any>)"));
        assert!(sdk.contains("${qs}`"));
    }

    #[test]
    fn body_endpoint_serializes_json_with_content_type() {
        // POST /api/pages carries a Page body.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(sdk.contains("body?: any"));
        assert!(sdk.contains("\"Content-Type\": \"application/json\""));
        assert!(sdk.contains("body: JSON.stringify(body)"));
    }

    #[test]
    fn with_types_emits_interface_and_typed_body() {
        use crate::discover::discover_schemas;
        let g = ws(&["wickes-cms"]);
        let eps = discover_endpoints(&g);
        let sdk = generate_typescript_sdk_with_types(&eps, "http://api", &discover_schemas(&g));
        // Named interface with field types + optionality + enum union + nullable.
        assert!(sdk.contains("export interface Page {"), "missing interface:\n{sdk}");
        assert!(sdk.contains("id: string;"));
        assert!(sdk.contains("status?: \"draft\" | \"published\" | \"archived\";"), "enum union:\n{sdk}");
        assert!(sdk.contains("body?: string | null;"), "nullable field:\n{sdk}");
        // POST body arg is typed as Page, not any.
        assert!(sdk.contains("body?: Page"), "body not typed Page:\n{sdk}");
        assert!(!sdk.contains("body?: any"), "body still any in typed mode:\n{sdk}");
    }

    #[test]
    fn without_registry_no_interfaces_body_any() {
        // Back-compat: empty registry → no interfaces, body stays any.
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_typescript_sdk(&eps, "http://api");
        assert!(!sdk.contains("export interface"));
        assert!(sdk.contains("body?: any"));
    }
}
