// Python REST SDK generator.
//
// v0.14: bare httpx.
// v0.15-B (rocky 2026-05-29): when an endpoint carries an active
// MiddlewareSpec we emit a richer client: optional `token=` constructor arg
// for bearer auth + an internal `_request` helper that injects the
// `Authorization` header and retries with exp-backoff on the configured
// status codes. Endpoints without active middleware keep the v0.14 emission.

use crate::casing::{pascal_case, snake_case};
use crate::codegen::{
    as_object, body_type_name, has_body, path_params, prim_of, query_params, render_path,
    SchemaDefs,
};
use crate::middleware::{AuthKind, MiddlewareSpec, PaginationStyle, DEFAULT_PAGE_SIZE};
use crate::schema::{ApiEndpoint, ApiSchema, PrimType};
use std::collections::BTreeMap;

/// Back-compat entry point: no schema registry, so bodies are untyped (`body=None`)
/// and no `TypedDict`s are emitted.
pub fn generate_python_sdk(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    generate_python_sdk_with_types(endpoints, base_url, &BTreeMap::new())
}

/// Emit the Python SDK with a `TypedDict` per registry schema, and annotate each
/// `Ref`-bodied endpoint's `body` param with that name.
pub fn generate_python_sdk_with_types(
    endpoints: &[ApiEndpoint],
    base_url: &str,
    defs: &SchemaDefs,
) -> String {
    let mut s = String::from("# Auto-generated by Flux API Builder — Phase 3a\nimport httpx\n");
    // `time`/`json` are only used by the retry and SSE paths; emit
    // unconditionally so the file parses cleanly when those are toggled in and
    // out across regenerations.
    s.push_str("import time\n");
    s.push_str("import json\n");
    if !defs.is_empty() {
        s.push_str("from typing import List, Optional, TypedDict\n");
    }
    s.push_str("\n");
    emit_py_types(&mut s, defs);

    let tags: Vec<String> = endpoints
        .iter()
        .flat_map(|e| e.tags.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    for tag in &tags {
        let eps: Vec<_> = endpoints.iter().filter(|e| e.tags.contains(tag)).collect();
        if eps.is_empty() {
            continue;
        }
        let cn = pascal_case(&tag.replace('-', "_"));
        let effective = eps
            .iter()
            .find_map(|e| e.middleware.as_ref())
            .filter(|m| m.is_active())
            .cloned();

        if let Some(mw) = effective {
            emit_middleware_client(&mut s, &cn, base_url, &eps, &mw, defs);
        } else {
            emit_basic_client(&mut s, &cn, base_url, &eps, defs);
        }
    }
    s
}

fn py_type(schema: &ApiSchema) -> &'static str {
    match prim_of(schema) {
        Some(PrimType::Integer) => "int",
        Some(PrimType::Number) => "float",
        Some(PrimType::Boolean) => "bool",
        Some(PrimType::String) | None => "str",
    }
}

/// Rich annotation: refs become the TypedDict name, arrays become `List[..]`,
/// nullables `Optional[..]`, inline objects `dict`.
fn py_type_ref(schema: &ApiSchema) -> String {
    match schema {
        ApiSchema::Primitive { .. } | ApiSchema::Enum { .. } => py_type(schema).to_string(),
        ApiSchema::Ref { name } => pascal_case(&name.replace('-', "_")),
        ApiSchema::Array { items } => format!("List[{}]", py_type_ref(items)),
        ApiSchema::Nullable { inner } => format!("Optional[{}]", py_type_ref(inner)),
        ApiSchema::Object { .. } => "dict".into(),
        ApiSchema::OneOf { .. } => "object".into(),
    }
}

/// Emit a `TypedDict` per object schema (type alias for non-objects).
fn emit_py_types(s: &mut String, defs: &SchemaDefs) {
    for (name, schema) in defs {
        let tn = pascal_case(&name.replace('-', "_"));
        match as_object(schema) {
            Some((props, required)) => {
                s.push_str(&format!("class {tn}(TypedDict):\n"));
                if props.is_empty() {
                    s.push_str("    pass\n");
                }
                for (field, fschema) in props {
                    let ty = py_type_ref(fschema);
                    let ann = if required.contains(field) { ty } else { format!("Optional[{ty}]") };
                    s.push_str(&format!("    {field}: {ann}\n"));
                }
                s.push_str("\n\n");
            }
            None => {
                s.push_str(&format!("{tn} = {}\n\n\n", py_type_ref(schema)));
            }
        }
    }
}

/// Build the `(self, <path args>, [body=None], [params=None])` signature and
/// the `f"<path>"` template + trailing kwargs (`, json=body`, `, params=params`)
/// shared by the basic and middleware method emitters. `defs` types the body
/// param when it's a known `Ref`.
fn py_sig_and_call(ep: &ApiEndpoint, defs: &SchemaDefs) -> (String, String, String) {
    let mut args: Vec<String> = vec!["self".into()];
    for p in path_params(ep) {
        args.push(format!("{}: {}", snake_case(&p.name), py_type(&p.schema)));
    }
    let body = has_body(ep);
    let qps = query_params(ep);
    if body {
        match body_type_name(ep.request_body.as_ref(), defs) {
            Some(n) => args.push(format!("body: {} = None", pascal_case(&n.replace('-', "_")))),
            None => args.push("body=None".into()),
        }
    }
    if !qps.is_empty() {
        args.push("params=None".into());
    }
    let tmpl = render_path(&ep.path, |n| format!("{{{}}}", snake_case(n)));
    let mut kwargs = String::new();
    if !qps.is_empty() {
        kwargs.push_str(", params=params");
    }
    if body {
        kwargs.push_str(", json=body");
    }
    (args.join(", "), tmpl, kwargs)
}

/// Positional path-param args (`self, org_id: str`) plus the f-string path
/// template, shared by the paginator and stream emitters so both take the same
/// arguments as the plain method.
fn py_path_args(ep: &ApiEndpoint) -> (Vec<String>, Vec<String>, String) {
    let mut args: Vec<String> = vec!["self".into()];
    let mut names: Vec<String> = vec![];
    for p in path_params(ep) {
        let n = snake_case(&p.name);
        args.push(format!("{n}: {}", py_type(&p.schema)));
        names.push(n);
    }
    let tmpl = render_path(&ep.path, |n| format!("{{{}}}", snake_case(n)));
    (args, names, tmpl)
}

/// Emit `<m>_iter_pages` (yields whole page dicts) and `<m>_iter_items`
/// (flattens them). Items delegates to pages so the two can never disagree
/// about traversal.
fn emit_py_paginator(s: &mut String, ep: &ApiEndpoint, mw: &MiddlewareSpec) {
    let mn = snake_case(&ep.operation_id);
    let (mut args, names, tmpl) = py_path_args(ep);
    args.push("params=None".into());
    let sig = args.join(", ");
    let items = mw.items_key();

    s.push_str(&format!("    def {mn}_iter_pages({sig}):\n"));
    s.push_str("        base = dict(params or {})\n");

    let fetch = format!(
        "            page = self._request(\"GET\", f\"{tmpl}\", params=q).json()\n"
    );

    match &mw.pagination {
        PaginationStyle::Cursor { cursor_param, response_field } => {
            s.push_str("        cursor = None\n        while True:\n");
            s.push_str("            q = dict(base)\n");
            s.push_str(&format!(
                "            if cursor is not None:\n                q[\"{cursor_param}\"] = cursor\n"
            ));
            s.push_str(&fetch);
            s.push_str("            yield page\n");
            s.push_str(&format!("            nxt = page.get(\"{response_field}\")\n"));
            s.push_str("            if nxt is None or nxt == \"\":\n                return\n");
            s.push_str("            cursor = str(nxt)\n");
        }
        PaginationStyle::Page { page_param } => {
            s.push_str("        page_no = 1\n        while True:\n");
            s.push_str("            q = dict(base)\n");
            s.push_str(&format!("            q[\"{page_param}\"] = page_no\n"));
            s.push_str(&fetch);
            // No next-cursor to test, so an empty page is the terminator.
            s.push_str(&format!("            items = page.get(\"{items}\") or []\n"));
            s.push_str("            if not items:\n                return\n");
            s.push_str("            yield page\n            page_no += 1\n");
        }
        PaginationStyle::Offset { offset_param, limit_param } => {
            s.push_str(&format!(
                "        offset = 0\n        limit = {DEFAULT_PAGE_SIZE}\n        while True:\n"
            ));
            s.push_str("            q = dict(base)\n");
            s.push_str(&format!(
                "            q[\"{offset_param}\"] = offset\n            q[\"{limit_param}\"] = limit\n"
            ));
            s.push_str(&fetch);
            s.push_str(&format!("            items = page.get(\"{items}\") or []\n"));
            s.push_str("            if not items:\n                return\n");
            s.push_str("            yield page\n");
            // A short page means the server ran out — stop without paying for
            // one more round-trip that returns nothing.
            s.push_str("            if len(items) < limit:\n                return\n");
            s.push_str("            offset += len(items)\n");
        }
        PaginationStyle::None => unreachable!("paginator emitted for non-paginated endpoint"),
    }
    s.push_str("\n");

    let mut fwd = names.clone();
    fwd.push("params".into());
    s.push_str(&format!(
        "    def {mn}_iter_items({sig}):\n\
         \x20       for page in self.{mn}_iter_pages({}):\n\
         \x20           for item in (page.get(\"{items}\") or []):\n\
         \x20               yield item\n\n",
        fwd.join(", ")
    ));
}

/// Emit an SSE consumer. httpx's `iter_lines()` already reassembles lines
/// across chunk boundaries, so unlike the TS reader this needs no manual
/// buffering — but it does need its own header dict, because `_request`
/// buffers the whole body and would defeat streaming.
fn emit_py_stream(s: &mut String, ep: &ApiEndpoint, bearer: bool) {
    let mn = snake_case(&ep.operation_id);
    let (mut args, _names, tmpl) = py_path_args(ep);
    args.push("params=None".into());
    let sig = args.join(", ");

    s.push_str(&format!("    def {mn}_stream({sig}):\n"));
    s.push_str("        headers = {\"Accept\": \"text/event-stream\"}\n");
    if bearer {
        s.push_str("        if self.token:\n            headers[\"Authorization\"] = f\"Bearer {self.token}\"\n");
    }
    s.push_str(&format!(
        "        with self.c.stream(\"GET\", f\"{tmpl}\", params=params, headers=headers) as r:\n"
    ));
    s.push_str("            for line in r.iter_lines():\n");
    s.push_str("                if not line.startswith(\"data:\"):\n                    continue\n");
    s.push_str("                payload = line[5:].strip()\n");
    s.push_str("                if payload == \"\" or payload == \"[DONE]\":\n                    continue\n");
    s.push_str("                try:\n                    yield json.loads(payload)\n");
    s.push_str("                except ValueError:\n                    yield payload\n\n");
}

fn emit_basic_client(s: &mut String, cn: &str, base_url: &str, eps: &[&ApiEndpoint], defs: &SchemaDefs) {
    s.push_str(&format!(
        "class {cn}Client:\n    def __init__(self, base_url: str = \"{base_url}\"):\n        self.c = httpx.Client(base_url=base_url)\n\n"
    ));
    for ep in eps {
        let (sig, tmpl, kwargs) = py_sig_and_call(ep, defs);
        s.push_str(&format!(
            "    def {}({sig}):\n        return self.c.{}(f\"{tmpl}\"{kwargs}).json()\n\n",
            snake_case(&ep.operation_id),
            format!("{:?}", ep.method).to_lowercase(),
        ));
    }
}

fn emit_middleware_client(
    s: &mut String,
    cn: &str,
    base_url: &str,
    eps: &[&ApiEndpoint],
    mw: &MiddlewareSpec,
    defs: &SchemaDefs,
) {
    let bearer = matches!(mw.auth, AuthKind::Bearer);
    let retry = &mw.retry;

    s.push_str(&format!("class {cn}Client:\n"));
    if bearer {
        s.push_str(&format!(
            "    def __init__(self, base_url: str = \"{base_url}\", token: str | None = None):\n        self.c = httpx.Client(base_url=base_url)\n        self.token = token\n\n"
        ));
    } else {
        s.push_str(&format!(
            "    def __init__(self, base_url: str = \"{base_url}\"):\n        self.c = httpx.Client(base_url=base_url)\n\n"
        ));
    }

    s.push_str("    def _request(self, method: str, path: str, params=None, json=None):\n");
    s.push_str("        headers = {}\n");
    if bearer {
        s.push_str("        if self.token:\n            headers[\"Authorization\"] = f\"Bearer {self.token}\"\n");
    }
    if retry.is_active() {
        let max_attempts = retry.max_attempts;
        let init_ms = retry.initial_backoff_ms;
        let max_ms = retry.max_backoff_ms;
        let retry_list = retry
            .retry_on_status
            .iter()
            .map(|c| c.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!(
            "        retry_on = {{{retry_list}}}\n\
             \tattempt = 0\n\
             \twhile True:\n\
             \t    r = self.c.request(method, path, headers=headers, params=params, json=json)\n\
             \t    if r.status_code not in retry_on or attempt >= {max_attempts} - 1:\n\
             \t        return r\n\
             \t    backoff = min({init_ms} * (2 ** attempt), {max_ms}) / 1000.0\n\
             \t    time.sleep(backoff)\n\
             \t    attempt += 1\n"
        ).replace('\t', "        "));
    } else {
        s.push_str("        return self.c.request(method, path, headers=headers, params=params, json=json)\n");
    }
    s.push_str("\n");

    for ep in eps {
        let mn = snake_case(&ep.operation_id);
        let verb = format!("{:?}", ep.method).to_uppercase();
        let (sig, tmpl, kwargs) = py_sig_and_call(ep, defs);
        s.push_str(&format!(
            "    def {mn}({sig}):\n        return self._request(\"{verb}\", f\"{tmpl}\"{kwargs}).json()\n\n"
        ));
    }

    // Middleware extras, resolved per-endpoint (falling back to the tag's
    // effective spec) so only the endpoints that actually page or stream grow
    // the extra surface.
    for ep in eps {
        let spec = ep
            .middleware
            .as_ref()
            .filter(|m| m.is_active())
            .unwrap_or(mw);
        if spec.pagination.is_active() {
            emit_py_paginator(s, ep, spec);
        }
        if spec.streaming.is_sse() {
            emit_py_stream(s, ep, bearer);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discover::discover_endpoints;
    use crate::middleware::{MiddlewareSpec, RetryPolicy};
    use crate::schema::{ApiEndpoint, ApiResponse, HttpMethod};

    fn ci(name: &str) -> flux_graph::CrateInfo {
        flux_graph::CrateInfo {
            name: name.into(),
            path: std::path::PathBuf::from("/tmp"),
            dependencies: vec![],
            edition: "2021".into(),
            crate_type: flux_graph::CrateType::Lib,
            features: vec![],
        }
    }
    fn ws(names: &[&str]) -> flux_graph::WorkspaceGraph {
        flux_graph::WorkspaceGraph {
            root: std::path::PathBuf::from("/tmp"),
            crates: names.iter().map(|n| ci(n)).collect(),
            batches: vec![],
        }
    }
    fn ep_with_mw(path: &str, mw: MiddlewareSpec) -> ApiEndpoint {
        ApiEndpoint {
            crate_name: "demo".into(),
            method: HttpMethod::GET,
            path: path.into(),
            operation_id: "demo_endpoint".into(),
            summary: "demo".into(),
            parameters: vec![],
            request_body: None,
            responses: vec![ApiResponse { status: 200, description: "".into(), schema: None }],
            tags: vec!["demo".into()],
            middleware: Some(mw),
        }
    }

    // ---- v0.15-B pagination + streaming ------------------------------------

    use crate::middleware::{PaginationStyle, StreamKind};

    fn cursor_mw() -> MiddlewareSpec {
        MiddlewareSpec::default().with_pagination(PaginationStyle::Cursor {
            cursor_param: "after".into(),
            response_field: "next_cursor".into(),
        })
    }

    #[test]
    fn cursor_pagination_emits_both_generators() {
        let sdk = generate_python_sdk(&[ep_with_mw("/things", cursor_mw())], "http://api");
        assert!(sdk.contains("def demo_endpoint_iter_pages(self, params=None):"), "{sdk}");
        assert!(sdk.contains("def demo_endpoint_iter_items(self, params=None):"), "{sdk}");
        assert!(sdk.contains("q[\"after\"] = cursor"));
        assert!(sdk.contains("nxt = page.get(\"next_cursor\")"));
        assert!(sdk.contains("if nxt is None or nxt == \"\":"));
        // Items view walks the page generator rather than re-fetching.
        assert!(sdk.contains("for page in self.demo_endpoint_iter_pages(params):"));
    }

    #[test]
    fn items_field_defaults_to_data_and_is_overridable() {
        let sdk = generate_python_sdk(&[ep_with_mw("/things", cursor_mw())], "http://api");
        assert!(sdk.contains("page.get(\"data\") or []"), "{sdk}");
        let sdk2 = generate_python_sdk(
            &[ep_with_mw("/things", cursor_mw().with_items_field("results"))],
            "http://api",
        );
        assert!(sdk2.contains("page.get(\"results\") or []"), "{sdk2}");
        assert!(!sdk2.contains("page.get(\"data\")"));
    }

    #[test]
    fn page_and_offset_styles_emit_their_terminators() {
        let paged = generate_python_sdk(
            &[ep_with_mw(
                "/p",
                MiddlewareSpec::default()
                    .with_pagination(PaginationStyle::Page { page_param: "page".into() }),
            )],
            "http://api",
        );
        assert!(paged.contains("page_no = 1"));
        assert!(paged.contains("q[\"page\"] = page_no"));
        assert!(paged.contains("page_no += 1"));

        let off = generate_python_sdk(
            &[ep_with_mw(
                "/o",
                MiddlewareSpec::default().with_pagination(PaginationStyle::Offset {
                    offset_param: "offset".into(),
                    limit_param: "limit".into(),
                }),
            )],
            "http://api",
        );
        assert!(off.contains("limit = 100"));
        assert!(off.contains("if len(items) < limit:"));
        assert!(off.contains("offset += len(items)"));
    }

    #[test]
    fn sse_emits_streaming_context_manager_not_buffered_request() {
        let mw = MiddlewareSpec::default().with_streaming(StreamKind::Sse);
        let sdk = generate_python_sdk(&[ep_with_mw("/events", mw)], "http://api");
        assert!(sdk.contains("def demo_endpoint_stream(self, params=None):"), "{sdk}");
        // Must use httpx's streaming context manager — routing through
        // `_request` would buffer the whole body and never yield incrementally.
        assert!(sdk.contains("with self.c.stream(\"GET\""), "{sdk}");
        assert!(sdk.contains("for line in r.iter_lines():"));
        assert!(sdk.contains("\"Accept\": \"text/event-stream\""));
        assert!(sdk.contains("[DONE]"));
        assert!(sdk.contains("import json"));
    }

    #[test]
    fn sse_stream_attaches_bearer_token_when_auth_is_on() {
        // The stream path builds its own headers, so it has to re-apply auth
        // itself — otherwise streaming endpoints silently go out unauthenticated.
        let mw = MiddlewareSpec::bearer_auth().with_streaming(StreamKind::Sse);
        let sdk = generate_python_sdk(&[ep_with_mw("/events", mw)], "http://api");
        assert!(
            sdk.contains("headers[\"Authorization\"] = f\"Bearer {self.token}\""),
            "stream dropped auth:\n{sdk}"
        );
    }

    #[test]
    fn inactive_pagination_emits_no_paginator() {
        let sdk = generate_python_sdk(
            &[ep_with_mw("/me", MiddlewareSpec::bearer_auth())],
            "http://api",
        );
        assert!(!sdk.contains("_iter_pages"));
        assert!(!sdk.contains("_stream("));
    }

    #[test]
    fn no_middleware_keeps_v0_14_emission() {
        let eps = discover_endpoints(&ws(&["flux-ue-bridge"]));
        let sdk = generate_python_sdk(&eps, "http://localhost:9989");
        assert!(sdk.contains("class FluxUeBridgeClient:"));
        assert!(!sdk.contains("_request"));
        assert!(!sdk.contains("Authorization"));
    }

    #[test]
    fn bearer_auth_emits_token_arg_and_header() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("token: str | None = None"));
        assert!(sdk.contains("Authorization"));
        assert!(sdk.contains("f\"Bearer {self.token}\""));
    }

    #[test]
    fn retry_policy_emits_loop_and_sleep() {
        let eps = vec![ep_with_mw(
            "/poll",
            MiddlewareSpec::default().with_retry(RetryPolicy::standard()),
        )];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("retry_on = {"));
        assert!(sdk.contains("429"));
        assert!(sdk.contains("503"));
        assert!(sdk.contains("time.sleep"));
        assert!(sdk.contains("2 ** attempt"));
    }

    #[test]
    fn middleware_methods_route_through_request_helper() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("self._request"));
        assert!(!sdk.contains("self.c.get(\"/me\")"));
    }

    #[test]
    fn path_param_is_typed_arg_and_fstring_substituted() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("id: str"), "missing typed id arg:\n{sdk}");
        // The path is an f-string so `{id}` binds the arg at call time. The
        // non-f form (a plain httpx call on the literal placeholder) must not
        // appear — that would hit the URL `/api/pages/{id}` verbatim.
        assert!(sdk.contains("f\"/api/pages/{id}\""), "id not f-string substituted:\n{sdk}");
        assert!(!sdk.contains("self.c.get(\"/api/pages/{id}\")"), "non-f literal call leaked:\n{sdk}");
    }

    #[test]
    fn query_param_passes_params_kwarg() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("params=None"));
        assert!(sdk.contains(", params=params)"));
    }

    #[test]
    fn body_endpoint_passes_json_kwarg() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("body=None"));
        assert!(sdk.contains(", json=body)"));
    }

    #[test]
    fn middleware_request_helper_forwards_params_and_json() {
        let eps = vec![ep_with_mw("/me", MiddlewareSpec::bearer_auth())];
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(sdk.contains("def _request(self, method: str, path: str, params=None, json=None)"));
        assert!(sdk.contains("params=params, json=json"));
    }

    #[test]
    fn with_types_emits_typeddict_and_typed_body() {
        use crate::discover::discover_schemas;
        let g = ws(&["wickes-cms"]);
        let eps = discover_endpoints(&g);
        let sdk = generate_python_sdk_with_types(&eps, "http://api", &discover_schemas(&g));
        assert!(sdk.contains("from typing import List, Optional, TypedDict"));
        assert!(sdk.contains("class Page(TypedDict):"), "missing TypedDict:\n{sdk}");
        assert!(sdk.contains("    id: str"));
        assert!(sdk.contains("    title: str"));
        assert!(sdk.contains("    status: Optional[str]"), "optional enum field:\n{sdk}");
        // POST body param annotated Page.
        assert!(sdk.contains("body: Page = None"), "body not typed Page:\n{sdk}");
    }

    #[test]
    fn without_registry_no_typeddict_body_untyped() {
        let eps = discover_endpoints(&ws(&["wickes-cms"]));
        let sdk = generate_python_sdk(&eps, "http://api");
        assert!(!sdk.contains("TypedDict"));
        assert!(sdk.contains("body=None"));
    }
}
