// flux-api · Signed Webhook Handler codegen — the "killer feature".
//
// flux-api already (a) emits typed discriminated-union events (event_types.rs)
// and (b) ships an HMAC-SHA256 webhook delivery engine (fluxc::webhook, which
// signs each POST with header `X-Flux-Signature: sha256=<hex>`). Those two
// halves were disconnected: webhook receivers had to hand-roll signature
// verification and untyped JSON dispatch.
//
// This module closes the loop for the USER: from the same `Vec<EventVariant>`
// source, generate a signature-verifying, *typed* webhook receiver in the
// user's own language — the thing Svix/Stainless charge for, emitted for free
// and guaranteed in-sync with both the event surface and the delivery scheme.

use crate::casing::pascal_case;
use crate::event_types::EventVariant;

/// TypeScript (Node) signed webhook receiver.
///
/// Emits `verifyFluxSignature` (timing-safe HMAC-SHA256 against the
/// `X-Flux-Signature: sha256=<hex>` header fluxc::webhook delivers) plus a
/// typed `handleFluxWebhook(secret, rawBody, sigHeader, handlers)` that parses
/// the body into the discriminated union and dispatches to per-variant
/// callbacks. Pairs 1:1 with `generate_ts_event_types(union_name, variants)`.
pub fn generate_ts_webhook_handler(union_name: &str, variants: &[EventVariant]) -> String {
    let mut s = String::from(
        r#"// Auto-generated by Flux API Builder — Signed Webhook Handler
// Pairs with the typed events from generate_ts_event_types(). Verifies the
// `X-Flux-Signature: sha256=<hmac>` header (the scheme fluxc::webhook delivers)
// then dispatches the parsed body to typed per-variant callbacks.
import { createHmac, timingSafeEqual } from "node:crypto";

/** Verify the `X-Flux-Signature: sha256=<hex>` header (timing-safe). */
export function verifyFluxSignature(secret: string, rawBody: string, signatureHeader: string | null | undefined): boolean {
  if (!signatureHeader) return false;
  const expected = createHmac("sha256", secret).update(rawBody, "utf8").digest("hex");
  const got = signatureHeader.startsWith("sha256=") ? signatureHeader.slice(7) : signatureHeader;
  let a: Buffer, b: Buffer;
  try { a = Buffer.from(expected, "hex"); b = Buffer.from(got, "hex"); } catch { return false; }
  if (a.length === 0 || a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

export interface FluxWebhookResult { ok: boolean; handled?: string; error?: string; }

"#,
    );

    // Typed handlers interface — one optional callback per event variant.
    s.push_str(&format!("export interface {un}Handlers {{\n", un = union_name));
    for v in variants {
        let pas = pascal_case(&v.tag.replace('-', "_"));
        s.push_str(&format!(
            "  on{pas}?: (e: {un}_{pas}) => void | Promise<void>;\n",
            pas = pas,
            un = union_name
        ));
    }
    s.push_str(&format!(
        "  onUnhandled?: (e: {un}) => void | Promise<void>;\n}}\n\n",
        un = union_name
    ));

    // Verify + parse + dispatch.
    s.push_str(&format!(
        "/** Verify the signature, parse the body, dispatch to typed callbacks. */\n\
         export async function handleFluxWebhook(secret: string, rawBody: string, signatureHeader: string | null | undefined, handlers: {un}Handlers): Promise<FluxWebhookResult> {{\n",
        un = union_name
    ));
    s.push_str("  if (!verifyFluxSignature(secret, rawBody, signatureHeader)) return { ok: false, error: \"invalid_signature\" };\n");
    s.push_str(&format!("  let evt: {un};\n", un = union_name));
    s.push_str(&format!(
        "  try {{ evt = JSON.parse(rawBody) as {un}; }} catch {{ return {{ ok: false, error: \"invalid_json\" }}; }}\n",
        un = union_name
    ));
    s.push_str("  switch (evt.type) {\n");
    for v in variants {
        let pas = pascal_case(&v.tag.replace('-', "_"));
        s.push_str(&format!(
            "    case \"{tag}\": await handlers.on{pas}?.(evt); return {{ ok: true, handled: \"{tag}\" }};\n",
            tag = v.tag,
            pas = pas
        ));
    }
    s.push_str(&format!(
        "    default: await handlers.onUnhandled?.(evt as {un}); return {{ ok: true, handled: \"unhandled\" }};\n",
        un = union_name
    ));
    s.push_str("  }\n}\n");
    s
}

/// Python signed webhook receiver (framework-agnostic; pass the raw request
/// body bytes + the `X-Flux-Signature` header). Uses `hmac.compare_digest`
/// for constant-time verification.
pub fn generate_python_webhook_handler(union_name: &str, variants: &[EventVariant]) -> String {
    let mut s = String::from(
        r#"# Auto-generated by Flux API Builder — Signed Webhook Handler
# Pairs with the TypedDicts from generate_python_event_types().
import hmac
import hashlib
import json
from typing import Any, Callable, Dict, Optional


def verify_flux_signature(secret: str, raw_body: bytes, signature_header: Optional[str]) -> bool:
    """Verify the `X-Flux-Signature: sha256=<hex>` header (constant-time)."""
    if not signature_header:
        return False
    expected = hmac.new(secret.encode(), raw_body, hashlib.sha256).hexdigest()
    got = signature_header[7:] if signature_header.startswith("sha256=") else signature_header
    return hmac.compare_digest(expected, got)


def handle_flux_webhook(
    secret: str,
    raw_body: bytes,
    signature_header: Optional[str],
    handlers: Dict[str, Callable[[dict], Any]],
) -> dict:
    """Verify the signature, parse the body, dispatch by event `type`.

    `handlers` is keyed by event tag (e.g. "iterate_complete"); use "*" for a
    catch-all. Returns {"ok": bool, "handled"?: str, "error"?: str}.
    """
    if not verify_flux_signature(secret, raw_body, signature_header):
        return {"ok": False, "error": "invalid_signature"}
    try:
        evt = json.loads(raw_body)
    except Exception:
        return {"ok": False, "error": "invalid_json"}
    cb = handlers.get(evt.get("type")) or handlers.get("*")
    if cb is not None:
        cb(evt)
        return {"ok": True, "handled": evt.get("type")}
    return {"ok": True, "handled": "unhandled"}

"#,
    );
    // Variant-aware footer so the generated file documents the exact surface.
    s.push_str(&format!("# Event tags for {}: ", union_name));
    s.push_str(
        &variants
            .iter()
            .map(|v| v.tag.clone())
            .collect::<Vec<_>>()
            .join(", "),
    );
    s.push('\n');
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event_types::flux_ue_bridge_events;

    #[test]
    fn ts_handler_has_timingsafe_verify_and_typed_dispatch() {
        let ts = generate_ts_webhook_handler("BridgeEvent", &flux_ue_bridge_events());
        assert!(ts.contains("export function verifyFluxSignature"));
        assert!(ts.contains("createHmac(\"sha256\""));
        assert!(ts.contains("timingSafeEqual"));
        // must match the exact header scheme fluxc::webhook delivers
        assert!(ts.contains("sha256="));
        assert!(ts.contains("export async function handleFluxWebhook"));
        assert!(ts.contains("onIterateComplete?:"));
        assert!(ts.contains("case \"iterate_complete\":"));
        assert!(ts.contains("invalid_signature"));
        assert!(ts.contains("invalid_json"));
    }

    #[test]
    fn ts_dispatch_covers_every_variant() {
        let vs = flux_ue_bridge_events();
        let ts = generate_ts_webhook_handler("BridgeEvent", &vs);
        for v in &vs {
            assert!(
                ts.contains(&format!("case \"{}\":", v.tag)),
                "TS dispatch missing case for {}",
                v.tag
            );
        }
    }

    #[test]
    fn py_handler_has_constant_time_verify() {
        let py = generate_python_webhook_handler("BridgeEvent", &flux_ue_bridge_events());
        assert!(py.contains("def verify_flux_signature"));
        assert!(py.contains("hmac.compare_digest"));
        assert!(py.contains("hashlib.sha256"));
        assert!(py.contains("def handle_flux_webhook"));
        assert!(py.contains("iterate_complete"));
    }
}
