// fluxc prune-report — SEMANTIC DEPENDENCY ELIMINATION, report-only (v0.36 task, DeepSeek adopt).
//
// Walks the workspace's cargo dep edges (path-deps incl. dev/build/target deps) starting from
// the `default-members` roots in the root Cargo.toml and reports every member crate the
// load-bearing core can NOT reach — with LOC and last-commit-touch date — into
// docs/PRUNE_REPORT.md. It deletes NOTHING: the report is the input to a human/DeepSeek
// decision about `git rm` / archiving, never the executor.
//
// Reachability definition: a crate is "reachable" iff it appears in the transitive path-dep
// closure of the default-members set. Since default-members is itself maintained as the closure
// of the 10 core roots, unreachable == "no core crate can ever link this in".

use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::path::{Path, PathBuf};

pub fn run(args: &[String]) -> i32 {
    let verbose = args.iter().any(|a| a == "-v" || a == "--verbose");
    let root = match find_workspace_root() {
        Some(r) => r,
        None => {
            eprintln!("prune-report: no workspace Cargo.toml found above {:?}", std::env::current_dir().ok());
            return 1;
        }
    };
    let manifest = match std::fs::read_to_string(root.join("Cargo.toml")) {
        Ok(s) => s,
        Err(e) => { eprintln!("prune-report: read root Cargo.toml: {e}"); return 1; }
    };
    let ws: toml::Value = match manifest.parse() {
        Ok(v) => v,
        Err(e) => { eprintln!("prune-report: parse root Cargo.toml: {e}"); return 1; }
    };
    let ws_tbl = ws.get("workspace").and_then(|w| w.as_table());
    let members_spec: Vec<String> = ws_tbl
        .and_then(|w| w.get("members")).and_then(|m| m.as_array())
        .map(|a| a.iter().filter_map(|v| v.as_str().map(String::from)).collect())
        .unwrap_or_default();
    let default_members: Vec<String> = ws_tbl
        .and_then(|w| w.get("default-members")).and_then(|m| m.as_array())
        .map(|a| a.iter().filter_map(|v| v.as_str().map(String::from)).collect())
        .unwrap_or_default();
    if default_members.is_empty() {
        eprintln!("prune-report: root Cargo.toml has no [workspace] default-members — nothing to walk from");
        return 1;
    }

    // Expand members globs (`crates/*`) into concrete crate dirs (rel paths from root).
    let mut member_dirs: BTreeSet<String> = BTreeSet::new();
    for spec in &members_spec {
        if let Some(prefix) = spec.strip_suffix("/*") {
            if let Ok(rd) = std::fs::read_dir(root.join(prefix)) {
                for e in rd.flatten() {
                    let p = e.path();
                    if p.join("Cargo.toml").is_file() {
                        member_dirs.insert(format!("{}/{}", prefix, e.file_name().to_string_lossy()));
                    }
                }
            }
        } else if root.join(spec).join("Cargo.toml").is_file() {
            member_dirs.insert(spec.clone());
        }
    }

    // BFS the path-dep closure from the default-members roots.
    let mut reachable: BTreeSet<String> = BTreeSet::new();
    let mut queue: VecDeque<String> = default_members.iter().cloned().collect();
    while let Some(dir) = queue.pop_front() {
        if !reachable.insert(dir.clone()) { continue; }
        for dep_dir in path_deps(&root, &dir) {
            if !reachable.contains(&dep_dir) { queue.push_back(dep_dir); }
        }
    }

    // Unreachable = members - reachable. Collect LOC + last-touch for each.
    let mut rows: Vec<(String, u64, String)> = Vec::new(); // (dir, loc, last_commit)
    let mut reachable_loc: u64 = 0;
    for dir in &member_dirs {
        let loc = rust_loc(&root.join(dir));
        if reachable.contains(dir) {
            reachable_loc += loc;
            continue;
        }
        let last = git_last_touch(&root, dir).unwrap_or_else(|| "untracked".into());
        if verbose { eprintln!("unreachable: {dir} ({loc} LOC, last touch {last})"); }
        rows.push((dir.clone(), loc, last));
    }
    // Stalest first, then biggest first.
    rows.sort_by(|a, b| a.2.cmp(&b.2).then(b.1.cmp(&a.1)));

    let total_unreachable_loc: u64 = rows.iter().map(|r| r.1).sum();
    let mut md = String::new();
    md.push_str("# PRUNE REPORT — semantic dependency elimination (report only)\n\n");
    md.push_str(&format!("Generated by `fluxc prune-report` on {}.\n\n", today_utc()));
    md.push_str(&format!(
        "- Workspace members: **{}**\n- Reachable from `default-members` ({} roots): **{}** crates ({} LOC)\n- **Unreachable: {} crates, {} LOC**\n\n",
        member_dirs.len(), default_members.len(), reachable.len(), reachable_loc, rows.len(), total_unreachable_loc
    ));
    md.push_str(
        "Reachability = transitive path-dep closure (deps + dev-deps + build-deps + target deps)\n\
         of the root `Cargo.toml` `default-members` set. An unreachable crate cannot be linked\n\
         into the load-bearing core by any build. THIS REPORT DELETES NOTHING — it is the input\n\
         to an explicit prune/archive decision (swarm + DeepSeek review), never the executor.\n\n",
    );
    md.push_str("| crate | LOC | last commit touch |\n|---|---:|---|\n");
    for (dir, loc, last) in &rows {
        md.push_str(&format!("| `{}` | {} | {} |\n", dir, loc, last));
    }
    md.push('\n');

    let out = root.join("docs").join("PRUNE_REPORT.md");
    if let Err(e) = std::fs::create_dir_all(out.parent().unwrap()) {
        eprintln!("prune-report: mkdir docs/: {e}");
        return 1;
    }
    if let Err(e) = std::fs::write(&out, &md) {
        eprintln!("prune-report: write {}: {e}", out.display());
        return 1;
    }
    println!(
        "prune-report: {} members, {} reachable from {} default-members roots, {} UNREACHABLE ({} LOC) -> {}",
        member_dirs.len(), reachable.len(), default_members.len(), rows.len(), total_unreachable_loc, out.display()
    );
    0
}

/// Walk up from CWD to the first Cargo.toml containing a [workspace] table.
fn find_workspace_root() -> Option<PathBuf> {
    let mut dir = std::env::current_dir().ok()?;
    loop {
        let m = dir.join("Cargo.toml");
        if m.is_file() {
            if let Ok(s) = std::fs::read_to_string(&m) {
                if s.contains("[workspace]") {
                    return Some(dir);
                }
            }
        }
        if !dir.pop() { return None; }
    }
}

/// Path-deps of the crate at `root/dir`, normalized to workspace-relative dirs.
/// Covers [dependencies], [dev-dependencies], [build-dependencies] and every
/// [target.'cfg'.…] variant. Deps escaping the workspace root are ignored
/// (reported once by the caller via reachability anyway).
fn path_deps(root: &Path, dir: &str) -> Vec<String> {
    let Ok(s) = std::fs::read_to_string(root.join(dir).join("Cargo.toml")) else { return Vec::new(); };
    let Ok(v) = s.parse::<toml::Value>() else { return Vec::new(); };
    let mut sections: Vec<&toml::value::Table> = Vec::new();
    for key in ["dependencies", "dev-dependencies", "build-dependencies"] {
        if let Some(t) = v.get(key).and_then(|t| t.as_table()) { sections.push(t); }
    }
    if let Some(targets) = v.get("target").and_then(|t| t.as_table()) {
        for tgt in targets.values() {
            for key in ["dependencies", "dev-dependencies", "build-dependencies"] {
                if let Some(t) = tgt.get(key).and_then(|t| t.as_table()) { sections.push(t); }
            }
        }
    }
    let mut out = Vec::new();
    for sec in sections {
        for spec in sec.values() {
            let Some(p) = spec.get("path").and_then(|p| p.as_str()) else { continue; };
            let abs = normalize(&root.join(dir).join(p));
            if let Ok(rel) = abs.strip_prefix(&normalize(root)) {
                out.push(rel.to_string_lossy().replace('\\', "/"));
            }
        }
    }
    out
}

/// Lexical `..`/`.` normalization (no symlink resolution — keeps missing paths workable).
fn normalize(p: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for c in p.components() {
        match c {
            std::path::Component::ParentDir => { out.pop(); }
            std::path::Component::CurDir => {}
            other => out.push(other.as_os_str()),
        }
    }
    out
}

/// Total lines across every .rs file under the crate dir (src, tests, benches, examples).
fn rust_loc(dir: &Path) -> u64 {
    let mut total = 0u64;
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&d) else { continue; };
        for e in rd.flatten() {
            let p = e.path();
            let Ok(ft) = e.file_type() else { continue; };
            if ft.is_dir() {
                if p.file_name().map_or(false, |n| n == "target" || n == ".git") { continue; }
                stack.push(p);
            } else if p.extension().map_or(false, |x| x == "rs") {
                if let Ok(s) = std::fs::read_to_string(&p) {
                    total += s.lines().count() as u64;
                }
            }
        }
    }
    total
}

/// `git log -1 --format=%cs -- <dir>` — the last commit date (YYYY-MM-DD) that touched the crate.
fn git_last_touch(root: &Path, dir: &str) -> Option<String> {
    let out = std::process::Command::new("git")
        .current_dir(root)
        .args(["log", "-1", "--format=%cs", "--", dir])
        .stdin(std::process::Stdio::null())
        .output()
        .ok()?;
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() { None } else { Some(s) }
}

fn today_utc() -> String {
    // Date from epoch days — avoids pulling a chrono dep for one line.
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let days = secs / 86_400;
    // Civil-from-days (Howard Hinnant's algorithm).
    let z = days as i64 + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{:04}-{:02}-{:02}", y, m, d)
}
