#![cfg(test)]

pub struct Circuit {
    pub round: u8,
    pub name: &'static str,
    pub country: &'static str,
    pub length_km: f64,
    pub corners: u8,
    pub drs_zones: u8,
    pub elevation_m: u16,
    pub tyre_stress: u8,
    pub overtaking: u8,
    pub character: &'static str,
    pub lore: &'static str,
}

pub fn season_2026_circuits() -> Vec<Circuit> {
    vec![
        Circuit {
            round: 1,
            name: "Bahrain International Circuit",
            country: "Bahrain",
            length_km: 5.412,
            corners: 15,
            drs_zones: 3,
            elevation_m: 12,
            tyre_stress: 4,
            overtaking: 5,
            character: "Desert track with long straights and heavy braking zones",
            lore: "The Sakhir circuit's shifting desert sands create ever-changing grip levels that catch out even champions.",
        },
        Circuit {
            round: 2,
            name: "Jeddah Corniche Circuit",
            country: "Saudi Arabia",
            length_km: 6.174,
            corners: 27,
            drs_zones: 3,
            elevation_m: 8,
            tyre_stress: 5,
            overtaking: 6,
            character: "Ultra-fast street circuit with blind corners and high commitment",
            lore: "Jeddah's relentless high-speed corners demand absolute trust in the car's downforce and driver nerve.",
        },
        Circuit {
            round: 3,
            name: "Albert Park Circuit",
            country: "Australia",
            length_km: 5.303,
            corners: 14,
            drs_zones: 4,
            elevation_m: 6,
            tyre_stress: 3,
            overtaking: 4,
            character: "Semi-street parkland track with fast flowing corners",
            lore: "The lakeside park circuit's mix of natural undulations and temporary barriers creates a unique visual spectacle.",
        },
        Circuit {
            round: 4,
            name: "Suzuka International Racing Course",
            country: "Japan",
            length_km: 5.807,
            corners: 18,
            drs_zones: 2,
            elevation_m: 40,
            tyre_stress: 5,
            overtaking: 3,
            character: "Classic figure‑eight with high‑speed esses and technical final sector",
            lore: "Suzuka's unique figure‑eight layout tests every aspect of a car's balance and a driver's precision.",
        },
        Circuit {
            round: 5,
            name: "Shanghai International Circuit",
            country: "China",
            length_km: 5.451,
            corners: 16,
            drs_zones: 2,
            elevation_m: 8,
            tyre_stress: 4,
            overtaking: 5,
            character: "Modern track with long back straight and tight hairpin sequence",
            lore: "Shanghai's complex turn‑1‑2‑3 complex and massive main straight reward overtaking bravery.",
        },
        Circuit {
            round: 6,
            name: "Miami International Autodrome",
            country: "United States",
            length_km: 5.412,
            corners: 19,
            drs_zones: 3,
            elevation_m: 6,
            tyre_stress: 4,
            overtaking: 4,
            character: "Temporary street circuit with a marina vibe and high‑speed sections",
            lore: "Miami's relentless heat and tricky braking zones turn the midfield into a battle of tyre management.",
        },
        Circuit {
            round: 7,
            name: "Autodromo Enzo e Dino Ferrari",
            country: "Italy",
            length_km: 4.909,
            corners: 19,
            drs_zones: 2,
            elevation_m: 36,
            tyre_stress: 4,
            overtaking: 3,
            character: "Temple of speed with long straights and sharp chicanes",
            lore: "Imola's historic parkland layout punishes even the slightest mistake with unforgiving gravel traps.",
        },
        Circuit {
            round: 8,
            name: "Circuit de Monaco",
            country: "Monaco",
            length_km: 3.337,
            corners: 19,
            drs_zones: 1,
            elevation_m: 42,
            tyre_stress: 5,
            overtaking: 1,
            character: "Legendary street circuit with tight barriers and dramatic elevation change",
            lore: "Monaco's narrow streets and lack of runoff make qualifying the most nerve‑wracking hour of the season.",
        },
        Circuit {
            round: 9,
            name: "Madrid Street Circuit",
            country: "Spain",
            length_km: 5.400,
            corners: 20,
            drs_zones: 2,
            elevation_m: 15,
            tyre_stress: 4,
            overtaking: 5,
            character: "Modern urban circuit with flowing sections and a mix of straights",
            lore: "Madrid's brand‑new circuit blends traditional Spanish flair with cutting‑edge safety and layout design.",
        },
        Circuit {
            round: 10,
            name: "Circuit Gilles Villeneuve",
            country: "Canada",
            length_km: 4.361,
            corners: 14,
            drs_zones: 2,
            elevation_m: 4,
            tyre_stress: 3,
            overtaking: 7,
            character: "Semi‑permanent island track with long straights and chicanes",
            lore: "Montreal's wall‑of‑champions and unpredictable weather turn every race into a survival test.",
        },
        Circuit {
            round: 11,
            name: "Red Bull Ring",
            country: "Austria",
            length_km: 4.318,
            corners: 10,
            drs_zones: 3,
            elevation_m: 65,
            tyre_stress: 3,
            overtaking: 8,
            character: "Short, fast track with massive straights and only three heavy braking zones",
            lore: "The Red Bull Ring's short lap and high‑speed straights create bumper‑to‑bumper action every corner.",
        },
        Circuit {
            round: 12,
            name: "Silverstone Circuit",
            country: "Great Britain",
            length_km: 5.891,
            corners: 18,
            drs_zones: 2,
            elevation_m: 15,
            tyre_stress: 4,
            overtaking: 6,
            character: "High‑speed sweepers and historic layout demanding high downforce",
            lore: "Silverstone's legendary Copse and Maggots‑Becketts sequence churn through tyres at a ferocious rate.",
        },
        Circuit {
            round: 13,
            name: "Hungaroring",
            country: "Hungary",
            length_km: 4.381,
            corners: 14,
            drs_zones: 2,
            elevation_m: 30,
            tyre_stress: 4,
            overtaking: 2,
            character: "Twisty, low‑speed track with heavy emphasis on downforce and tyre management",
            lore: "Budapest's tight, dusty circuit forces drivers to treat their rear tyres like raw eggs in the heat.",
        },
        Circuit {
            round: 14,
            name: "Circuit de Spa-Francorchamps",
            country: "Belgium",
            length_km: 7.004,
            corners: 19,
            drs_zones: 2,
            elevation_m: 100,
            tyre_stress: 4,
            overtaking: 7,
            character: "Epic undulating layout with famous Eau Rouge and long straight",
            lore: "Spa's microclimate can batter the field with rain on one side and sun on the other within a single lap.",
        },
        Circuit {
            round: 15,
            name: "Circuit Zandvoort",
            country: "Netherlands",
            length_km: 4.259,
            corners: 14,
            drs_zones: 2,
            elevation_m: 8,
            tyre_stress: 5,
            overtaking: 3,
            character: "Old‑school banked corners and a short, intense lap",
            lore: "Zandvoort's banked turns and narrow track leave no room for error amid the orange‑clad crowd.",
        },
        Circuit {
            round: 16,
            name: "Autodromo Nazionale di Monza",
            country: "Italy",
            length_km: 5.793,
            corners: 11,
            drs_zones: 3,
            elevation_m: 10,
            tyre_stress: 3,
            overtaking: 8,
            character: "Temple of speed with long straights and famous Lesmos and Parabolica",
            lore: "Monza's low‑downforce configuration and slipstream battles produce the season's most thrilling slipstream duels.",
        },
        Circuit {
            round: 17,
            name: "Baku City Circuit",
            country: "Azerbaijan",
            length_km: 6.003,
            corners: 20,
            drs_zones: 2,
            elevation_m: 10,
            tyre_stress: 4,
            overtaking: 5,
            character: "Fast street circuit with a massive castle section and 2.2 km straight",
            lore: "Baku's castle walls and blind crests create a delicate balance between bravery and patience.",
        },
        Circuit {
            round: 18,
            name: "Marina Bay Street Circuit",
            country: "Singapore",
            length_km: 5.063,
            corners: 19,
            drs_zones: 2,
            elevation_m: 6,
            tyre_stress: 5,
            overtaking: 3,
            character: "Night street circuit with tight walls and tropical humidity",
            lore: "Singapore's sauna‑like heat and bumpy streets push hydration and neck strength to the absolute limit.",
        },
        Circuit {
            round: 19,
            name: "Circuit of the Americas",
            country: "United States",
            length_km: 5.513,
            corners: 20,
            drs_zones: 2,
            elevation_m: 40,
            tyre_stress: 4,
            overtaking: 6,
            character: "Modern circuit with a steep uphill first turn and fast sweeping sections",
            lore: "COTA's combination of long straights and heavy braking zones rewards both power and late braking.",
        },
        Circuit {
            round: 20,
            name: "Autódromo Hermanos Rodríguez",
            country: "Mexico",
            length_km: 4.304,
            corners: 17,
            drs_zones: 2,
            elevation_m: 2200,
            tyre_stress: 3,
            overtaking: 4,
            character: "High‑altitude track with a long back straight and stadium section",
            lore: "Mexico City's thin air strips downforce and makes even the most powerful engines gasp for oxygen.",
        },
        Circuit {
            round: 21,
            name: "Autódromo José Carlos Pace",
            country: "Brazil",
            length_km: 4.309,
            corners: 15,
            drs_zones: 2,
            elevation_m: 760,
            tyre_stress: 4,
            overtaking: 6,
            character: "Bumpy, anti‑clockwise circuit with a famous downhill Senna S",
            lore: "Interlagos' unique anti‑clockwise layout and bumpy surface create a chaotic, fan‑favourite race.",
        },
        Circuit {
            round: 22,
            name: "Las Vegas Strip Circuit",
            country: "United States",
            length_km: 6.201,
            corners: 17,
            drs_zones: 3,
            elevation_m: 4,
            tyre_stress: 3,
            overtaking: 4,
            character: "High‑speed street circuit with neon glitz and long straights",
            lore: "Las Vegas' cold desert nights force teams to warm tyres like blankets at a winter sleepover.",
        },
        Circuit {
            round: 23,
            name: "Lusail International Circuit",
            country: "Qatar",
            length_km: 5.380,
            corners: 16,
            drs_zones: 2,
            elevation_m: 20,
            tyre_stress: 5,
            overtaking: 5,
            character: "Modern floodlit track with fast corners and high kerb usage",
            lore: "Qatar's searing heat on the kerbs strips rubber and punishes any mistake with massive tyre wear.",
        },
        Circuit {
            round: 24,
            name: "Yas Marina Circuit",
            country: "United Arab Emirates",
            length_km: 5.281,
            corners: 16,
            drs_zones: 2,
            elevation_m: 8,
            tyre_stress: 3,
            overtaking: 3,
            character: "Day‑to‑night track with a long straight and hotel section",
            lore: "Abu Dhabi's sunset start creates a beautiful fade from daylight into the glow of the Yas Hotel.",
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_circuit_count() {
        let circuits = season_2026_circuits();
        assert_eq!(circuits.len(), 24, "There must be exactly 24 circuits in the 2026 season");
    }

    #[test]
    fn test_unique_names() {
        let circuits = season_2026_circuits();
        let names: std::collections::HashSet<&str> = circuits.iter().map(|c| c.name).collect();
        assert_eq!(names.len(), circuits.len(), "All circuit names must be unique");
    }

    #[test]
    fn test_field_ranges() {
        let circuits = season_2026_circuits();
        let mut rounds: Vec<u8> = circuits.iter().map(|c| c.round).collect();
        rounds.sort_unstable();
        assert_eq!(rounds, (1..=24).collect::<Vec<u8>>(), "Rounds must be 1 through 24 exactly");

        for c in circuits {
            assert!(c.length_km > 0.0, "Length must be positive for circuit {}", c.name);
            assert!(c.corners > 0, "Corners must be positive for circuit {}", c.name);
            assert!(c.drs_zones >= 1, "DRS zones must be at least 1 for circuit {}", c.name);
            assert!(c.elevation_m <= 3000, "Elevation too high for circuit {}", c.name);
            assert!((1..=5).contains(&c.tyre_stress), "Tyre stress must be 1-5 for circuit {}", c.name);
            assert!((1..=10).contains(&c.overtaking), "Overtaking rating must be 1-10 for circuit {}", c.name);
            assert!(!c.character.is_empty(), "Character must not be empty for circuit {}", c.name);
            assert!(!c.lore.is_empty(), "Lore must not be empty for circuit {}", c.name);
        }
    }
}
