//! invoice.rs — real Danish invoices for the flux/sigil business (CVR + moms).
//!
//! GENERATE-only: builds a proper faktura (CVR, 25% moms/VAT, line items, due
//! date, payment reference) and renders HTML. The agent NEVER collects money,
//! signs with NemID/MitID, or pulls a customer's funds — YOU send the invoice and
//! the customer pays your account/MobilePay directly. This is the honest path to
//! rocky's first real revenue: an invoice for delivered work, paid to your CVR.

pub const MOMS_RATE: f64 = 0.25; // Danish standard VAT 25%

#[derive(Debug, Clone)]
pub struct Party {
    pub name: String,
    pub cvr: Option<String>, // seller has a CVR; buyer may
    pub address: String,
}

#[derive(Debug, Clone)]
pub struct LineItem {
    pub description: String,
    pub qty: f64,
    pub unit_price_dkk: f64,
}
impl LineItem {
    pub fn amount(&self) -> f64 { self.qty * self.unit_price_dkk }
}

#[derive(Debug, Clone)]
pub struct Invoice {
    pub number: String,
    pub date: String,        // ISO yyyy-mm-dd
    pub due_date: String,
    pub seller: Party,
    pub buyer: Party,
    pub items: Vec<LineItem>,
    /// "Betales til" — your bank reg+konto, IBAN, or MobilePay. The customer pays
    /// THIS directly; the agent never touches it.
    pub pay_to: String,
}

impl Invoice {
    pub fn subtotal(&self) -> f64 { self.items.iter().map(|i| i.amount()).sum() }
    pub fn moms(&self) -> f64 { self.subtotal() * MOMS_RATE }
    pub fn total(&self) -> f64 { self.subtotal() + self.moms() }

    /// Render a clean HTML faktura (deployable / printable). All amounts in DKK.
    pub fn render_html(&self) -> String {
        let rows: String = self.items.iter().map(|i| format!(
            "<tr><td>{}</td><td class=r>{:.2}</td><td class=r>{:.2}</td><td class=r>{:.2}</td></tr>",
            html_escape(&i.description), i.qty, i.unit_price_dkk, i.amount())).collect();
        let cvr_seller = self.seller.cvr.as_deref().unwrap_or("—");
        format!(
"<!doctype html><html lang=da><meta charset=utf-8><title>Faktura {num}</title>
<style>body{{font-family:Inter,system-ui,sans-serif;max-width:760px;margin:40px auto;color:#1a1428}}
h1{{color:#8b5cf6}} table{{width:100%;border-collapse:collapse;margin:18px 0}}
td,th{{padding:8px;border-bottom:1px solid #eee;text-align:left}} .r{{text-align:right}}
.tot{{font-weight:700}} .box{{background:#faf8ff;padding:14px;border-radius:8px}}</style>
<h1>Faktura</h1>
<div class=box>
<b>{sname}</b> · CVR {scvr}<br>{saddr}<br>
<small>Betales til: {payto}</small>
</div>
<p>Faktura nr.: <b>{num}</b> · Fakturadato: {date} · Forfaldsdato: <b>{due}</b></p>
<p><b>Kunde:</b> {bname}{bcvr}<br>{baddr}</p>
<table><tr><th>Beskrivelse</th><th class=r>Antal</th><th class=r>Stk-pris</th><th class=r>Beløb</th></tr>
{rows}
<tr><td colspan=3 class=r>Subtotal (ekskl. moms)</td><td class=r>{sub:.2}</td></tr>
<tr><td colspan=3 class=r>Moms (25%)</td><td class=r>{moms:.2}</td></tr>
<tr class=tot><td colspan=3 class=r>I alt at betale (DKK)</td><td class=r>{tot:.2}</td></tr>
</table>
<small>Generated by flux-invoice — propose-only. Customer pays the account above directly; no auto-collection.</small>
</html>",
            num=html_escape(&self.number), sname=html_escape(&self.seller.name), scvr=cvr_seller,
            saddr=html_escape(&self.seller.address), payto=html_escape(&self.pay_to),
            date=self.date, due=self.due_date, bname=html_escape(&self.buyer.name),
            bcvr=self.buyer.cvr.as_deref().map(|c| format!(" · CVR {c}")).unwrap_or_default(),
            baddr=html_escape(&self.buyer.address), rows=rows,
            sub=self.subtotal(), moms=self.moms(), tot=self.total())
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&',"&amp;").replace('<',"&lt;").replace('>',"&gt;")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Invoice {
        Invoice {
            number: "2026-001".into(), date: "2026-06-01".into(), due_date: "2026-06-15".into(),
            seller: Party { name: "Flux/SIGIL".into(), cvr: Some("12345678".into()), address: "København, DK".into() },
            buyer: Party { name: "Acme ApS".into(), cvr: Some("87654321".into()), address: "Aarhus, DK".into() },
            items: vec![
                LineItem { description: "flux-moe agentic LLM integration".into(), qty: 10.0, unit_price_dkk: 1200.0 },
                LineItem { description: "GPU CUDA miner (2.36 GH/s)".into(), qty: 1.0, unit_price_dkk: 5000.0 },
            ],
            pay_to: "MobilePay 12345 / IBAN DK00 0000 0000 0000 00".into(),
        }
    }

    #[test]
    fn moms_is_25_percent_and_total_adds_up() {
        let inv = sample();
        assert!((inv.subtotal() - 17_000.0).abs() < 1e-6); // 10*1200 + 5000
        assert!((inv.moms() - 4_250.0).abs() < 1e-6);       // 25%
        assert!((inv.total() - 21_250.0).abs() < 1e-6);     // subtotal*1.25
    }

    #[test]
    fn html_has_cvr_moms_total_and_payment() {
        let h = sample().render_html();
        assert!(h.contains("CVR 12345678"));
        assert!(h.contains("Moms (25%)"));
        assert!(h.contains("21250.00"));
        assert!(h.contains("MobilePay")); // customer pays directly
        assert!(h.contains("Faktura nr."));
    }

    #[test]
    fn escapes_html_in_descriptions() {
        let mut inv = sample();
        inv.items[0].description = "a & <b>".into();
        assert!(inv.render_html().contains("a &amp; &lt;b&gt;"));
    }
}
