//! flux-arxiv-latex — turn arxiv-mcp-server results into Flux LaTeX.
//!
//! [blazickjp/arxiv-mcp-server](https://github.com/blazickjp/arxiv-mcp-server)
//! searches/fetches arXiv papers over MCP. This crate is the **flux-latex** side
//! of that integration: it parses the JSON the MCP returns and emits LaTeX —
//! BibTeX entries + a cite-ready `\section{Related Work}` — properly escaped, so
//! an `arxiv search` result drops straight into a flux-built paper (the
//! flux-foundation / SIGIL whitepapers, the fluxc cheatsheet, …).
//!
//! ```
//! # use flux_arxiv_latex::*;
//! let papers = parse_arxiv_json(r#"{"papers":[{"id":"2305.12345","title":"A & B","authors":["Ada L."],"summary":"On x_y.","published":"2023-05-01","categories":["cs.DC"]}]}"#).unwrap();
//! let bib = bibliography(&papers);
//! assert!(bib.contains("@misc{arxiv2305_12345"));
//! assert!(bib.contains(r"A \& B"));            // LaTeX-escaped
//! ```

use anyhow::Result;
use serde::Deserialize;

/// LaTeX document builder (assemble + render + compile a whole `.tex`).
pub mod doc;
pub use doc::{Block, Document, PdfResult};

/// One arXiv paper, tolerant of the arxiv-mcp-server field variants.
#[derive(Debug, Clone, Deserialize)]
pub struct ArxivPaper {
    pub id: String,
    #[serde(default)]
    pub title: String,
    #[serde(default)]
    pub authors: Vec<String>,
    /// `summary` (arXiv) or `abstract` — accept both.
    #[serde(default, alias = "abstract")]
    pub summary: String,
    #[serde(default)]
    pub published: String,
    #[serde(default)]
    pub categories: Vec<String>,
    #[serde(default, alias = "pdf_url", alias = "resource_uri")]
    pub url: String,
}

impl ArxivPaper {
    /// A stable BibTeX cite key, e.g. `arxiv2305_12345`.
    pub fn cite_key(&self) -> String {
        let core: String = self
            .id
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
            .collect();
        format!("arxiv{core}")
    }
    fn year(&self) -> &str {
        self.published.get(0..4).unwrap_or("")
    }
}

/// Escape the LaTeX special characters so titles/abstracts compile.
pub fn latex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '&' | '%' | '$' | '#' | '_' | '{' | '}' => {
                out.push('\\');
                out.push(c);
            }
            '~' => out.push_str(r"\textasciitilde{}"),
            '^' => out.push_str(r"\textasciicircum{}"),
            '\\' => out.push_str(r"\textbackslash{}"),
            _ => out.push(c),
        }
    }
    out
}

/// One BibTeX `@misc` entry for an arXiv paper (the standard arXiv form).
pub fn to_bibtex(p: &ArxivPaper) -> String {
    let authors = if p.authors.is_empty() {
        "Unknown".to_string()
    } else {
        p.authors.iter().map(|a| latex_escape(a)).collect::<Vec<_>>().join(" and ")
    };
    format!(
        "@misc{{{key},\n  title        = {{{title}}},\n  author       = {{{authors}}},\n  year         = {{{year}}},\n  eprint       = {{{id}}},\n  archivePrefix= {{arXiv}},\n  primaryClass = {{{primary}}},\n  url          = {{{url}}}\n}}",
        key = p.cite_key(),
        title = latex_escape(&p.title),
        authors = authors,
        year = p.year(),
        id = p.id,
        primary = p.categories.first().map(|s| s.as_str()).unwrap_or(""),
        url = if p.url.is_empty() { format!("https://arxiv.org/abs/{}", p.id) } else { p.url.clone() },
    )
}

/// A complete `.bib` for a set of papers.
pub fn bibliography(papers: &[ArxivPaper]) -> String {
    let mut out = String::from("% Generated by flux-arxiv-latex from arxiv-mcp-server results.\n");
    for p in papers {
        out.push_str(&to_bibtex(p));
        out.push_str("\n\n");
    }
    out
}

/// A `\section{Related Work}` that cites each paper with a one-line gloss from
/// its abstract (first sentence, truncated, escaped).
pub fn related_work_section(papers: &[ArxivPaper]) -> String {
    let mut out = String::from("\\section{Related Work}\n");
    for p in papers {
        let gloss = p.summary.split(['.', '\n']).next().unwrap_or("").trim();
        let gloss: String = gloss.chars().take(200).collect();
        out.push_str(&format!(
            "\\textcite{{{key}}} ({title}): {gloss}.\\\\\n",
            key = p.cite_key(),
            title = latex_escape(&p.title),
            gloss = latex_escape(&gloss),
        ));
    }
    out
}

/// Parse the arxiv-mcp-server response. Accepts a bare array, or an object with
/// a `papers` / `results` / `data` array, or a single paper object.
pub fn parse_arxiv_json(json: &str) -> Result<Vec<ArxivPaper>> {
    let v: serde_json::Value = serde_json::from_str(json)?;
    let arr = if v.is_array() {
        v
    } else if let Some(a) = v.get("papers").or_else(|| v.get("results")).or_else(|| v.get("data")) {
        a.clone()
    } else {
        // single paper object
        serde_json::Value::Array(vec![v])
    };
    Ok(serde_json::from_value(arr)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"{"papers":[
      {"id":"2305.12345","title":"DAG-KNIGHT & 50% Trees","authors":["Ada Lovelace","Alan T."],"abstract":"A parallel BlockDAG under x_y conditions. More text.","published":"2023-05-01","categories":["cs.DC","cs.CR"]},
      {"id":"1706.03762","title":"Attention Is All You Need","authors":["A. Vaswani"],"summary":"The Transformer.","published":"2017-06-12","categories":["cs.CL"]}
    ]}"#;

    #[test]
    fn parses_mcp_response() {
        let p = parse_arxiv_json(SAMPLE).unwrap();
        assert_eq!(p.len(), 2);
        assert_eq!(p[0].id, "2305.12345");
        assert_eq!(p[0].authors.len(), 2);
        assert_eq!(p[1].summary, "The Transformer."); // `summary` alias
    }

    #[test]
    fn escapes_latex_specials() {
        assert_eq!(latex_escape("a & b_c 50% #x"), r"a \& b\_c 50\% \#x");
    }

    #[test]
    fn bibtex_is_well_formed_and_escaped() {
        let p = parse_arxiv_json(SAMPLE).unwrap();
        let b = to_bibtex(&p[0]);
        assert!(b.contains("@misc{arxiv2305_12345,"));
        assert!(b.contains(r"DAG-KNIGHT \& 50\% Trees")); // escaped title
        assert!(b.contains("author       = {Ada Lovelace and Alan T.}"));
        assert!(b.contains("year         = {2023}"));
        assert!(b.contains("archivePrefix= {arXiv}"));
    }

    #[test]
    fn related_work_cites_each_paper() {
        let p = parse_arxiv_json(SAMPLE).unwrap();
        let rw = related_work_section(&p);
        assert!(rw.starts_with("\\section{Related Work}"));
        assert!(rw.contains("\\textcite{arxiv2305_12345}"));
        assert!(rw.contains("\\textcite{arxiv1706_03762}"));
    }

    #[test]
    fn handles_bare_array_and_single_object() {
        assert_eq!(parse_arxiv_json(r#"[{"id":"1"},{"id":"2"}]"#).unwrap().len(), 2);
        assert_eq!(parse_arxiv_json(r#"{"id":"solo"}"#).unwrap().len(), 1);
    }
}
